#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"

typedef enum {
    ADVANCEMENT_GRANT,
    ADVANCEMENT_REVOKE
} AdvancementAction;

#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/advancement_everything_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run advancement grant $(target) everything\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_everything_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run advancement revoke $(target) everything\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_only_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run advancement grant $(target) only $(advancement)\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_only_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run advancement revoke $(target) only $(advancement)\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_only_criterion_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run advancement grant $(target) only $(advancement) $(criterion)\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_only_criterion_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run advancement revoke $(target) only $(advancement) $(criterion)\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_from_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run advancement grant $(target) from $(advancement)\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_from_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run advancement revoke $(target) from $(advancement)\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_through_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run advancement grant $(target) through $(advancement)\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_through_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run advancement revoke $(target) through $(advancement)\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_until_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run advancement grant $(target) until $(advancement)\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_until_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run advancement revoke $(target) until $(advancement)\n"
"    ret\n"
);

static inline int
advancement_everything_unsafe(AdvancementAction action, McfStrRef target_ref)
{
    int ret;
    int target_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }

    switch (action) {
        case ADVANCEMENT_GRANT:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/advancement_everything_unsafe_exec_0 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case ADVANCEMENT_REVOKE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/advancement_everything_unsafe_exec_1 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
advancement_everything(AdvancementAction action, Target target)
{
    McfStrRef target_ref;
    int target_slot;

    target_ref = _Command_RequireTargetRef(target);
    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }
    return advancement_everything_unsafe(action, target_ref);
}

static inline int
advancement_only_unsafe(AdvancementAction action, McfStrRef target_ref, McfStrRef advancement_ref)
{
    int ret;
    int target_slot;
    int advancement_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    advancement_slot = McfStrRef_SlotId(advancement_ref);
    if (target_slot < 0 || advancement_slot < 0) {
        return -1;
    }

    switch (action) {
        case ADVANCEMENT_GRANT:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.advancement set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(target_slot), "r"(advancement_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/advancement_only_unsafe_exec_0 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case ADVANCEMENT_REVOKE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.advancement set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(target_slot), "r"(advancement_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/advancement_only_unsafe_exec_1 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
advancement_only(AdvancementAction action, Target target, const Identifier * advancement)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef advancement_ref;
    int target_slot;
    int advancement_slot;

    target_ref = _Command_RequireTargetRef(target);
    advancement_ref = _Command_RequireIdentifierRef(advancement);
    target_slot = McfStrRef_SlotId(target_ref);
    advancement_slot = McfStrRef_SlotId(advancement_ref);
    if (target_slot < 0 || advancement_slot < 0) {
        McfStrRef_Release(advancement_ref);
        return -1;
    }

    ret = advancement_only_unsafe(action, target_ref, advancement_ref);
    McfStrRef_Release(advancement_ref);
    return ret;
}

static inline int
advancement_only_criterion_unsafe(AdvancementAction action, McfStrRef target_ref, McfStrRef advancement_ref, McfStrRef criterion_ref)
{
    int ret;
    int target_slot;
    int advancement_slot;
    int criterion_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    advancement_slot = McfStrRef_SlotId(advancement_ref);
    criterion_slot = McfStrRef_SlotId(criterion_ref);
    if (target_slot < 0 || advancement_slot < 0 || criterion_slot < 0) {
        return -1;
    }

    switch (action) {
        case ADVANCEMENT_GRANT:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.advancement set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.criterion set from storage std:vm mcstr.slots[%2].value"
                :
                : "r"(target_slot), "r"(advancement_slot), "r"(criterion_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/advancement_only_criterion_unsafe_exec_0 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case ADVANCEMENT_REVOKE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.advancement set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.criterion set from storage std:vm mcstr.slots[%2].value"
                :
                : "r"(target_slot), "r"(advancement_slot), "r"(criterion_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/advancement_only_criterion_unsafe_exec_1 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
advancement_only_criterion(AdvancementAction action, Target target, const Identifier * advancement, String criterion)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef advancement_ref;
    McfStrRef criterion_ref;
    int target_slot;
    int advancement_slot;
    int criterion_slot;

    target_ref = _Command_RequireTargetRef(target);
    advancement_ref = _Command_RequireIdentifierRef(advancement);
    criterion_ref = _Command_RequireStringRef(criterion);
    target_slot = McfStrRef_SlotId(target_ref);
    advancement_slot = McfStrRef_SlotId(advancement_ref);
    criterion_slot = McfStrRef_SlotId(criterion_ref);
    if (target_slot < 0 || advancement_slot < 0 || criterion_slot < 0) {
        McfStrRef_Release(advancement_ref);
        return -1;
    }

    ret = advancement_only_criterion_unsafe(action, target_ref, advancement_ref, criterion_ref);
    McfStrRef_Release(advancement_ref);
    return ret;
}

static inline int
advancement_from_unsafe(AdvancementAction action, McfStrRef target_ref, McfStrRef advancement_ref)
{
    int ret;
    int target_slot;
    int advancement_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    advancement_slot = McfStrRef_SlotId(advancement_ref);
    if (target_slot < 0 || advancement_slot < 0) {
        return -1;
    }

    switch (action) {
        case ADVANCEMENT_GRANT:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.advancement set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(target_slot), "r"(advancement_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/advancement_from_unsafe_exec_0 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case ADVANCEMENT_REVOKE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.advancement set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(target_slot), "r"(advancement_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/advancement_from_unsafe_exec_1 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
advancement_from(AdvancementAction action, Target target, const Identifier * advancement)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef advancement_ref;
    int target_slot;
    int advancement_slot;

    target_ref = _Command_RequireTargetRef(target);
    advancement_ref = _Command_RequireIdentifierRef(advancement);
    target_slot = McfStrRef_SlotId(target_ref);
    advancement_slot = McfStrRef_SlotId(advancement_ref);
    if (target_slot < 0 || advancement_slot < 0) {
        McfStrRef_Release(advancement_ref);
        return -1;
    }

    ret = advancement_from_unsafe(action, target_ref, advancement_ref);
    McfStrRef_Release(advancement_ref);
    return ret;
}

static inline int
advancement_through_unsafe(AdvancementAction action, McfStrRef target_ref, McfStrRef advancement_ref)
{
    int ret;
    int target_slot;
    int advancement_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    advancement_slot = McfStrRef_SlotId(advancement_ref);
    if (target_slot < 0 || advancement_slot < 0) {
        return -1;
    }

    switch (action) {
        case ADVANCEMENT_GRANT:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.advancement set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(target_slot), "r"(advancement_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/advancement_through_unsafe_exec_0 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case ADVANCEMENT_REVOKE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.advancement set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(target_slot), "r"(advancement_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/advancement_through_unsafe_exec_1 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
advancement_through(AdvancementAction action, Target target, const Identifier * advancement)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef advancement_ref;
    int target_slot;
    int advancement_slot;

    target_ref = _Command_RequireTargetRef(target);
    advancement_ref = _Command_RequireIdentifierRef(advancement);
    target_slot = McfStrRef_SlotId(target_ref);
    advancement_slot = McfStrRef_SlotId(advancement_ref);
    if (target_slot < 0 || advancement_slot < 0) {
        McfStrRef_Release(advancement_ref);
        return -1;
    }

    ret = advancement_through_unsafe(action, target_ref, advancement_ref);
    McfStrRef_Release(advancement_ref);
    return ret;
}

static inline int
advancement_until_unsafe(AdvancementAction action, McfStrRef target_ref, McfStrRef advancement_ref)
{
    int ret;
    int target_slot;
    int advancement_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    advancement_slot = McfStrRef_SlotId(advancement_ref);
    if (target_slot < 0 || advancement_slot < 0) {
        return -1;
    }

    switch (action) {
        case ADVANCEMENT_GRANT:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.advancement set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(target_slot), "r"(advancement_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/advancement_until_unsafe_exec_0 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case ADVANCEMENT_REVOKE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.advancement set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(target_slot), "r"(advancement_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/advancement_until_unsafe_exec_1 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
advancement_until(AdvancementAction action, Target target, const Identifier * advancement)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef advancement_ref;
    int target_slot;
    int advancement_slot;

    target_ref = _Command_RequireTargetRef(target);
    advancement_ref = _Command_RequireIdentifierRef(advancement);
    target_slot = McfStrRef_SlotId(target_ref);
    advancement_slot = McfStrRef_SlotId(advancement_ref);
    if (target_slot < 0 || advancement_slot < 0) {
        McfStrRef_Release(advancement_ref);
        return -1;
    }

    ret = advancement_until_unsafe(action, target_ref, advancement_ref);
    McfStrRef_Release(advancement_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
