#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"

typedef enum {
    BOSSBAR_COLOR_BLUE,
    BOSSBAR_COLOR_GREEN,
    BOSSBAR_COLOR_PINK,
    BOSSBAR_COLOR_PURPLE,
    BOSSBAR_COLOR_RED,
    BOSSBAR_COLOR_WHITE,
    BOSSBAR_COLOR_YELLOW
} BossbarColor;

typedef enum {
    BOSSBAR_STYLE_NOTCHED_6,
    BOSSBAR_STYLE_NOTCHED_10,
    BOSSBAR_STYLE_NOTCHED_12,
    BOSSBAR_STYLE_NOTCHED_20,
    BOSSBAR_STYLE_PROGRESS
} BossbarStyle;

typedef enum {
    BOSSBAR_QUERY_MAX,
    BOSSBAR_QUERY_PLAYERS,
    BOSSBAR_QUERY_VALUE,
    BOSSBAR_QUERY_VISIBLE
} BossbarQuery;

#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_bossbar_add:\n"
"    inline $execute store result score r0 vm_regs run bossbar add $(id) $(name)\n"
"    ret\n"
"\n"
"export _ll_shared:z/bossbar_get_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run bossbar get $(id) max\n"
"    ret\n"
"\n"
"export _ll_shared:z/bossbar_get_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run bossbar get $(id) players\n"
"    ret\n"
"\n"
"export _ll_shared:z/bossbar_get_unsafe_exec_2:\n"
"    inline $execute store result score r0 vm_regs run bossbar get $(id) value\n"
"    ret\n"
"\n"
"export _ll_shared:z/bossbar_get_unsafe_exec_3:\n"
"    inline $execute store result score r0 vm_regs run bossbar get $(id) visible\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_bossbar_list:\n"
"    inline execute store result score r0 vm_regs run bossbar list\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_bossbar_remove:\n"
"    inline $execute store result score r0 vm_regs run bossbar remove $(id)\n"
"    ret\n"
"\n"
"export _ll_shared:z/bossbar_set_color_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run bossbar set $(id) color blue\n"
"    ret\n"
"\n"
"export _ll_shared:z/bossbar_set_color_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run bossbar set $(id) color green\n"
"    ret\n"
"\n"
"export _ll_shared:z/bossbar_set_color_unsafe_exec_2:\n"
"    inline $execute store result score r0 vm_regs run bossbar set $(id) color pink\n"
"    ret\n"
"\n"
"export _ll_shared:z/bossbar_set_color_unsafe_exec_3:\n"
"    inline $execute store result score r0 vm_regs run bossbar set $(id) color purple\n"
"    ret\n"
"\n"
"export _ll_shared:z/bossbar_set_color_unsafe_exec_4:\n"
"    inline $execute store result score r0 vm_regs run bossbar set $(id) color red\n"
"    ret\n"
"\n"
"export _ll_shared:z/bossbar_set_color_unsafe_exec_5:\n"
"    inline $execute store result score r0 vm_regs run bossbar set $(id) color white\n"
"    ret\n"
"\n"
"export _ll_shared:z/bossbar_set_color_unsafe_exec_6:\n"
"    inline $execute store result score r0 vm_regs run bossbar set $(id) color yellow\n"
"    ret\n"
"\n"
"export _ll_shared:z/bossbar_set_style_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run bossbar set $(id) style notched_6\n"
"    ret\n"
"\n"
"export _ll_shared:z/bossbar_set_style_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run bossbar set $(id) style notched_10\n"
"    ret\n"
"\n"
"export _ll_shared:z/bossbar_set_style_unsafe_exec_2:\n"
"    inline $execute store result score r0 vm_regs run bossbar set $(id) style notched_12\n"
"    ret\n"
"\n"
"export _ll_shared:z/bossbar_set_style_unsafe_exec_3:\n"
"    inline $execute store result score r0 vm_regs run bossbar set $(id) style notched_20\n"
"    ret\n"
"\n"
"export _ll_shared:z/bossbar_set_style_unsafe_exec_4:\n"
"    inline $execute store result score r0 vm_regs run bossbar set $(id) style progress\n"
"    ret\n"
"\n"
"export _ll_shared:z/bossbar_set_visible_unsafe_exec_true:\n"
"    inline $execute store result score r0 vm_regs run bossbar set $(id) visible true\n"
"    ret\n"
"\n"
"export _ll_shared:z/bossbar_set_visible_unsafe_exec_false:\n"
"    inline $execute store result score r0 vm_regs run bossbar set $(id) visible false\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_bossbar_set_name:\n"
"    inline $execute store result score r0 vm_regs run bossbar set $(id) name $(name)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_bossbar_set_players_all:\n"
"    inline $execute store result score r0 vm_regs run bossbar set $(id) players\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_bossbar_set_players:\n"
"    inline $execute store result score r0 vm_regs run bossbar set $(id) players $(targets)\n"
"    ret\n"
);

static inline int
bossbar_add_unsafe(McfStrRef id_ref, McfStrRef name_ref)
{
    int ret;
    int id_slot;
    int name_slot;

    id_slot = McfStrRef_SlotId(id_ref);
    name_slot = McfStrRef_SlotId(name_ref);
    if (id_slot < 0 || name_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{id: \"\", name: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.id set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.name set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_bossbar_add with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(id_slot), "r"(name_slot)
    );
    return ret;
}

static inline int
bossbar_add(const Identifier * id, TextComponent name)
{
    int ret;
    McfStrRef id_ref;
    McfStrRef name_ref;
    int id_slot;
    int name_slot;

    id_ref = _Command_RequireIdentifierRef(id);
    name_ref = _Command_RequireTextComponentRef(name);
    id_slot = McfStrRef_SlotId(id_ref);
    name_slot = McfStrRef_SlotId(name_ref);
    if (id_slot < 0 || name_slot < 0) {
        McfStrRef_Release(id_ref);
        McfStrRef_Release(name_ref);
        return -1;
    }

    ret = bossbar_add_unsafe(id_ref, name_ref);
    McfStrRef_Release(id_ref);
    McfStrRef_Release(name_ref);
    return ret;
}

static inline int
bossbar_get_unsafe(McfStrRef id_ref, BossbarQuery query)
{
    int ret;
    int id_slot;

    id_slot = McfStrRef_SlotId(id_ref);
    if (id_slot < 0) {
        return -1;
    }

    switch (query) {
        case BOSSBAR_QUERY_MAX:
            __asm volatile (
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(id_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/bossbar_get_unsafe_exec_0 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case BOSSBAR_QUERY_PLAYERS:
            __asm volatile (
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(id_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/bossbar_get_unsafe_exec_1 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case BOSSBAR_QUERY_VALUE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(id_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/bossbar_get_unsafe_exec_2 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case BOSSBAR_QUERY_VISIBLE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(id_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/bossbar_get_unsafe_exec_3 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
bossbar_get(const Identifier * id, BossbarQuery query)
{
    int ret;
    McfStrRef id_ref;
    int id_slot;

    id_ref = _Command_RequireIdentifierRef(id);
    id_slot = McfStrRef_SlotId(id_ref);
    if (id_slot < 0) {
        McfStrRef_Release(id_ref);
        return -1;
    }

    ret = bossbar_get_unsafe(id_ref, query);
    McfStrRef_Release(id_ref);
    return ret;
}

static inline int
bossbar_list(void)
{
    int ret;

    __asm volatile (
        "inline function _ll_shared:z/libmc_cmd_bossbar_list\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
    );
    return ret;
}

static inline int
bossbar_remove_unsafe(McfStrRef id_ref)
{
    int ret;
    int id_slot;

    id_slot = McfStrRef_SlotId(id_ref);
    if (id_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{id: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.id set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_bossbar_remove with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(id_slot)
    );
    return ret;
}

static inline int
bossbar_remove(const Identifier * id)
{
    int ret;
    McfStrRef id_ref;
    int id_slot;

    id_ref = _Command_RequireIdentifierRef(id);
    id_slot = McfStrRef_SlotId(id_ref);
    if (id_slot < 0) {
        McfStrRef_Release(id_ref);
        return -1;
    }

    ret = bossbar_remove_unsafe(id_ref);
    McfStrRef_Release(id_ref);
    return ret;
}

static inline int
bossbar_set_color_unsafe(McfStrRef id_ref, BossbarColor color)
{
    int ret;
    int id_slot;

    id_slot = McfStrRef_SlotId(id_ref);
    if (id_slot < 0) {
        return -1;
    }

    switch (color) {
        case BOSSBAR_COLOR_BLUE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(id_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/bossbar_set_color_unsafe_exec_0 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case BOSSBAR_COLOR_GREEN:
            __asm volatile (
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(id_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/bossbar_set_color_unsafe_exec_1 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case BOSSBAR_COLOR_PINK:
            __asm volatile (
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(id_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/bossbar_set_color_unsafe_exec_2 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case BOSSBAR_COLOR_PURPLE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(id_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/bossbar_set_color_unsafe_exec_3 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case BOSSBAR_COLOR_RED:
            __asm volatile (
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(id_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/bossbar_set_color_unsafe_exec_4 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case BOSSBAR_COLOR_WHITE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(id_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/bossbar_set_color_unsafe_exec_5 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case BOSSBAR_COLOR_YELLOW:
            __asm volatile (
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(id_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/bossbar_set_color_unsafe_exec_6 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
bossbar_set_color(const Identifier * id, BossbarColor color)
{
    int ret;
    McfStrRef id_ref;
    int id_slot;

    id_ref = _Command_RequireIdentifierRef(id);
    id_slot = McfStrRef_SlotId(id_ref);
    if (id_slot < 0) {
        McfStrRef_Release(id_ref);
        return -1;
    }

    ret = bossbar_set_color_unsafe(id_ref, color);
    McfStrRef_Release(id_ref);
    return ret;
}

static inline int
bossbar_set_style_unsafe(McfStrRef id_ref, BossbarStyle style)
{
    int ret;
    int id_slot;

    id_slot = McfStrRef_SlotId(id_ref);
    if (id_slot < 0) {
        return -1;
    }

    switch (style) {
        case BOSSBAR_STYLE_NOTCHED_6:
            __asm volatile (
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(id_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/bossbar_set_style_unsafe_exec_0 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case BOSSBAR_STYLE_NOTCHED_10:
            __asm volatile (
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(id_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/bossbar_set_style_unsafe_exec_1 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case BOSSBAR_STYLE_NOTCHED_12:
            __asm volatile (
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(id_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/bossbar_set_style_unsafe_exec_2 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case BOSSBAR_STYLE_NOTCHED_20:
            __asm volatile (
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(id_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/bossbar_set_style_unsafe_exec_3 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case BOSSBAR_STYLE_PROGRESS:
            __asm volatile (
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(id_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/bossbar_set_style_unsafe_exec_4 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
bossbar_set_style(const Identifier * id, BossbarStyle style)
{
    int ret;
    McfStrRef id_ref;
    int id_slot;

    id_ref = _Command_RequireIdentifierRef(id);
    id_slot = McfStrRef_SlotId(id_ref);
    if (id_slot < 0) {
        McfStrRef_Release(id_ref);
        return -1;
    }

    ret = bossbar_set_style_unsafe(id_ref, style);
    McfStrRef_Release(id_ref);
    return ret;
}

static inline int
bossbar_set_max_unsafe(McfStrRef id_ref, int value)
{
    int ret;
    int id_slot;

    id_slot = McfStrRef_SlotId(id_ref);
    if (id_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
        :
        : "r"(id_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run bossbar set $(id) max %1"
        : "=r"(ret)
        : "r"(value)
    );
    return ret;
}

static inline int
bossbar_set_max(const Identifier * id, int value)
{
    int ret;
    McfStrRef id_ref;
    int id_slot;

    id_ref = _Command_RequireIdentifierRef(id);
    id_slot = McfStrRef_SlotId(id_ref);
    if (id_slot < 0) {
        McfStrRef_Release(id_ref);
        return -1;
    }

    ret = bossbar_set_max_unsafe(id_ref, value);
    McfStrRef_Release(id_ref);
    return ret;
}

static inline int
bossbar_set_value_unsafe(McfStrRef id_ref, int value)
{
    int ret;
    int id_slot;

    id_slot = McfStrRef_SlotId(id_ref);
    if (id_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
        :
        : "r"(id_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run bossbar set $(id) value %1"
        : "=r"(ret)
        : "r"(value)
    );
    return ret;
}

static inline int
bossbar_set_value(const Identifier * id, int value)
{
    int ret;
    McfStrRef id_ref;
    int id_slot;

    id_ref = _Command_RequireIdentifierRef(id);
    id_slot = McfStrRef_SlotId(id_ref);
    if (id_slot < 0) {
        McfStrRef_Release(id_ref);
        return -1;
    }

    ret = bossbar_set_value_unsafe(id_ref, value);
    McfStrRef_Release(id_ref);
    return ret;
}

static inline int
bossbar_set_visible_unsafe(McfStrRef id_ref, int visible)
{
    int ret;
    int id_slot;

    id_slot = McfStrRef_SlotId(id_ref);
    if (id_slot < 0) {
        return -1;
    }

    if (visible) {
        __asm volatile (
            "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
            :
            : "r"(id_slot)
        );
        __asm volatile (
            "inline function _ll_shared:z/bossbar_set_visible_unsafe_exec_true with storage std:vm ls0\n"
            "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
            : "=r"(ret)
        );
        return ret;
    } else {
        __asm volatile (
            "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%0].value"
            :
            : "r"(id_slot)
        );
        __asm volatile (
            "inline function _ll_shared:z/bossbar_set_visible_unsafe_exec_false with storage std:vm ls0\n"
            "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
            : "=r"(ret)
        );
        return ret;
    }
}

static inline int
bossbar_set_visible(const Identifier * id, int visible)
{
    int ret;
    McfStrRef id_ref;
    int id_slot;

    id_ref = _Command_RequireIdentifierRef(id);
    id_slot = McfStrRef_SlotId(id_ref);
    if (id_slot < 0) {
        McfStrRef_Release(id_ref);
        return -1;
    }

    ret = bossbar_set_visible_unsafe(id_ref, visible);
    McfStrRef_Release(id_ref);
    return ret;
}

static inline int
bossbar_set_name_unsafe(McfStrRef id_ref, McfStrRef name_ref)
{
    int ret;
    int id_slot;
    int name_slot;

    id_slot = McfStrRef_SlotId(id_ref);
    name_slot = McfStrRef_SlotId(name_ref);
    if (id_slot < 0 || name_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{id: \"\", name: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.id set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.name set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_bossbar_set_name with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(id_slot), "r"(name_slot)
    );
    return ret;
}

static inline int
bossbar_set_name(const Identifier * id, TextComponent name)
{
    int ret;
    McfStrRef id_ref;
    McfStrRef name_ref;
    int id_slot;
    int name_slot;

    id_ref = _Command_RequireIdentifierRef(id);
    name_ref = _Command_RequireTextComponentRef(name);
    id_slot = McfStrRef_SlotId(id_ref);
    name_slot = McfStrRef_SlotId(name_ref);
    if (id_slot < 0 || name_slot < 0) {
        McfStrRef_Release(id_ref);
        McfStrRef_Release(name_ref);
        return -1;
    }

    ret = bossbar_set_name_unsafe(id_ref, name_ref);
    McfStrRef_Release(id_ref);
    McfStrRef_Release(name_ref);
    return ret;
}

static inline int
bossbar_set_players_all_unsafe(McfStrRef id_ref)
{
    int ret;
    int id_slot;

    id_slot = McfStrRef_SlotId(id_ref);
    if (id_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{id: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.id set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_bossbar_set_players_all with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(id_slot)
    );
    return ret;
}

static inline int
bossbar_set_players_all(const Identifier * id)
{
    int ret;
    McfStrRef id_ref;
    int id_slot;

    id_ref = _Command_RequireIdentifierRef(id);
    id_slot = McfStrRef_SlotId(id_ref);
    if (id_slot < 0) {
        McfStrRef_Release(id_ref);
        return -1;
    }

    ret = bossbar_set_players_all_unsafe(id_ref);
    McfStrRef_Release(id_ref);
    return ret;
}

static inline int
bossbar_set_players_unsafe(McfStrRef id_ref, McfStrRef targets_ref)
{
    int ret;
    int id_slot;
    int targets_slot;

    id_slot = McfStrRef_SlotId(id_ref);
    targets_slot = McfStrRef_SlotId(targets_ref);
    if (id_slot < 0 || targets_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{id: \"\", targets: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.id set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.targets set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_bossbar_set_players with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(id_slot), "r"(targets_slot)
    );
    return ret;
}

static inline int
bossbar_set_players(const Identifier * id, Target targets)
{
    int ret;
    McfStrRef id_ref;
    McfStrRef targets_ref;
    int id_slot;
    int targets_slot;

    id_ref = _Command_RequireIdentifierRef(id);
    targets_ref = _Command_RequireTargetRef(targets);
    id_slot = McfStrRef_SlotId(id_ref);
    targets_slot = McfStrRef_SlotId(targets_ref);
    if (id_slot < 0 || targets_slot < 0) {
        McfStrRef_Release(id_ref);
        return -1;
    }

    ret = bossbar_set_players_unsafe(id_ref, targets_ref);
    McfStrRef_Release(id_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
