#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"

typedef enum {
    CLONE_MASK_REPLACE,
    CLONE_MASK_MASKED
} CloneMaskMode;

#ifdef __cplusplus
extern "C" {
#endif

static inline int
clone(Vec3i begin, Vec3i end, Vec3i destination)
{
    int ret;

    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run clone %1 %2 %3 %4 %5 %6 %7 %8 %9"
        : "=r"(ret)
        : "r"(begin.x), "r"(begin.y), "r"(begin.z), "r"(end.x), "r"(end.y), "r"(end.z), "r"(destination.x), "r"(destination.y), "r"(destination.z)
    );
    return ret;
}

static inline int
clone_mode(Vec3i begin, Vec3i end, Vec3i destination, CloneMaskMode mode)
{
    int ret;

    switch (mode) {
        case CLONE_MASK_REPLACE:
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run clone %1 %2 %3 %4 %5 %6 %7 %8 %9 replace"
                : "=r"(ret)
                : "r"(begin.x), "r"(begin.y), "r"(begin.z), "r"(end.x), "r"(end.y), "r"(end.z), "r"(destination.x), "r"(destination.y), "r"(destination.z)
            );
            return ret;
        case CLONE_MASK_MASKED:
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run clone %1 %2 %3 %4 %5 %6 %7 %8 %9 masked"
                : "=r"(ret)
                : "r"(begin.x), "r"(begin.y), "r"(begin.z), "r"(end.x), "r"(end.y), "r"(end.z), "r"(destination.x), "r"(destination.y), "r"(destination.z)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
clone_filtered_unsafe(int begin_x, int begin_y, int begin_z, int end_x, int end_y, int end_z, int dest_x, int dest_y, int dest_z, McfStrRef filter_ref)
{
    int ret;
    int filter_slot;

    filter_slot = McfStrRef_SlotId(filter_ref);
    if (filter_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.filter set from storage std:vm mcstr.slots[%0].value"
        :
        : "r"(filter_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run clone %1 %2 %3 %4 %5 %6 %7 %8 %9 filtered $(filter)"
        : "=r"(ret)
        : "r"(begin_x), "r"(begin_y), "r"(begin_z), "r"(end_x), "r"(end_y), "r"(end_z), "r"(dest_x), "r"(dest_y), "r"(dest_z)
    );
    return ret;
}

static inline int
clone_filtered(Vec3i begin, Vec3i end, Vec3i destination, Block filter)
{
    McfStrRef filter_ref;
    int filter_slot;

    filter_ref = Block_EnsureMcfName(filter);
    filter_slot = McfStrRef_SlotId(filter_ref);
    if (filter_slot < 0) {
        return -1;
    }
    return clone_filtered_unsafe(begin.x, begin.y, begin.z, end.x, end.y, end.z, destination.x, destination.y, destination.z, filter_ref);
}

#ifdef __cplusplus
}
#endif
