#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_damage:\n"
"    inline $execute store result score r0 vm_regs run damage $(target) $(amount)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_damage_type:\n"
"    inline $execute store result score r0 vm_regs run damage $(target) $(amount) $(damage_type)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_damage_at:\n"
"    inline $execute store result score r0 vm_regs run damage $(target) $(amount) $(damage_type) at $(loc_x) $(loc_y) $(loc_z)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_damage_by:\n"
"    inline $execute store result score r0 vm_regs run damage $(target) $(amount) $(damage_type) by $(entity)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_damage_by_from:\n"
"    inline $execute store result score r0 vm_regs run damage $(target) $(amount) $(damage_type) by $(entity) from $(cause)\n"
"    ret\n"
);

static inline int
damage_unsafe(McfStrRef target_ref, McfStrRef amount_ref)
{
    int ret;
    int target_slot;
    int amount_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    amount_slot = McfStrRef_SlotId(amount_ref);
    if (target_slot < 0 || amount_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", amount: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.amount set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_damage with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(amount_slot)
    );
    return ret;
}

static inline int
damage(Target target, float amount)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef amount_ref;
    int target_slot;
    int amount_slot;

    target_ref = _Command_RequireTargetRef(target);
    amount_ref = _Command_FormatFloatRef(amount);
    target_slot = McfStrRef_SlotId(target_ref);
    amount_slot = McfStrRef_SlotId(amount_ref);
    if (target_slot < 0 || amount_slot < 0) {
        McfStrRef_Release(amount_ref);
        return -1;
    }

    ret = damage_unsafe(target_ref, amount_ref);
    McfStrRef_Release(amount_ref);
    return ret;
}

static inline int
damage_type_unsafe(McfStrRef target_ref, McfStrRef amount_ref, McfStrRef damage_type_ref)
{
    int ret;
    int target_slot;
    int amount_slot;
    int damage_type_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    amount_slot = McfStrRef_SlotId(amount_ref);
    damage_type_slot = McfStrRef_SlotId(damage_type_ref);
    if (target_slot < 0 || amount_slot < 0 || damage_type_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", amount: \"\", damage_type: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.amount set from storage std:vm mcstr.slots[%2].value\n"
        "inline $data modify storage std:vm s6.cmd.damage_type set from storage std:vm mcstr.slots[%3].value\n"
        "inline function _ll_shared:z/libmc_cmd_damage_type with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(amount_slot), "r"(damage_type_slot)
    );
    return ret;
}

static inline int
damage_type(Target target, float amount, const Identifier * damage_type)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef amount_ref;
    McfStrRef damage_type_ref;
    int target_slot;
    int amount_slot;
    int damage_type_slot;

    target_ref = _Command_RequireTargetRef(target);
    amount_ref = _Command_FormatFloatRef(amount);
    damage_type_ref = _Command_RequireIdentifierRef(damage_type);
    target_slot = McfStrRef_SlotId(target_ref);
    amount_slot = McfStrRef_SlotId(amount_ref);
    damage_type_slot = McfStrRef_SlotId(damage_type_ref);
    if (target_slot < 0 || amount_slot < 0 || damage_type_slot < 0) {
        McfStrRef_Release(amount_ref);
        McfStrRef_Release(damage_type_ref);
        return -1;
    }

    ret = damage_type_unsafe(target_ref, amount_ref, damage_type_ref);
    McfStrRef_Release(amount_ref);
    McfStrRef_Release(damage_type_ref);
    return ret;
}

static inline int
damage_at_unsafe(McfStrRef target_ref, McfStrRef amount_ref, McfStrRef damage_type_ref, McfStrRef loc_x_ref, McfStrRef loc_y_ref, McfStrRef loc_z_ref)
{
    int ret;
    int target_slot;
    int amount_slot;
    int damage_type_slot;
    int loc_x_slot;
    int loc_y_slot;
    int loc_z_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    amount_slot = McfStrRef_SlotId(amount_ref);
    damage_type_slot = McfStrRef_SlotId(damage_type_ref);
    loc_x_slot = McfStrRef_SlotId(loc_x_ref);
    loc_y_slot = McfStrRef_SlotId(loc_y_ref);
    loc_z_slot = McfStrRef_SlotId(loc_z_ref);
    if (target_slot < 0 || amount_slot < 0 || damage_type_slot < 0 || loc_x_slot < 0 || loc_y_slot < 0 || loc_z_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", amount: \"\", damage_type: \"\", loc_x: \"\", loc_y: \"\", loc_z: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.amount set from storage std:vm mcstr.slots[%2].value\n"
        "inline $data modify storage std:vm s6.cmd.damage_type set from storage std:vm mcstr.slots[%3].value\n"
        "inline $data modify storage std:vm s6.cmd.loc_x set from storage std:vm mcstr.slots[%4].value\n"
        "inline $data modify storage std:vm s6.cmd.loc_y set from storage std:vm mcstr.slots[%5].value\n"
        "inline $data modify storage std:vm s6.cmd.loc_z set from storage std:vm mcstr.slots[%6].value\n"
        "inline function _ll_shared:z/libmc_cmd_damage_at with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(amount_slot), "r"(damage_type_slot), "r"(loc_x_slot), "r"(loc_y_slot), "r"(loc_z_slot)
    );
    return ret;
}

static inline int
damage_at(Target target, float amount, const Identifier * damage_type, Vec3d location)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef amount_ref;
    McfStrRef damage_type_ref;
    McfStrRef loc_x_ref;
    McfStrRef loc_y_ref;
    McfStrRef loc_z_ref;
    int target_slot;
    int amount_slot;
    int damage_type_slot;
    int loc_x_slot;
    int loc_y_slot;
    int loc_z_slot;

    target_ref = _Command_RequireTargetRef(target);
    amount_ref = _Command_FormatFloatRef(amount);
    damage_type_ref = _Command_RequireIdentifierRef(damage_type);
    loc_x_ref = _Command_FormatDoubleRef(location.x);
    loc_y_ref = _Command_FormatDoubleRef(location.y);
    loc_z_ref = _Command_FormatDoubleRef(location.z);
    target_slot = McfStrRef_SlotId(target_ref);
    amount_slot = McfStrRef_SlotId(amount_ref);
    damage_type_slot = McfStrRef_SlotId(damage_type_ref);
    loc_x_slot = McfStrRef_SlotId(loc_x_ref);
    loc_y_slot = McfStrRef_SlotId(loc_y_ref);
    loc_z_slot = McfStrRef_SlotId(loc_z_ref);
    if (target_slot < 0 || amount_slot < 0 || damage_type_slot < 0 || loc_x_slot < 0 || loc_y_slot < 0 || loc_z_slot < 0) {
        McfStrRef_Release(amount_ref);
        McfStrRef_Release(damage_type_ref);
        McfStrRef_Release(loc_x_ref);
        McfStrRef_Release(loc_y_ref);
        McfStrRef_Release(loc_z_ref);
        return -1;
    }

    ret = damage_at_unsafe(target_ref, amount_ref, damage_type_ref, loc_x_ref, loc_y_ref, loc_z_ref);
    McfStrRef_Release(amount_ref);
    McfStrRef_Release(damage_type_ref);
    McfStrRef_Release(loc_x_ref);
    McfStrRef_Release(loc_y_ref);
    McfStrRef_Release(loc_z_ref);
    return ret;
}

static inline int
damage_by_unsafe(McfStrRef target_ref, McfStrRef amount_ref, McfStrRef damage_type_ref, McfStrRef entity_ref)
{
    int ret;
    int target_slot;
    int amount_slot;
    int damage_type_slot;
    int entity_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    amount_slot = McfStrRef_SlotId(amount_ref);
    damage_type_slot = McfStrRef_SlotId(damage_type_ref);
    entity_slot = McfStrRef_SlotId(entity_ref);
    if (target_slot < 0 || amount_slot < 0 || damage_type_slot < 0 || entity_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", amount: \"\", damage_type: \"\", entity: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.amount set from storage std:vm mcstr.slots[%2].value\n"
        "inline $data modify storage std:vm s6.cmd.damage_type set from storage std:vm mcstr.slots[%3].value\n"
        "inline $data modify storage std:vm s6.cmd.entity set from storage std:vm mcstr.slots[%4].value\n"
        "inline function _ll_shared:z/libmc_cmd_damage_by with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(amount_slot), "r"(damage_type_slot), "r"(entity_slot)
    );
    return ret;
}

static inline int
damage_by(Target target, float amount, const Identifier * damage_type, Target entity)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef amount_ref;
    McfStrRef damage_type_ref;
    McfStrRef entity_ref;
    int target_slot;
    int amount_slot;
    int damage_type_slot;
    int entity_slot;

    target_ref = _Command_RequireTargetRef(target);
    amount_ref = _Command_FormatFloatRef(amount);
    damage_type_ref = _Command_RequireIdentifierRef(damage_type);
    entity_ref = _Command_RequireTargetRef(entity);
    target_slot = McfStrRef_SlotId(target_ref);
    amount_slot = McfStrRef_SlotId(amount_ref);
    damage_type_slot = McfStrRef_SlotId(damage_type_ref);
    entity_slot = McfStrRef_SlotId(entity_ref);
    if (target_slot < 0 || amount_slot < 0 || damage_type_slot < 0 || entity_slot < 0) {
        McfStrRef_Release(amount_ref);
        McfStrRef_Release(damage_type_ref);
        return -1;
    }

    ret = damage_by_unsafe(target_ref, amount_ref, damage_type_ref, entity_ref);
    McfStrRef_Release(amount_ref);
    McfStrRef_Release(damage_type_ref);
    return ret;
}

static inline int
damage_by_from_unsafe(McfStrRef target_ref, McfStrRef amount_ref, McfStrRef damage_type_ref, McfStrRef entity_ref, McfStrRef cause_ref)
{
    int ret;
    int target_slot;
    int amount_slot;
    int damage_type_slot;
    int entity_slot;
    int cause_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    amount_slot = McfStrRef_SlotId(amount_ref);
    damage_type_slot = McfStrRef_SlotId(damage_type_ref);
    entity_slot = McfStrRef_SlotId(entity_ref);
    cause_slot = McfStrRef_SlotId(cause_ref);
    if (target_slot < 0 || amount_slot < 0 || damage_type_slot < 0 || entity_slot < 0 || cause_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", amount: \"\", damage_type: \"\", entity: \"\", cause: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.amount set from storage std:vm mcstr.slots[%2].value\n"
        "inline $data modify storage std:vm s6.cmd.damage_type set from storage std:vm mcstr.slots[%3].value\n"
        "inline $data modify storage std:vm s6.cmd.entity set from storage std:vm mcstr.slots[%4].value\n"
        "inline $data modify storage std:vm s6.cmd.cause set from storage std:vm mcstr.slots[%5].value\n"
        "inline function _ll_shared:z/libmc_cmd_damage_by_from with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(amount_slot), "r"(damage_type_slot), "r"(entity_slot), "r"(cause_slot)
    );
    return ret;
}

static inline int
damage_by_from(Target target, float amount, const Identifier * damage_type, Target entity, Target cause)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef amount_ref;
    McfStrRef damage_type_ref;
    McfStrRef entity_ref;
    McfStrRef cause_ref;
    int target_slot;
    int amount_slot;
    int damage_type_slot;
    int entity_slot;
    int cause_slot;

    target_ref = _Command_RequireTargetRef(target);
    amount_ref = _Command_FormatFloatRef(amount);
    damage_type_ref = _Command_RequireIdentifierRef(damage_type);
    entity_ref = _Command_RequireTargetRef(entity);
    cause_ref = _Command_RequireTargetRef(cause);
    target_slot = McfStrRef_SlotId(target_ref);
    amount_slot = McfStrRef_SlotId(amount_ref);
    damage_type_slot = McfStrRef_SlotId(damage_type_ref);
    entity_slot = McfStrRef_SlotId(entity_ref);
    cause_slot = McfStrRef_SlotId(cause_ref);
    if (target_slot < 0 || amount_slot < 0 || damage_type_slot < 0 || entity_slot < 0 || cause_slot < 0) {
        McfStrRef_Release(amount_ref);
        McfStrRef_Release(damage_type_ref);
        return -1;
    }

    ret = damage_by_from_unsafe(target_ref, amount_ref, damage_type_ref, entity_ref, cause_ref);
    McfStrRef_Release(amount_ref);
    McfStrRef_Release(damage_type_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
