#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
datapack_enable_unsafe(McfStrRef name_ref)
{
    int ret;
    int name_slot;

    name_slot = McfStrRef_SlotId(name_ref);
    if (name_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{name: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.name set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_datapack_enable with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(name_slot)
    );
    return ret;
}

static inline int
datapack_enable(String name)
{
    McfStrRef name_ref;
    int name_slot;

    name_ref = _Command_RequireStringRef(name);
    name_slot = McfStrRef_SlotId(name_ref);
    if (name_slot < 0) {
        return -1;
    }
    return datapack_enable_unsafe(name_ref);
}

static inline int
datapack_disable_unsafe(McfStrRef name_ref)
{
    int ret;
    int name_slot;

    name_slot = McfStrRef_SlotId(name_ref);
    if (name_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{name: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.name set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_datapack_disable with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(name_slot)
    );
    return ret;
}

static inline int
datapack_disable(String name)
{
    McfStrRef name_ref;
    int name_slot;

    name_ref = _Command_RequireStringRef(name);
    name_slot = McfStrRef_SlotId(name_ref);
    if (name_slot < 0) {
        return -1;
    }
    return datapack_disable_unsafe(name_ref);
}

static inline int
datapack_list(void)
{
    int ret;

    __asm volatile (
        "inline function _ll_shared:z/libmc_cmd_datapack_list\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
    );
    return ret;
}

#ifdef __cplusplus
}
#endif
