#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"

typedef enum {
    FILL_DESTROY,
    FILL_HOLLOW,
    FILL_KEEP,
    FILL_OUTLINE,
    FILL_REPLACE
} FillMode;

#ifdef __cplusplus
extern "C" {
#endif

static inline int
fill_unsafe(int from_x, int from_y, int from_z, int to_x, int to_y, int to_z, McfStrRef block_ref, FillMode mode)
{
    int ret;
    int block_slot;

    block_slot = McfStrRef_SlotId(block_ref);
    if (block_slot < 0) {
        return -1;
    }

    switch (mode) {
        case FILL_DESTROY:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(block_slot)
            );
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run fill %1 %2 %3 %4 %5 %6 $(block) destroy"
                : "=r"(ret)
                : "r"(from_x), "r"(from_y), "r"(from_z), "r"(to_x), "r"(to_y), "r"(to_z)
            );
            return ret;
        case FILL_HOLLOW:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(block_slot)
            );
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run fill %1 %2 %3 %4 %5 %6 $(block) hollow"
                : "=r"(ret)
                : "r"(from_x), "r"(from_y), "r"(from_z), "r"(to_x), "r"(to_y), "r"(to_z)
            );
            return ret;
        case FILL_KEEP:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(block_slot)
            );
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run fill %1 %2 %3 %4 %5 %6 $(block) keep"
                : "=r"(ret)
                : "r"(from_x), "r"(from_y), "r"(from_z), "r"(to_x), "r"(to_y), "r"(to_z)
            );
            return ret;
        case FILL_OUTLINE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(block_slot)
            );
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run fill %1 %2 %3 %4 %5 %6 $(block) outline"
                : "=r"(ret)
                : "r"(from_x), "r"(from_y), "r"(from_z), "r"(to_x), "r"(to_y), "r"(to_z)
            );
            return ret;
        case FILL_REPLACE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(block_slot)
            );
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run fill %1 %2 %3 %4 %5 %6 $(block)"
                : "=r"(ret)
                : "r"(from_x), "r"(from_y), "r"(from_z), "r"(to_x), "r"(to_y), "r"(to_z)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
fill(Vec3i from, Vec3i to, Block block, FillMode mode)
{
    McfStrRef block_ref;
    int block_slot;

    block_ref = Block_EnsureMcfName(block);
    block_slot = McfStrRef_SlotId(block_ref);
    if (block_slot < 0) {
        return -1;
    }
    return fill_unsafe(from.x, from.y, from.z, to.x, to.y, to.z, block_ref, mode);
}

#ifdef __cplusplus
}
#endif
