#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
function_call_unsafe(McfStrRef name_ref)
{
    int ret;
    int name_slot;

    name_slot = McfStrRef_SlotId(name_ref);
    if (name_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{name: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.name set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_function_call with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(name_slot)
    );
    return ret;
}

static inline int
function_call(const Identifier * name)
{
    int ret;
    McfStrRef name_ref;
    int name_slot;

    name_ref = _Command_RequireIdentifierRef(name);
    name_slot = McfStrRef_SlotId(name_ref);
    if (name_slot < 0) {
        McfStrRef_Release(name_ref);
        return -1;
    }

    ret = function_call_unsafe(name_ref);
    McfStrRef_Release(name_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
