#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"

typedef enum {
    GAMEMODE_SURVIVAL,
    GAMEMODE_CREATIVE,
    GAMEMODE_ADVENTURE,
    GAMEMODE_SPECTATOR
} GameMode;

#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/gamemode_target_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run gamemode survival $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/gamemode_target_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run gamemode creative $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/gamemode_target_unsafe_exec_2:\n"
"    inline $execute store result score r0 vm_regs run gamemode adventure $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/gamemode_target_unsafe_exec_3:\n"
"    inline $execute store result score r0 vm_regs run gamemode spectator $(target)\n"
"    ret\n"
);

static inline int
gamemode(GameMode mode)
{
    int ret;

    switch (mode) {
        case GAMEMODE_SURVIVAL:
            __asm volatile (
                "inline execute store result score %0 vm_regs run gamemode survival"
                : "=r"(ret)
            );
            return ret;
        case GAMEMODE_CREATIVE:
            __asm volatile (
                "inline execute store result score %0 vm_regs run gamemode creative"
                : "=r"(ret)
            );
            return ret;
        case GAMEMODE_ADVENTURE:
            __asm volatile (
                "inline execute store result score %0 vm_regs run gamemode adventure"
                : "=r"(ret)
            );
            return ret;
        case GAMEMODE_SPECTATOR:
            __asm volatile (
                "inline execute store result score %0 vm_regs run gamemode spectator"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
gamemode_target_unsafe(GameMode mode, McfStrRef target_ref)
{
    int ret;
    int target_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }

    switch (mode) {
        case GAMEMODE_SURVIVAL:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/gamemode_target_unsafe_exec_0 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case GAMEMODE_CREATIVE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/gamemode_target_unsafe_exec_1 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case GAMEMODE_ADVENTURE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/gamemode_target_unsafe_exec_2 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case GAMEMODE_SPECTATOR:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/gamemode_target_unsafe_exec_3 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
gamemode_target(GameMode mode, Target target)
{
    McfStrRef target_ref;
    int target_slot;

    target_ref = _Command_RequireTargetRef(target);
    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }
    return gamemode_target_unsafe(mode, target_ref);
}

#ifdef __cplusplus
}
#endif
