#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
help(void)
{
    int ret;

    __asm volatile (
        "inline function _ll_shared:z/libmc_cmd_help\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
    );
    return ret;
}

static inline int
help_command_unsafe(McfStrRef command_ref)
{
    int ret;
    int command_slot;

    command_slot = McfStrRef_SlotId(command_ref);
    if (command_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{command: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.command set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_help_command with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(command_slot)
    );
    return ret;
}

static inline int
help_command(String command)
{
    McfStrRef command_ref;
    int command_slot;

    command_ref = _Command_RequireStringRef(command);
    command_slot = McfStrRef_SlotId(command_ref);
    if (command_slot < 0) {
        return -1;
    }
    return help_command_unsafe(command_ref);
}

#ifdef __cplusplus
}
#endif
