#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
locate_structure_unsafe(McfStrRef structure_ref)
{
    int ret;
    int structure_slot;

    structure_slot = McfStrRef_SlotId(structure_ref);
    if (structure_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{structure: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.structure set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_locate_structure with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(structure_slot)
    );
    return ret;
}

static inline int
locate_structure(const Identifier * structure)
{
    int ret;
    McfStrRef structure_ref;
    int structure_slot;

    structure_ref = _Command_RequireIdentifierRef(structure);
    structure_slot = McfStrRef_SlotId(structure_ref);
    if (structure_slot < 0) {
        McfStrRef_Release(structure_ref);
        return -1;
    }

    ret = locate_structure_unsafe(structure_ref);
    McfStrRef_Release(structure_ref);
    return ret;
}

static inline int
locate_biome_unsafe(McfStrRef biome_ref)
{
    int ret;
    int biome_slot;

    biome_slot = McfStrRef_SlotId(biome_ref);
    if (biome_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{biome: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.biome set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_locate_biome with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(biome_slot)
    );
    return ret;
}

static inline int
locate_biome(const Identifier * biome)
{
    int ret;
    McfStrRef biome_ref;
    int biome_slot;

    biome_ref = _Command_RequireIdentifierRef(biome);
    biome_slot = McfStrRef_SlotId(biome_ref);
    if (biome_slot < 0) {
        McfStrRef_Release(biome_ref);
        return -1;
    }

    ret = locate_biome_unsafe(biome_ref);
    McfStrRef_Release(biome_ref);
    return ret;
}

static inline int
locate_poi_unsafe(McfStrRef poi_ref)
{
    int ret;
    int poi_slot;

    poi_slot = McfStrRef_SlotId(poi_ref);
    if (poi_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{poi: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.poi set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_locate_poi with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(poi_slot)
    );
    return ret;
}

static inline int
locate_poi(const Identifier * poi)
{
    int ret;
    McfStrRef poi_ref;
    int poi_slot;

    poi_ref = _Command_RequireIdentifierRef(poi);
    poi_slot = McfStrRef_SlotId(poi_ref);
    if (poi_slot < 0) {
        McfStrRef_Release(poi_ref);
        return -1;
    }

    ret = locate_poi_unsafe(poi_ref);
    McfStrRef_Release(poi_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
