#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_me:\n"
"    inline $execute store result score r0 vm_regs run me $(action)\n"
"    ret\n"
);

static inline int
me_unsafe(McfStrRef action_ref)
{
    int ret;
    int action_slot;

    action_slot = McfStrRef_SlotId(action_ref);
    if (action_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{action: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.action set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_me with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(action_slot)
    );
    return ret;
}

static inline int
me(String action)
{
    McfStrRef action_ref;
    int action_slot;

    action_ref = _Command_RequireStringRef(action);
    action_slot = McfStrRef_SlotId(action_ref);
    if (action_slot < 0) {
        return -1;
    }
    return me_unsafe(action_ref);
}

#ifdef __cplusplus
}
#endif
