#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
msg_unsafe(McfStrRef target_ref, McfStrRef message_ref)
{
    int ret;
    int target_slot;
    int message_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    message_slot = McfStrRef_SlotId(message_ref);
    if (target_slot < 0 || message_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", message: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.message set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_msg with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(message_slot)
    );
    return ret;
}

static inline int
msg(Target target, String message)
{
    McfStrRef target_ref;
    McfStrRef message_ref;
    int target_slot;
    int message_slot;

    target_ref = _Command_RequireTargetRef(target);
    message_ref = _Command_RequireStringRef(message);
    target_slot = McfStrRef_SlotId(target_ref);
    message_slot = McfStrRef_SlotId(message_ref);
    if (target_slot < 0 || message_slot < 0) {
        return -1;
    }
    return msg_unsafe(target_ref, message_ref);
}

#ifdef __cplusplus
}
#endif
