#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_particle:\n"
"    inline $execute store result score r0 vm_regs run particle $(name)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_particle_at:\n"
"    inline $execute store result score r0 vm_regs run particle $(name) $(x) $(y) $(z)\n"
"    ret\n"
);

static inline int
particle_unsafe(McfStrRef name_ref)
{
    int ret;
    int name_slot;

    name_slot = McfStrRef_SlotId(name_ref);
    if (name_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{name: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.name set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_particle with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(name_slot)
    );
    return ret;
}

static inline int
particle(const Identifier * name)
{
    int ret;
    McfStrRef name_ref;
    int name_slot;

    name_ref = _Command_RequireIdentifierRef(name);
    name_slot = McfStrRef_SlotId(name_ref);
    if (name_slot < 0) {
        McfStrRef_Release(name_ref);
        return -1;
    }

    ret = particle_unsafe(name_ref);
    McfStrRef_Release(name_ref);
    return ret;
}

static inline int
particle_at_unsafe(McfStrRef name_ref, McfStrRef x_ref, McfStrRef y_ref, McfStrRef z_ref)
{
    int ret;
    int name_slot;
    int x_slot;
    int y_slot;
    int z_slot;

    name_slot = McfStrRef_SlotId(name_ref);
    x_slot = McfStrRef_SlotId(x_ref);
    y_slot = McfStrRef_SlotId(y_ref);
    z_slot = McfStrRef_SlotId(z_ref);
    if (name_slot < 0 || x_slot < 0 || y_slot < 0 || z_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{name: \"\", x: \"\", y: \"\", z: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.name set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.x set from storage std:vm mcstr.slots[%2].value\n"
        "inline $data modify storage std:vm s6.cmd.y set from storage std:vm mcstr.slots[%3].value\n"
        "inline $data modify storage std:vm s6.cmd.z set from storage std:vm mcstr.slots[%4].value\n"
        "inline function _ll_shared:z/libmc_cmd_particle_at with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(name_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
    );
    return ret;
}

static inline int
particle_at(const Identifier * name, Vec3d pos)
{
    int ret;
    McfStrRef name_ref;
    McfStrRef x_ref;
    McfStrRef y_ref;
    McfStrRef z_ref;
    int name_slot;
    int x_slot;
    int y_slot;
    int z_slot;

    name_ref = _Command_RequireIdentifierRef(name);
    x_ref = _Command_FormatDoubleRef(pos.x);
    y_ref = _Command_FormatDoubleRef(pos.y);
    z_ref = _Command_FormatDoubleRef(pos.z);
    name_slot = McfStrRef_SlotId(name_ref);
    x_slot = McfStrRef_SlotId(x_ref);
    y_slot = McfStrRef_SlotId(y_ref);
    z_slot = McfStrRef_SlotId(z_ref);
    if (name_slot < 0 || x_slot < 0 || y_slot < 0 || z_slot < 0) {
        McfStrRef_Release(name_ref);
        McfStrRef_Release(x_ref);
        McfStrRef_Release(y_ref);
        McfStrRef_Release(z_ref);
        return -1;
    }

    ret = particle_at_unsafe(name_ref, x_ref, y_ref, z_ref);
    McfStrRef_Release(name_ref);
    McfStrRef_Release(x_ref);
    McfStrRef_Release(y_ref);
    McfStrRef_Release(z_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
