#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
place_feature_unsafe(McfStrRef feature_ref)
{
    int ret;
    int feature_slot;

    feature_slot = McfStrRef_SlotId(feature_ref);
    if (feature_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{feature: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.feature set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_place_feature with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(feature_slot)
    );
    return ret;
}

static inline int
place_feature(const Identifier * feature)
{
    int ret;
    McfStrRef feature_ref;
    int feature_slot;

    feature_ref = _Command_RequireIdentifierRef(feature);
    feature_slot = McfStrRef_SlotId(feature_ref);
    if (feature_slot < 0) {
        McfStrRef_Release(feature_ref);
        return -1;
    }

    ret = place_feature_unsafe(feature_ref);
    McfStrRef_Release(feature_ref);
    return ret;
}

static inline int
place_feature_at_unsafe(McfStrRef feature_ref, int x, int y, int z)
{
    int ret;
    int feature_slot;

    feature_slot = McfStrRef_SlotId(feature_ref);
    if (feature_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.feature set from storage std:vm mcstr.slots[%0].value"
        :
        : "r"(feature_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run place feature $(feature) %1 %2 %3"
        : "=r"(ret)
        : "r"(x), "r"(y), "r"(z)
    );
    return ret;
}

static inline int
place_feature_at(const Identifier * feature, Vec3i pos)
{
    int ret;
    McfStrRef feature_ref;
    int feature_slot;

    feature_ref = _Command_RequireIdentifierRef(feature);
    feature_slot = McfStrRef_SlotId(feature_ref);
    if (feature_slot < 0) {
        McfStrRef_Release(feature_ref);
        return -1;
    }

    ret = place_feature_at_unsafe(feature_ref, pos.x, pos.y, pos.z);
    McfStrRef_Release(feature_ref);
    return ret;
}

static inline int
place_structure_unsafe(McfStrRef structure_ref)
{
    int ret;
    int structure_slot;

    structure_slot = McfStrRef_SlotId(structure_ref);
    if (structure_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{structure: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.structure set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_place_structure with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(structure_slot)
    );
    return ret;
}

static inline int
place_structure(const Identifier * structure)
{
    int ret;
    McfStrRef structure_ref;
    int structure_slot;

    structure_ref = _Command_RequireIdentifierRef(structure);
    structure_slot = McfStrRef_SlotId(structure_ref);
    if (structure_slot < 0) {
        McfStrRef_Release(structure_ref);
        return -1;
    }

    ret = place_structure_unsafe(structure_ref);
    McfStrRef_Release(structure_ref);
    return ret;
}

static inline int
place_structure_at_unsafe(McfStrRef structure_ref, int x, int y, int z)
{
    int ret;
    int structure_slot;

    structure_slot = McfStrRef_SlotId(structure_ref);
    if (structure_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.structure set from storage std:vm mcstr.slots[%0].value"
        :
        : "r"(structure_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run place structure $(structure) %1 %2 %3"
        : "=r"(ret)
        : "r"(x), "r"(y), "r"(z)
    );
    return ret;
}

static inline int
place_structure_at(const Identifier * structure, Vec3i pos)
{
    int ret;
    McfStrRef structure_ref;
    int structure_slot;

    structure_ref = _Command_RequireIdentifierRef(structure);
    structure_slot = McfStrRef_SlotId(structure_ref);
    if (structure_slot < 0) {
        McfStrRef_Release(structure_ref);
        return -1;
    }

    ret = place_structure_at_unsafe(structure_ref, pos.x, pos.y, pos.z);
    McfStrRef_Release(structure_ref);
    return ret;
}

static inline int
place_jigsaw_unsafe(McfStrRef pool_ref, McfStrRef target_ref, int max_depth)
{
    int ret;
    int pool_slot;
    int target_slot;

    pool_slot = McfStrRef_SlotId(pool_ref);
    target_slot = McfStrRef_SlotId(target_ref);
    if (pool_slot < 0 || target_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.pool set from storage std:vm mcstr.slots[%0].value\n"
        "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value"
        :
        : "r"(pool_slot), "r"(target_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run place jigsaw $(pool) $(target) %1"
        : "=r"(ret)
        : "r"(max_depth)
    );
    return ret;
}

static inline int
place_jigsaw(const Identifier * pool, const Identifier * target, int max_depth)
{
    int ret;
    McfStrRef pool_ref;
    McfStrRef target_ref;
    int pool_slot;
    int target_slot;

    pool_ref = _Command_RequireIdentifierRef(pool);
    target_ref = _Command_RequireIdentifierRef(target);
    pool_slot = McfStrRef_SlotId(pool_ref);
    target_slot = McfStrRef_SlotId(target_ref);
    if (pool_slot < 0 || target_slot < 0) {
        McfStrRef_Release(pool_ref);
        McfStrRef_Release(target_ref);
        return -1;
    }

    ret = place_jigsaw_unsafe(pool_ref, target_ref, max_depth);
    McfStrRef_Release(pool_ref);
    McfStrRef_Release(target_ref);
    return ret;
}

static inline int
place_jigsaw_at_unsafe(McfStrRef pool_ref, McfStrRef target_ref, int max_depth, int x, int y, int z)
{
    int ret;
    int pool_slot;
    int target_slot;

    pool_slot = McfStrRef_SlotId(pool_ref);
    target_slot = McfStrRef_SlotId(target_ref);
    if (pool_slot < 0 || target_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.pool set from storage std:vm mcstr.slots[%0].value\n"
        "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value"
        :
        : "r"(pool_slot), "r"(target_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run place jigsaw $(pool) $(target) %1 %2 %3 %4"
        : "=r"(ret)
        : "r"(max_depth), "r"(x), "r"(y), "r"(z)
    );
    return ret;
}

static inline int
place_jigsaw_at(const Identifier * pool, const Identifier * target, int max_depth, Vec3i pos)
{
    int ret;
    McfStrRef pool_ref;
    McfStrRef target_ref;
    int pool_slot;
    int target_slot;

    pool_ref = _Command_RequireIdentifierRef(pool);
    target_ref = _Command_RequireIdentifierRef(target);
    pool_slot = McfStrRef_SlotId(pool_ref);
    target_slot = McfStrRef_SlotId(target_ref);
    if (pool_slot < 0 || target_slot < 0) {
        McfStrRef_Release(pool_ref);
        McfStrRef_Release(target_ref);
        return -1;
    }

    ret = place_jigsaw_at_unsafe(pool_ref, target_ref, max_depth, pos.x, pos.y, pos.z);
    McfStrRef_Release(pool_ref);
    McfStrRef_Release(target_ref);
    return ret;
}

static inline int
place_template_unsafe(McfStrRef template_ref)
{
    int ret;
    int template_slot;

    template_slot = McfStrRef_SlotId(template_ref);
    if (template_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{template: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.template set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_place_template with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(template_slot)
    );
    return ret;
}

static inline int
place_template(const Identifier * template)
{
    int ret;
    McfStrRef template_ref;
    int template_slot;

    template_ref = _Command_RequireIdentifierRef(template);
    template_slot = McfStrRef_SlotId(template_ref);
    if (template_slot < 0) {
        McfStrRef_Release(template_ref);
        return -1;
    }

    ret = place_template_unsafe(template_ref);
    McfStrRef_Release(template_ref);
    return ret;
}

static inline int
place_template_at_unsafe(McfStrRef template_ref, int x, int y, int z)
{
    int ret;
    int template_slot;

    template_slot = McfStrRef_SlotId(template_ref);
    if (template_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.template set from storage std:vm mcstr.slots[%0].value"
        :
        : "r"(template_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run place template $(template) %1 %2 %3"
        : "=r"(ret)
        : "r"(x), "r"(y), "r"(z)
    );
    return ret;
}

static inline int
place_template_at(const Identifier * template, Vec3i pos)
{
    int ret;
    McfStrRef template_ref;
    int template_slot;

    template_ref = _Command_RequireIdentifierRef(template);
    template_slot = McfStrRef_SlotId(template_ref);
    if (template_slot < 0) {
        McfStrRef_Release(template_ref);
        return -1;
    }

    ret = place_template_at_unsafe(template_ref, pos.x, pos.y, pos.z);
    McfStrRef_Release(template_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
