#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
random_value_unsafe(McfStrRef range_ref)
{
    int ret;
    int range_slot;

    range_slot = McfStrRef_SlotId(range_ref);
    if (range_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{range: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.range set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_random_value with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(range_slot)
    );
    return ret;
}

static inline int
random_value(String range)
{
    McfStrRef range_ref;
    int range_slot;

    range_ref = _Command_RequireStringRef(range);
    range_slot = McfStrRef_SlotId(range_ref);
    if (range_slot < 0) {
        return -1;
    }
    return random_value_unsafe(range_ref);
}

static inline int
random_value_seq_unsafe(McfStrRef range_ref, McfStrRef sequence_ref)
{
    int ret;
    int range_slot;
    int sequence_slot;

    range_slot = McfStrRef_SlotId(range_ref);
    sequence_slot = McfStrRef_SlotId(sequence_ref);
    if (range_slot < 0 || sequence_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{range: \"\", sequence: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.range set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.sequence set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_random_value_seq with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(range_slot), "r"(sequence_slot)
    );
    return ret;
}

static inline int
random_value_seq(String range, const Identifier * sequence)
{
    int ret;
    McfStrRef range_ref;
    McfStrRef sequence_ref;
    int range_slot;
    int sequence_slot;

    range_ref = _Command_RequireStringRef(range);
    sequence_ref = _Command_RequireIdentifierRef(sequence);
    range_slot = McfStrRef_SlotId(range_ref);
    sequence_slot = McfStrRef_SlotId(sequence_ref);
    if (range_slot < 0 || sequence_slot < 0) {
        McfStrRef_Release(sequence_ref);
        return -1;
    }

    ret = random_value_seq_unsafe(range_ref, sequence_ref);
    McfStrRef_Release(sequence_ref);
    return ret;
}

static inline int
random_roll_unsafe(McfStrRef range_ref)
{
    int ret;
    int range_slot;

    range_slot = McfStrRef_SlotId(range_ref);
    if (range_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{range: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.range set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_random_roll with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(range_slot)
    );
    return ret;
}

static inline int
random_roll(String range)
{
    McfStrRef range_ref;
    int range_slot;

    range_ref = _Command_RequireStringRef(range);
    range_slot = McfStrRef_SlotId(range_ref);
    if (range_slot < 0) {
        return -1;
    }
    return random_roll_unsafe(range_ref);
}

static inline int
random_roll_seq_unsafe(McfStrRef range_ref, McfStrRef sequence_ref)
{
    int ret;
    int range_slot;
    int sequence_slot;

    range_slot = McfStrRef_SlotId(range_ref);
    sequence_slot = McfStrRef_SlotId(sequence_ref);
    if (range_slot < 0 || sequence_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{range: \"\", sequence: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.range set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.sequence set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_random_roll_seq with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(range_slot), "r"(sequence_slot)
    );
    return ret;
}

static inline int
random_roll_seq(String range, const Identifier * sequence)
{
    int ret;
    McfStrRef range_ref;
    McfStrRef sequence_ref;
    int range_slot;
    int sequence_slot;

    range_ref = _Command_RequireStringRef(range);
    sequence_ref = _Command_RequireIdentifierRef(sequence);
    range_slot = McfStrRef_SlotId(range_ref);
    sequence_slot = McfStrRef_SlotId(sequence_ref);
    if (range_slot < 0 || sequence_slot < 0) {
        McfStrRef_Release(sequence_ref);
        return -1;
    }

    ret = random_roll_seq_unsafe(range_ref, sequence_ref);
    McfStrRef_Release(sequence_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
