#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
rotate_unsafe(McfStrRef target_ref, McfStrRef yaw_ref, McfStrRef pitch_ref)
{
    int ret;
    int target_slot;
    int yaw_slot;
    int pitch_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    yaw_slot = McfStrRef_SlotId(yaw_ref);
    pitch_slot = McfStrRef_SlotId(pitch_ref);
    if (target_slot < 0 || yaw_slot < 0 || pitch_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", yaw: \"\", pitch: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.yaw set from storage std:vm mcstr.slots[%2].value\n"
        "inline $data modify storage std:vm s6.cmd.pitch set from storage std:vm mcstr.slots[%3].value\n"
        "inline function _ll_shared:z/libmc_cmd_rotate with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(yaw_slot), "r"(pitch_slot)
    );
    return ret;
}

static inline int
rotate(Target target, Vec2f rotation)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef yaw_ref;
    McfStrRef pitch_ref;
    int target_slot;
    int yaw_slot;
    int pitch_slot;

    target_ref = _Command_RequireTargetRef(target);
    yaw_ref = _Command_FormatFloatRef(rotation.x);
    pitch_ref = _Command_FormatFloatRef(rotation.y);
    target_slot = McfStrRef_SlotId(target_ref);
    yaw_slot = McfStrRef_SlotId(yaw_ref);
    pitch_slot = McfStrRef_SlotId(pitch_ref);
    if (target_slot < 0 || yaw_slot < 0 || pitch_slot < 0) {
        McfStrRef_Release(yaw_ref);
        McfStrRef_Release(pitch_ref);
        return -1;
    }

    ret = rotate_unsafe(target_ref, yaw_ref, pitch_ref);
    McfStrRef_Release(yaw_ref);
    McfStrRef_Release(pitch_ref);
    return ret;
}

static inline int
rotate_facing_entity_unsafe(McfStrRef target_ref, McfStrRef entity_ref)
{
    int ret;
    int target_slot;
    int entity_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    entity_slot = McfStrRef_SlotId(entity_ref);
    if (target_slot < 0 || entity_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", entity: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.entity set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_rotate_facing_entity with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(entity_slot)
    );
    return ret;
}

static inline int
rotate_facing_entity(Target target, Target entity)
{
    McfStrRef target_ref;
    McfStrRef entity_ref;
    int target_slot;
    int entity_slot;

    target_ref = _Command_RequireTargetRef(target);
    entity_ref = _Command_RequireTargetRef(entity);
    target_slot = McfStrRef_SlotId(target_ref);
    entity_slot = McfStrRef_SlotId(entity_ref);
    if (target_slot < 0 || entity_slot < 0) {
        return -1;
    }
    return rotate_facing_entity_unsafe(target_ref, entity_ref);
}

static inline int
rotate_facing_pos_unsafe(McfStrRef target_ref, McfStrRef x_ref, McfStrRef y_ref, McfStrRef z_ref)
{
    int ret;
    int target_slot;
    int x_slot;
    int y_slot;
    int z_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    x_slot = McfStrRef_SlotId(x_ref);
    y_slot = McfStrRef_SlotId(y_ref);
    z_slot = McfStrRef_SlotId(z_ref);
    if (target_slot < 0 || x_slot < 0 || y_slot < 0 || z_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", x: \"\", y: \"\", z: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.x set from storage std:vm mcstr.slots[%2].value\n"
        "inline $data modify storage std:vm s6.cmd.y set from storage std:vm mcstr.slots[%3].value\n"
        "inline $data modify storage std:vm s6.cmd.z set from storage std:vm mcstr.slots[%4].value\n"
        "inline function _ll_shared:z/libmc_cmd_rotate_facing_pos with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
    );
    return ret;
}

static inline int
rotate_facing_pos(Target target, Vec3d pos)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef x_ref;
    McfStrRef y_ref;
    McfStrRef z_ref;
    int target_slot;
    int x_slot;
    int y_slot;
    int z_slot;

    target_ref = _Command_RequireTargetRef(target);
    x_ref = _Command_FormatDoubleRef(pos.x);
    y_ref = _Command_FormatDoubleRef(pos.y);
    z_ref = _Command_FormatDoubleRef(pos.z);
    target_slot = McfStrRef_SlotId(target_ref);
    x_slot = McfStrRef_SlotId(x_ref);
    y_slot = McfStrRef_SlotId(y_ref);
    z_slot = McfStrRef_SlotId(z_ref);
    if (target_slot < 0 || x_slot < 0 || y_slot < 0 || z_slot < 0) {
        McfStrRef_Release(x_ref);
        McfStrRef_Release(y_ref);
        McfStrRef_Release(z_ref);
        return -1;
    }

    ret = rotate_facing_pos_unsafe(target_ref, x_ref, y_ref, z_ref);
    McfStrRef_Release(x_ref);
    McfStrRef_Release(y_ref);
    McfStrRef_Release(z_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
