#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
say_unsafe(McfStrRef text_ref)
{
    int ret;
    int text_slot;

    text_slot = McfStrRef_SlotId(text_ref);
    if (text_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{text: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.text set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_say with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(text_slot)
    );
    return ret;
}

static inline int
say(String text)
{
    McfStrRef text_ref;
    int text_slot;

    text_ref = _Command_RequireStringRef(text);
    text_slot = McfStrRef_SlotId(text_ref);
    if (text_slot < 0) {
        return -1;
    }
    return say_unsafe(text_ref);
}

#ifdef __cplusplus
}
#endif
