#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
schedule_function_unsafe(McfStrRef name_ref, int delay)
{
    int ret;
    int name_slot;

    name_slot = McfStrRef_SlotId(name_ref);
    if (name_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.name set from storage std:vm mcstr.slots[%0].value"
        :
        : "r"(name_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run schedule function $(name) %1"
        : "=r"(ret)
        : "r"(delay)
    );
    return ret;
}

static inline int
schedule_function(const Identifier * name, int delay)
{
    int ret;
    McfStrRef name_ref;
    int name_slot;

    name_ref = _Command_RequireIdentifierRef(name);
    name_slot = McfStrRef_SlotId(name_ref);
    if (name_slot < 0) {
        McfStrRef_Release(name_ref);
        return -1;
    }

    ret = schedule_function_unsafe(name_ref, delay);
    McfStrRef_Release(name_ref);
    return ret;
}

static inline int
schedule_clear_unsafe(McfStrRef name_ref)
{
    int ret;
    int name_slot;

    name_slot = McfStrRef_SlotId(name_ref);
    if (name_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{name: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.name set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_schedule_clear with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(name_slot)
    );
    return ret;
}

static inline int
schedule_clear(String name)
{
    McfStrRef name_ref;
    int name_slot;

    name_ref = _Command_RequireStringRef(name);
    name_slot = McfStrRef_SlotId(name_ref);
    if (name_slot < 0) {
        return -1;
    }
    return schedule_clear_unsafe(name_ref);
}

#ifdef __cplusplus
}
#endif
