#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_spawnpoint:\n"
"    inline execute store result score r0 vm_regs run spawnpoint\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_spawnpoint_target:\n"
"    inline $execute store result score r0 vm_regs run spawnpoint $(target)\n"
"    ret\n"
);

static inline int
spawnpoint(void)
{
    int ret;

    __asm volatile (
        "inline function _ll_shared:z/libmc_cmd_spawnpoint\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
    );
    return ret;
}

static inline int
spawnpoint_target_unsafe(McfStrRef target_ref)
{
    int ret;
    int target_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_spawnpoint_target with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot)
    );
    return ret;
}

static inline int
spawnpoint_target(Target target)
{
    McfStrRef target_ref;
    int target_slot;

    target_ref = _Command_RequireTargetRef(target);
    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }
    return spawnpoint_target_unsafe(target_ref);
}

static inline int
spawnpoint_at_unsafe(McfStrRef target_ref, int x, int y, int z)
{
    int ret;
    int target_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value"
        :
        : "r"(target_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run spawnpoint $(target) %1 %2 %3"
        : "=r"(ret)
        : "r"(x), "r"(y), "r"(z)
    );
    return ret;
}

static inline int
spawnpoint_at(Target target, Vec3i pos)
{
    McfStrRef target_ref;
    int target_slot;

    target_ref = _Command_RequireTargetRef(target);
    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }
    return spawnpoint_at_unsafe(target_ref, pos.x, pos.y, pos.z);
}

#ifdef __cplusplus
}
#endif
