#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
summon_unsafe(McfStrRef type_ref, McfStrRef x_ref, McfStrRef y_ref, McfStrRef z_ref)
{
    int ret;
    int type_slot;
    int x_slot;
    int y_slot;
    int z_slot;

    type_slot = McfStrRef_SlotId(type_ref);
    x_slot = McfStrRef_SlotId(x_ref);
    y_slot = McfStrRef_SlotId(y_ref);
    z_slot = McfStrRef_SlotId(z_ref);
    if (type_slot < 0 || x_slot < 0 || y_slot < 0 || z_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{type: \"\", x: \"\", y: \"\", z: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.type set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.x set from storage std:vm mcstr.slots[%2].value\n"
        "inline $data modify storage std:vm s6.cmd.y set from storage std:vm mcstr.slots[%3].value\n"
        "inline $data modify storage std:vm s6.cmd.z set from storage std:vm mcstr.slots[%4].value\n"
        "inline function _ll_shared:z/libmc_cmd_summon with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(type_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
    );
    return ret;
}

static inline int
summon(Entity type, Vec3d pos)
{
    int ret;
    McfStrRef type_ref;
    McfStrRef x_ref;
    McfStrRef y_ref;
    McfStrRef z_ref;
    int type_slot;
    int x_slot;
    int y_slot;
    int z_slot;

    type_ref = Entity_EnsureMcfName(type);
    x_ref = _Command_FormatDoubleRef(pos.x);
    y_ref = _Command_FormatDoubleRef(pos.y);
    z_ref = _Command_FormatDoubleRef(pos.z);
    type_slot = McfStrRef_SlotId(type_ref);
    x_slot = McfStrRef_SlotId(x_ref);
    y_slot = McfStrRef_SlotId(y_ref);
    z_slot = McfStrRef_SlotId(z_ref);
    if (type_slot < 0 || x_slot < 0 || y_slot < 0 || z_slot < 0) {
        McfStrRef_Release(x_ref);
        McfStrRef_Release(y_ref);
        McfStrRef_Release(z_ref);
        return -1;
    }

    ret = summon_unsafe(type_ref, x_ref, y_ref, z_ref);
    McfStrRef_Release(x_ref);
    McfStrRef_Release(y_ref);
    McfStrRef_Release(z_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
