#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
teammsg_unsafe(McfStrRef message_ref)
{
    int ret;
    int message_slot;

    message_slot = McfStrRef_SlotId(message_ref);
    if (message_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{message: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.message set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_teammsg with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(message_slot)
    );
    return ret;
}

static inline int
teammsg(String message)
{
    McfStrRef message_ref;
    int message_slot;

    message_ref = _Command_RequireStringRef(message);
    message_slot = McfStrRef_SlotId(message_ref);
    if (message_slot < 0) {
        return -1;
    }
    return teammsg_unsafe(message_ref);
}

#ifdef __cplusplus
}
#endif
