#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
tellraw_unsafe(McfStrRef target_ref, McfStrRef json_ref)
{
    int ret;
    int target_slot;
    int json_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    json_slot = McfStrRef_SlotId(json_ref);
    if (target_slot < 0 || json_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", json: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.json set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_tellraw with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(json_slot)
    );
    return ret;
}

static inline int
tellraw(Target target, String json)
{
    McfStrRef target_ref;
    McfStrRef json_ref;
    int target_slot;
    int json_slot;

    target_ref = _Command_RequireTargetRef(target);
    json_ref = _Command_RequireStringRef(json);
    target_slot = McfStrRef_SlotId(target_ref);
    json_slot = McfStrRef_SlotId(json_ref);
    if (target_slot < 0 || json_slot < 0) {
        return -1;
    }
    return tellraw_unsafe(target_ref, json_ref);
}

#ifdef __cplusplus
}
#endif
