#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"

typedef enum {
    TIME_PRESET_DAY,
    TIME_PRESET_NOON,
    TIME_PRESET_NIGHT,
    TIME_PRESET_MIDNIGHT
} TimePreset;

typedef enum {
    TIME_QUERY_DAYTIME,
    TIME_QUERY_GAMETIME,
    TIME_QUERY_DAY
} TimeQueryKind;

#ifdef __cplusplus
extern "C" {
#endif

static inline int
time_set(int amount)
{
    int ret;

    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run time set %1"
        : "=r"(ret)
        : "r"(amount)
    );
    return ret;
}

static inline int
time_set_preset(TimePreset preset)
{
    int ret;

    switch (preset) {
        case TIME_PRESET_DAY:
            __asm volatile (
                "inline execute store result score %0 vm_regs run time set day"
                : "=r"(ret)
            );
            return ret;
        case TIME_PRESET_NOON:
            __asm volatile (
                "inline execute store result score %0 vm_regs run time set noon"
                : "=r"(ret)
            );
            return ret;
        case TIME_PRESET_NIGHT:
            __asm volatile (
                "inline execute store result score %0 vm_regs run time set night"
                : "=r"(ret)
            );
            return ret;
        case TIME_PRESET_MIDNIGHT:
            __asm volatile (
                "inline execute store result score %0 vm_regs run time set midnight"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
time_add(int amount)
{
    int ret;

    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run time add %1"
        : "=r"(ret)
        : "r"(amount)
    );
    return ret;
}

static inline int
time_query(TimeQueryKind query)
{
    int ret;

    switch (query) {
        case TIME_QUERY_DAYTIME:
            __asm volatile (
                "inline execute store result score %0 vm_regs run time query daytime"
                : "=r"(ret)
            );
            return ret;
        case TIME_QUERY_GAMETIME:
            __asm volatile (
                "inline execute store result score %0 vm_regs run time query gametime"
                : "=r"(ret)
            );
            return ret;
        case TIME_QUERY_DAY:
            __asm volatile (
                "inline execute store result score %0 vm_regs run time query day"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

#ifdef __cplusplus
}
#endif
