#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
trigger_unsafe(McfStrRef objective_ref)
{
    int ret;
    int objective_slot;

    objective_slot = McfStrRef_SlotId(objective_ref);
    if (objective_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{objective: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.objective set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_trigger with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(objective_slot)
    );
    return ret;
}

static inline int
trigger(String objective)
{
    McfStrRef objective_ref;
    int objective_slot;

    objective_ref = _Command_RequireStringRef(objective);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (objective_slot < 0) {
        return -1;
    }
    return trigger_unsafe(objective_ref);
}

static inline int
trigger_add_unsafe(McfStrRef objective_ref, int value)
{
    int ret;
    int objective_slot;

    objective_slot = McfStrRef_SlotId(objective_ref);
    if (objective_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.objective set from storage std:vm mcstr.slots[%0].value"
        :
        : "r"(objective_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run trigger $(objective) add %1"
        : "=r"(ret)
        : "r"(value)
    );
    return ret;
}

static inline int
trigger_add(String objective, int value)
{
    McfStrRef objective_ref;
    int objective_slot;

    objective_ref = _Command_RequireStringRef(objective);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (objective_slot < 0) {
        return -1;
    }
    return trigger_add_unsafe(objective_ref, value);
}

static inline int
trigger_set_unsafe(McfStrRef objective_ref, int value)
{
    int ret;
    int objective_slot;

    objective_slot = McfStrRef_SlotId(objective_ref);
    if (objective_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.objective set from storage std:vm mcstr.slots[%0].value"
        :
        : "r"(objective_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run trigger $(objective) set %1"
        : "=r"(ret)
        : "r"(value)
    );
    return ret;
}

static inline int
trigger_set(String objective, int value)
{
    McfStrRef objective_ref;
    int objective_slot;

    objective_ref = _Command_RequireStringRef(objective);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (objective_slot < 0) {
        return -1;
    }
    return trigger_set_unsafe(objective_ref, value);
}

#ifdef __cplusplus
}
#endif
