#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_worldborder_set:\n"
"    inline $execute store result score r0 vm_regs run worldborder set $(distance)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_worldborder_add:\n"
"    inline $execute store result score r0 vm_regs run worldborder add $(distance)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_worldborder_center:\n"
"    inline $execute store result score r0 vm_regs run worldborder center $(x) $(z)\n"
"    ret\n"
);

static inline int
worldborder_set_unsafe(McfStrRef distance_ref)
{
    int ret;
    int distance_slot;

    distance_slot = McfStrRef_SlotId(distance_ref);
    if (distance_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{distance: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.distance set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_worldborder_set with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(distance_slot)
    );
    return ret;
}

static inline int
worldborder_set(double distance)
{
    int ret;
    McfStrRef distance_ref;
    int distance_slot;

    distance_ref = _Command_FormatDoubleRef(distance);
    distance_slot = McfStrRef_SlotId(distance_ref);
    if (distance_slot < 0) {
        McfStrRef_Release(distance_ref);
        return -1;
    }

    ret = worldborder_set_unsafe(distance_ref);
    McfStrRef_Release(distance_ref);
    return ret;
}

static inline int
worldborder_add_unsafe(McfStrRef distance_ref)
{
    int ret;
    int distance_slot;

    distance_slot = McfStrRef_SlotId(distance_ref);
    if (distance_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{distance: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.distance set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_worldborder_add with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(distance_slot)
    );
    return ret;
}

static inline int
worldborder_add(double distance)
{
    int ret;
    McfStrRef distance_ref;
    int distance_slot;

    distance_ref = _Command_FormatDoubleRef(distance);
    distance_slot = McfStrRef_SlotId(distance_ref);
    if (distance_slot < 0) {
        McfStrRef_Release(distance_ref);
        return -1;
    }

    ret = worldborder_add_unsafe(distance_ref);
    McfStrRef_Release(distance_ref);
    return ret;
}

static inline int
worldborder_set_time_unsafe(McfStrRef distance_ref, int seconds)
{
    int ret;
    int distance_slot;

    distance_slot = McfStrRef_SlotId(distance_ref);
    if (distance_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.distance set from storage std:vm mcstr.slots[%0].value"
        :
        : "r"(distance_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run worldborder set $(distance) %1"
        : "=r"(ret)
        : "r"(seconds)
    );
    return ret;
}

static inline int
worldborder_set_time(double distance, int seconds)
{
    int ret;
    McfStrRef distance_ref;
    int distance_slot;

    distance_ref = _Command_FormatDoubleRef(distance);
    distance_slot = McfStrRef_SlotId(distance_ref);
    if (distance_slot < 0) {
        McfStrRef_Release(distance_ref);
        return -1;
    }

    ret = worldborder_set_time_unsafe(distance_ref, seconds);
    McfStrRef_Release(distance_ref);
    return ret;
}

static inline int
worldborder_center_unsafe(McfStrRef x_ref, McfStrRef z_ref)
{
    int ret;
    int x_slot;
    int z_slot;

    x_slot = McfStrRef_SlotId(x_ref);
    z_slot = McfStrRef_SlotId(z_ref);
    if (x_slot < 0 || z_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{x: \"\", z: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.x set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.z set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_worldborder_center with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(x_slot), "r"(z_slot)
    );
    return ret;
}

static inline int
worldborder_center(double x, double z)
{
    int ret;
    McfStrRef x_ref;
    McfStrRef z_ref;
    int x_slot;
    int z_slot;

    x_ref = _Command_FormatDoubleRef(x);
    z_ref = _Command_FormatDoubleRef(z);
    x_slot = McfStrRef_SlotId(x_ref);
    z_slot = McfStrRef_SlotId(z_ref);
    if (x_slot < 0 || z_slot < 0) {
        McfStrRef_Release(x_ref);
        McfStrRef_Release(z_ref);
        return -1;
    }

    ret = worldborder_center_unsafe(x_ref, z_ref);
    McfStrRef_Release(x_ref);
    McfStrRef_Release(z_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
