#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "experience.h"

#ifdef __cplusplus
extern "C" {
#endif

static inline int
xp_add_points(Target target, int amount)
{
    return experience_add_points(target, amount);
}

static inline int
xp_add_points_unsafe(McfStrRef target_ref, int amount)
{
    return experience_add_points_unsafe(target_ref, amount);
}

static inline int
xp_add_levels(Target target, int amount)
{
    return experience_add_levels(target, amount);
}

static inline int
xp_add_levels_unsafe(McfStrRef target_ref, int amount)
{
    return experience_add_levels_unsafe(target_ref, amount);
}

static inline int
xp_set_points(Target target, int amount)
{
    return experience_set_points(target, amount);
}

static inline int
xp_set_points_unsafe(McfStrRef target_ref, int amount)
{
    return experience_set_points_unsafe(target_ref, amount);
}

static inline int
xp_set_levels(Target target, int amount)
{
    return experience_set_levels(target, amount);
}

static inline int
xp_set_levels_unsafe(McfStrRef target_ref, int amount)
{
    return experience_set_levels_unsafe(target_ref, amount);
}

static inline int
xp_query_points(Target target)
{
    return experience_query_points(target);
}

static inline int
xp_query_points_unsafe(McfStrRef target_ref)
{
    return experience_query_points_unsafe(target_ref);
}

static inline int
xp_query_levels(Target target)
{
    return experience_query_levels(target);
}

static inline int
xp_query_levels_unsafe(McfStrRef target_ref)
{
    return experience_query_levels_unsafe(target_ref);
}

#ifdef __cplusplus
}
#endif
