/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

/*
 * File-scope command-helper label definitions for 'advancement', split out
 * of bindings/advancement.h so that a user translation unit which
 * #includes that header does NOT re-emit these `export` labels (they are already
 * provided, exactly once, by the LTO-built _ll_libmc.mch that every mcasm
 * program includes). This file is compiled once into the libmc stdlib bundle.
 */

__asm__(
"export _ll_shared:z/advancement_everything_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run advancement grant $(target) everything\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_everything_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run advancement revoke $(target) everything\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_only_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run advancement grant $(target) only $(advancement)\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_only_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run advancement revoke $(target) only $(advancement)\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_only_criterion_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run advancement grant $(target) only $(advancement) $(criterion)\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_only_criterion_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run advancement revoke $(target) only $(advancement) $(criterion)\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_from_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run advancement grant $(target) from $(advancement)\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_from_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run advancement revoke $(target) from $(advancement)\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_through_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run advancement grant $(target) through $(advancement)\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_through_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run advancement revoke $(target) through $(advancement)\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_until_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run advancement grant $(target) until $(advancement)\n"
"    ret\n"
"\n"
"export _ll_shared:z/advancement_until_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run advancement revoke $(target) until $(advancement)\n"
"    ret\n"
);
