#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"

typedef enum {
    ATTRIBUTE_ADD_VALUE,
    ATTRIBUTE_ADD_MULTIPLIED_BASE,
    ATTRIBUTE_ADD_MULTIPLIED_TOTAL
} AttributeAddMode;

#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_attribute_get:\n"
"    inline $execute store result score r0 vm_regs run attribute $(target) $(attribute) get\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_attribute_get_scaled:\n"
"    inline $execute store result score r0 vm_regs run attribute $(target) $(attribute) get $(scale)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_attribute_base_get:\n"
"    inline $execute store result score r0 vm_regs run attribute $(target) $(attribute) base get\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_attribute_base_set:\n"
"    inline $execute store result score r0 vm_regs run attribute $(target) $(attribute) base set $(value)\n"
"    ret\n"
"\n"
"export _ll_shared:z/attribute_modifier_add_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run attribute $(target) $(attribute) modifier add $(id) $(value) add_value\n"
"    ret\n"
"\n"
"export _ll_shared:z/attribute_modifier_add_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run attribute $(target) $(attribute) modifier add $(id) $(value) add_multiplied_base\n"
"    ret\n"
"\n"
"export _ll_shared:z/attribute_modifier_add_unsafe_exec_2:\n"
"    inline $execute store result score r0 vm_regs run attribute $(target) $(attribute) modifier add $(id) $(value) add_multiplied_total\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_attribute_modifier_remove:\n"
"    inline $execute store result score r0 vm_regs run attribute $(target) $(attribute) modifier remove $(id)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_attribute_modifier_value_get:\n"
"    inline $execute store result score r0 vm_regs run attribute $(target) $(attribute) modifier value get $(id)\n"
"    ret\n"
);

static inline int
attribute_get_unsafe(McfStrRef target_ref, McfStrRef attribute_ref)
{
    int ret;
    int target_slot;
    int attribute_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    attribute_slot = McfStrRef_SlotId(attribute_ref);
    if (target_slot < 0 || attribute_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", attribute: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.attribute set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_attribute_get with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(attribute_slot)
    );
    return ret;
}

static inline int
attribute_get(Target target, const Identifier * attribute)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef attribute_ref;
    int target_slot;
    int attribute_slot;

    target_ref = _Command_RequireTargetRef(target);
    attribute_ref = _Command_RequireIdentifierRef(attribute);
    target_slot = McfStrRef_SlotId(target_ref);
    attribute_slot = McfStrRef_SlotId(attribute_ref);
    if (target_slot < 0 || attribute_slot < 0) {
        McfStrRef_Release(attribute_ref);
        return -1;
    }

    ret = attribute_get_unsafe(target_ref, attribute_ref);
    McfStrRef_Release(attribute_ref);
    return ret;
}

static inline int
attribute_get_scaled_unsafe(McfStrRef target_ref, McfStrRef attribute_ref, McfStrRef scale_ref)
{
    int ret;
    int target_slot;
    int attribute_slot;
    int scale_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    attribute_slot = McfStrRef_SlotId(attribute_ref);
    scale_slot = McfStrRef_SlotId(scale_ref);
    if (target_slot < 0 || attribute_slot < 0 || scale_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", attribute: \"\", scale: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.attribute set from storage std:vm mcstr.slots[%2].value\n"
        "inline $data modify storage std:vm s6.cmd.scale set from storage std:vm mcstr.slots[%3].value\n"
        "inline function _ll_shared:z/libmc_cmd_attribute_get_scaled with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(attribute_slot), "r"(scale_slot)
    );
    return ret;
}

static inline int
attribute_get_scaled(Target target, const Identifier * attribute, double scale)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef attribute_ref;
    McfStrRef scale_ref;
    int target_slot;
    int attribute_slot;
    int scale_slot;

    target_ref = _Command_RequireTargetRef(target);
    attribute_ref = _Command_RequireIdentifierRef(attribute);
    scale_ref = _Command_FormatDoubleRef(scale);
    target_slot = McfStrRef_SlotId(target_ref);
    attribute_slot = McfStrRef_SlotId(attribute_ref);
    scale_slot = McfStrRef_SlotId(scale_ref);
    if (target_slot < 0 || attribute_slot < 0 || scale_slot < 0) {
        McfStrRef_Release(attribute_ref);
        McfStrRef_Release(scale_ref);
        return -1;
    }

    ret = attribute_get_scaled_unsafe(target_ref, attribute_ref, scale_ref);
    McfStrRef_Release(attribute_ref);
    McfStrRef_Release(scale_ref);
    return ret;
}

static inline int
attribute_base_get_unsafe(McfStrRef target_ref, McfStrRef attribute_ref)
{
    int ret;
    int target_slot;
    int attribute_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    attribute_slot = McfStrRef_SlotId(attribute_ref);
    if (target_slot < 0 || attribute_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", attribute: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.attribute set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_attribute_base_get with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(attribute_slot)
    );
    return ret;
}

static inline int
attribute_base_get(Target target, const Identifier * attribute)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef attribute_ref;
    int target_slot;
    int attribute_slot;

    target_ref = _Command_RequireTargetRef(target);
    attribute_ref = _Command_RequireIdentifierRef(attribute);
    target_slot = McfStrRef_SlotId(target_ref);
    attribute_slot = McfStrRef_SlotId(attribute_ref);
    if (target_slot < 0 || attribute_slot < 0) {
        McfStrRef_Release(attribute_ref);
        return -1;
    }

    ret = attribute_base_get_unsafe(target_ref, attribute_ref);
    McfStrRef_Release(attribute_ref);
    return ret;
}

static inline int
attribute_base_set_unsafe(McfStrRef target_ref, McfStrRef attribute_ref, McfStrRef value_ref)
{
    int ret;
    int target_slot;
    int attribute_slot;
    int value_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    attribute_slot = McfStrRef_SlotId(attribute_ref);
    value_slot = McfStrRef_SlotId(value_ref);
    if (target_slot < 0 || attribute_slot < 0 || value_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", attribute: \"\", value: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.attribute set from storage std:vm mcstr.slots[%2].value\n"
        "inline $data modify storage std:vm s6.cmd.value set from storage std:vm mcstr.slots[%3].value\n"
        "inline function _ll_shared:z/libmc_cmd_attribute_base_set with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(attribute_slot), "r"(value_slot)
    );
    return ret;
}

static inline int
attribute_base_set(Target target, const Identifier * attribute, double value)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef attribute_ref;
    McfStrRef value_ref;
    int target_slot;
    int attribute_slot;
    int value_slot;

    target_ref = _Command_RequireTargetRef(target);
    attribute_ref = _Command_RequireIdentifierRef(attribute);
    value_ref = _Command_FormatDoubleRef(value);
    target_slot = McfStrRef_SlotId(target_ref);
    attribute_slot = McfStrRef_SlotId(attribute_ref);
    value_slot = McfStrRef_SlotId(value_ref);
    if (target_slot < 0 || attribute_slot < 0 || value_slot < 0) {
        McfStrRef_Release(attribute_ref);
        McfStrRef_Release(value_ref);
        return -1;
    }

    ret = attribute_base_set_unsafe(target_ref, attribute_ref, value_ref);
    McfStrRef_Release(attribute_ref);
    McfStrRef_Release(value_ref);
    return ret;
}

static inline int
attribute_modifier_add_unsafe(McfStrRef target_ref, McfStrRef attribute_ref, McfStrRef id_ref, McfStrRef value_ref, AttributeAddMode mode)
{
    int ret;
    int target_slot;
    int attribute_slot;
    int id_slot;
    int value_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    attribute_slot = McfStrRef_SlotId(attribute_ref);
    id_slot = McfStrRef_SlotId(id_ref);
    value_slot = McfStrRef_SlotId(value_ref);
    if (target_slot < 0 || attribute_slot < 0 || id_slot < 0 || value_slot < 0) {
        return -1;
    }

    switch (mode) {
        case ATTRIBUTE_ADD_VALUE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.attribute set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.value set from storage std:vm mcstr.slots[%3].value"
                :
                : "r"(target_slot), "r"(attribute_slot), "r"(id_slot), "r"(value_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/attribute_modifier_add_unsafe_exec_0 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case ATTRIBUTE_ADD_MULTIPLIED_BASE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.attribute set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.value set from storage std:vm mcstr.slots[%3].value"
                :
                : "r"(target_slot), "r"(attribute_slot), "r"(id_slot), "r"(value_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/attribute_modifier_add_unsafe_exec_1 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case ATTRIBUTE_ADD_MULTIPLIED_TOTAL:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.attribute set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.id set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.value set from storage std:vm mcstr.slots[%3].value"
                :
                : "r"(target_slot), "r"(attribute_slot), "r"(id_slot), "r"(value_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/attribute_modifier_add_unsafe_exec_2 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
attribute_modifier_add(Target target, const Identifier * attribute, const Identifier * id, double value, AttributeAddMode mode)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef attribute_ref;
    McfStrRef id_ref;
    McfStrRef value_ref;
    int target_slot;
    int attribute_slot;
    int id_slot;
    int value_slot;

    target_ref = _Command_RequireTargetRef(target);
    attribute_ref = _Command_RequireIdentifierRef(attribute);
    id_ref = _Command_RequireIdentifierRef(id);
    value_ref = _Command_FormatDoubleRef(value);
    target_slot = McfStrRef_SlotId(target_ref);
    attribute_slot = McfStrRef_SlotId(attribute_ref);
    id_slot = McfStrRef_SlotId(id_ref);
    value_slot = McfStrRef_SlotId(value_ref);
    if (target_slot < 0 || attribute_slot < 0 || id_slot < 0 || value_slot < 0) {
        McfStrRef_Release(attribute_ref);
        McfStrRef_Release(id_ref);
        McfStrRef_Release(value_ref);
        return -1;
    }

    ret = attribute_modifier_add_unsafe(target_ref, attribute_ref, id_ref, value_ref, mode);
    McfStrRef_Release(attribute_ref);
    McfStrRef_Release(id_ref);
    McfStrRef_Release(value_ref);
    return ret;
}

static inline int
attribute_modifier_remove_unsafe(McfStrRef target_ref, McfStrRef attribute_ref, McfStrRef id_ref)
{
    int ret;
    int target_slot;
    int attribute_slot;
    int id_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    attribute_slot = McfStrRef_SlotId(attribute_ref);
    id_slot = McfStrRef_SlotId(id_ref);
    if (target_slot < 0 || attribute_slot < 0 || id_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", attribute: \"\", id: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.attribute set from storage std:vm mcstr.slots[%2].value\n"
        "inline $data modify storage std:vm s6.cmd.id set from storage std:vm mcstr.slots[%3].value\n"
        "inline function _ll_shared:z/libmc_cmd_attribute_modifier_remove with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(attribute_slot), "r"(id_slot)
    );
    return ret;
}

static inline int
attribute_modifier_remove(Target target, const Identifier * attribute, const Identifier * id)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef attribute_ref;
    McfStrRef id_ref;
    int target_slot;
    int attribute_slot;
    int id_slot;

    target_ref = _Command_RequireTargetRef(target);
    attribute_ref = _Command_RequireIdentifierRef(attribute);
    id_ref = _Command_RequireIdentifierRef(id);
    target_slot = McfStrRef_SlotId(target_ref);
    attribute_slot = McfStrRef_SlotId(attribute_ref);
    id_slot = McfStrRef_SlotId(id_ref);
    if (target_slot < 0 || attribute_slot < 0 || id_slot < 0) {
        McfStrRef_Release(attribute_ref);
        McfStrRef_Release(id_ref);
        return -1;
    }

    ret = attribute_modifier_remove_unsafe(target_ref, attribute_ref, id_ref);
    McfStrRef_Release(attribute_ref);
    McfStrRef_Release(id_ref);
    return ret;
}

static inline int
attribute_modifier_value_get_unsafe(McfStrRef target_ref, McfStrRef attribute_ref, McfStrRef id_ref)
{
    int ret;
    int target_slot;
    int attribute_slot;
    int id_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    attribute_slot = McfStrRef_SlotId(attribute_ref);
    id_slot = McfStrRef_SlotId(id_ref);
    if (target_slot < 0 || attribute_slot < 0 || id_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", attribute: \"\", id: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.attribute set from storage std:vm mcstr.slots[%2].value\n"
        "inline $data modify storage std:vm s6.cmd.id set from storage std:vm mcstr.slots[%3].value\n"
        "inline function _ll_shared:z/libmc_cmd_attribute_modifier_value_get with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(attribute_slot), "r"(id_slot)
    );
    return ret;
}

static inline int
attribute_modifier_value_get(Target target, const Identifier * attribute, const Identifier * id)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef attribute_ref;
    McfStrRef id_ref;
    int target_slot;
    int attribute_slot;
    int id_slot;

    target_ref = _Command_RequireTargetRef(target);
    attribute_ref = _Command_RequireIdentifierRef(attribute);
    id_ref = _Command_RequireIdentifierRef(id);
    target_slot = McfStrRef_SlotId(target_ref);
    attribute_slot = McfStrRef_SlotId(attribute_ref);
    id_slot = McfStrRef_SlotId(id_ref);
    if (target_slot < 0 || attribute_slot < 0 || id_slot < 0) {
        McfStrRef_Release(attribute_ref);
        McfStrRef_Release(id_ref);
        return -1;
    }

    ret = attribute_modifier_value_get_unsafe(target_ref, attribute_ref, id_ref);
    McfStrRef_Release(attribute_ref);
    McfStrRef_Release(id_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
