/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

/*
 * File-scope command-helper label definitions for 'damage', split out
 * of bindings/damage.h so that a user translation unit which
 * #includes that header does NOT re-emit these `export` labels (they are already
 * provided, exactly once, by the LTO-built _ll_libmc.mch that every mcasm
 * program includes). This file is compiled once into the libmc stdlib bundle.
 */

__asm__(
"export _ll_shared:z/libmc_cmd_damage:\n"
"    inline $execute store result score r0 vm_regs run damage $(target) $(amount)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_damage_type:\n"
"    inline $execute store result score r0 vm_regs run damage $(target) $(amount) $(damage_type)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_damage_at:\n"
"    inline $execute store result score r0 vm_regs run damage $(target) $(amount) $(damage_type) at $(loc_x) $(loc_y) $(loc_z)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_damage_by:\n"
"    inline $execute store result score r0 vm_regs run damage $(target) $(amount) $(damage_type) by $(entity)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_damage_by_from:\n"
"    inline $execute store result score r0 vm_regs run damage $(target) $(amount) $(damage_type) by $(entity) from $(cause)\n"
"    ret\n"
);
