/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

/*
 * File-scope command-helper label definitions for 'datapack', split out
 * of bindings/datapack.h so that a user translation unit which
 * #includes that header does NOT re-emit these `export` labels (they are already
 * provided, exactly once, by the LTO-built _ll_libmc.mch that every mcasm
 * program includes). This file is compiled once into the libmc stdlib bundle.
 */

__asm__(
"export _ll_shared:z/libmc_cmd_datapack_enable:\n"
"    inline $execute store result score r0 vm_regs run datapack enable $(name)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_datapack_disable:\n"
"    inline $execute store result score r0 vm_regs run datapack disable $(name)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_datapack_list:\n"
"    inline execute store result score r0 vm_regs run datapack list\n"
"    ret\n"
);
