#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"

typedef enum {
    DEFAULTGAMEMODE_SURVIVAL,
    DEFAULTGAMEMODE_CREATIVE,
    DEFAULTGAMEMODE_ADVENTURE,
    DEFAULTGAMEMODE_SPECTATOR
} DefaultGameMode;

#ifdef __cplusplus
extern "C" {
#endif

static inline int
defaultgamemode(DefaultGameMode mode)
{
    int ret;

    switch (mode) {
        case DEFAULTGAMEMODE_SURVIVAL:
            __asm volatile (
                "inline execute store result score %0 vm_regs run defaultgamemode survival"
                : "=r"(ret)
            );
            return ret;
        case DEFAULTGAMEMODE_CREATIVE:
            __asm volatile (
                "inline execute store result score %0 vm_regs run defaultgamemode creative"
                : "=r"(ret)
            );
            return ret;
        case DEFAULTGAMEMODE_ADVENTURE:
            __asm volatile (
                "inline execute store result score %0 vm_regs run defaultgamemode adventure"
                : "=r"(ret)
            );
            return ret;
        case DEFAULTGAMEMODE_SPECTATOR:
            __asm volatile (
                "inline execute store result score %0 vm_regs run defaultgamemode spectator"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

#ifdef __cplusplus
}
#endif
