#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"

typedef enum {
    DIFFICULTY_PEACEFUL,
    DIFFICULTY_EASY,
    DIFFICULTY_NORMAL,
    DIFFICULTY_HARD
} DifficultyLevel;

#ifdef __cplusplus
extern "C" {
#endif

static inline int
difficulty(DifficultyLevel level)
{
    int ret;

    switch (level) {
        case DIFFICULTY_PEACEFUL:
            __asm volatile (
                "inline $execute store result score %0 vm_regs run difficulty peaceful"
                : "=r"(ret)
            );
            return ret;
        case DIFFICULTY_EASY:
            __asm volatile (
                "inline $execute store result score %0 vm_regs run difficulty easy"
                : "=r"(ret)
            );
            return ret;
        case DIFFICULTY_NORMAL:
            __asm volatile (
                "inline $execute store result score %0 vm_regs run difficulty normal"
                : "=r"(ret)
            );
            return ret;
        case DIFFICULTY_HARD:
            __asm volatile (
                "inline $execute store result score %0 vm_regs run difficulty hard"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

#ifdef __cplusplus
}
#endif
