/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

/*
 * File-scope command-helper label definitions for 'effect', split out
 * of bindings/effect.h so that a user translation unit which
 * #includes that header does NOT re-emit these `export` labels (they are already
 * provided, exactly once, by the LTO-built _ll_libmc.mch that every mcasm
 * program includes). This file is compiled once into the libmc stdlib bundle.
 */

__asm__(
"export _ll_shared:z/libmc_cmd_effect_give:\n"
"    inline $execute store result score r0 vm_regs run effect give $(target) $(effect)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_effect_clear_all:\n"
"    inline $execute store result score r0 vm_regs run effect clear $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_effect_clear:\n"
"    inline $execute store result score r0 vm_regs run effect clear $(target) $(effect)\n"
"    ret\n"
);
