#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_enchant:\n"
"    inline $execute store result score r0 vm_regs run enchant $(target) $(enchantment)\n"
"    ret\n"
);

static inline int
enchant_unsafe(McfStrRef target_ref, McfStrRef enchantment_ref)
{
    int ret;
    int target_slot;
    int enchantment_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    enchantment_slot = McfStrRef_SlotId(enchantment_ref);
    if (target_slot < 0 || enchantment_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", enchantment: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.enchantment set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_enchant with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(enchantment_slot)
    );
    return ret;
}

static inline int
enchant(Target target, const Identifier * enchantment)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef enchantment_ref;
    int target_slot;
    int enchantment_slot;

    target_ref = _Command_RequireTargetRef(target);
    enchantment_ref = _Command_RequireIdentifierRef(enchantment);
    target_slot = McfStrRef_SlotId(target_ref);
    enchantment_slot = McfStrRef_SlotId(enchantment_ref);
    if (target_slot < 0 || enchantment_slot < 0) {
        McfStrRef_Release(enchantment_ref);
        return -1;
    }

    ret = enchant_unsafe(target_ref, enchantment_ref);
    McfStrRef_Release(enchantment_ref);
    return ret;
}

static inline int
enchant_level_unsafe(McfStrRef target_ref, McfStrRef enchantment_ref, int level)
{
    int ret;
    int target_slot;
    int enchantment_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    enchantment_slot = McfStrRef_SlotId(enchantment_ref);
    if (target_slot < 0 || enchantment_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
        "inline $data modify storage std:vm ls0.enchantment set from storage std:vm mcstr.slots[%1].value"
        :
        : "r"(target_slot), "r"(enchantment_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run enchant $(target) $(enchantment) %1"
        : "=r"(ret)
        : "r"(level)
    );
    return ret;
}

static inline int
enchant_level(Target target, const Identifier * enchantment, int level)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef enchantment_ref;
    int target_slot;
    int enchantment_slot;

    target_ref = _Command_RequireTargetRef(target);
    enchantment_ref = _Command_RequireIdentifierRef(enchantment);
    target_slot = McfStrRef_SlotId(target_ref);
    enchantment_slot = McfStrRef_SlotId(enchantment_ref);
    if (target_slot < 0 || enchantment_slot < 0) {
        McfStrRef_Release(enchantment_ref);
        return -1;
    }

    ret = enchant_level_unsafe(target_ref, enchantment_ref, level);
    McfStrRef_Release(enchantment_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
