#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
fillbiome_unsafe(int from_x, int from_y, int from_z, int to_x, int to_y, int to_z, McfStrRef biome_ref)
{
    int ret;
    int biome_slot;

    biome_slot = McfStrRef_SlotId(biome_ref);
    if (biome_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.biome set from storage std:vm mcstr.slots[%0].value"
        :
        : "r"(biome_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run fillbiome %1 %2 %3 %4 %5 %6 $(biome)"
        : "=r"(ret)
        : "r"(from_x), "r"(from_y), "r"(from_z), "r"(to_x), "r"(to_y), "r"(to_z)
    );
    return ret;
}

static inline int
fillbiome(Vec3i from, Vec3i to, const Identifier * biome)
{
    int ret;
    McfStrRef biome_ref;
    int biome_slot;

    biome_ref = _Command_RequireIdentifierRef(biome);
    biome_slot = McfStrRef_SlotId(biome_ref);
    if (biome_slot < 0) {
        McfStrRef_Release(biome_ref);
        return -1;
    }

    ret = fillbiome_unsafe(from.x, from.y, from.z, to.x, to.y, to.z, biome_ref);
    McfStrRef_Release(biome_ref);
    return ret;
}

static inline int
fillbiome_replace_unsafe(int from_x, int from_y, int from_z, int to_x, int to_y, int to_z, McfStrRef biome_ref, McfStrRef filter_ref)
{
    int ret;
    int biome_slot;
    int filter_slot;

    biome_slot = McfStrRef_SlotId(biome_ref);
    filter_slot = McfStrRef_SlotId(filter_ref);
    if (biome_slot < 0 || filter_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.biome set from storage std:vm mcstr.slots[%0].value\n"
        "inline $data modify storage std:vm ls0.filter set from storage std:vm mcstr.slots[%1].value"
        :
        : "r"(biome_slot), "r"(filter_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run fillbiome %1 %2 %3 %4 %5 %6 $(biome) replace $(filter)"
        : "=r"(ret)
        : "r"(from_x), "r"(from_y), "r"(from_z), "r"(to_x), "r"(to_y), "r"(to_z)
    );
    return ret;
}

static inline int
fillbiome_replace(Vec3i from, Vec3i to, const Identifier * biome, const Identifier * filter)
{
    int ret;
    McfStrRef biome_ref;
    McfStrRef filter_ref;
    int biome_slot;
    int filter_slot;

    biome_ref = _Command_RequireIdentifierRef(biome);
    filter_ref = _Command_RequireIdentifierRef(filter);
    biome_slot = McfStrRef_SlotId(biome_ref);
    filter_slot = McfStrRef_SlotId(filter_ref);
    if (biome_slot < 0 || filter_slot < 0) {
        McfStrRef_Release(biome_ref);
        McfStrRef_Release(filter_ref);
        return -1;
    }

    ret = fillbiome_replace_unsafe(from.x, from.y, from.z, to.x, to.y, to.z, biome_ref, filter_ref);
    McfStrRef_Release(biome_ref);
    McfStrRef_Release(filter_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
