#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_forceload_remove_all:\n"
"    inline execute store result score r0 vm_regs run forceload remove all\n"
"    ret\n"
);

static inline int
forceload_add(int x, int z)
{
    int ret;

    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run forceload add %1 %2"
        : "=r"(ret)
        : "r"(x), "r"(z)
    );
    return ret;
}

static inline int
forceload_remove(int x, int z)
{
    int ret;

    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run forceload remove %1 %2"
        : "=r"(ret)
        : "r"(x), "r"(z)
    );
    return ret;
}

static inline int
forceload_remove_all(void)
{
    int ret;

    __asm volatile (
        "inline function _ll_shared:z/libmc_cmd_forceload_remove_all\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
    );
    return ret;
}

#ifdef __cplusplus
}
#endif
