/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

/*
 * File-scope command-helper label definitions for 'gamemode', split out
 * of bindings/gamemode.h so that a user translation unit which
 * #includes that header does NOT re-emit these `export` labels (they are already
 * provided, exactly once, by the LTO-built _ll_libmc.mch that every mcasm
 * program includes). This file is compiled once into the libmc stdlib bundle.
 */

__asm__(
"export _ll_shared:z/gamemode_target_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run gamemode survival $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/gamemode_target_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run gamemode creative $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/gamemode_target_unsafe_exec_2:\n"
"    inline $execute store result score r0 vm_regs run gamemode adventure $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/gamemode_target_unsafe_exec_3:\n"
"    inline $execute store result score r0 vm_regs run gamemode spectator $(target)\n"
"    ret\n"
);
