#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_gamerule_query:\n"
"    inline $execute store result score r0 vm_regs run gamerule $(rule)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_gamerule_set_bool:\n"
"    inline $execute store result score r0 vm_regs run gamerule $(rule) $(value)\n"
"    ret\n"
);

static inline int
gamerule_query_unsafe(McfStrRef rule_ref)
{
    int ret;
    int rule_slot;

    rule_slot = McfStrRef_SlotId(rule_ref);
    if (rule_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{rule: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.rule set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_gamerule_query with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(rule_slot)
    );
    return ret;
}

static inline int
gamerule_query(String rule)
{
    McfStrRef rule_ref;
    int rule_slot;

    rule_ref = _Command_RequireStringRef(rule);
    rule_slot = McfStrRef_SlotId(rule_ref);
    if (rule_slot < 0) {
        return -1;
    }
    return gamerule_query_unsafe(rule_ref);
}

static inline int
gamerule_set_bool_unsafe(McfStrRef rule_ref, McfStrRef value_ref)
{
    int ret;
    int rule_slot;
    int value_slot;

    rule_slot = McfStrRef_SlotId(rule_ref);
    value_slot = McfStrRef_SlotId(value_ref);
    if (rule_slot < 0 || value_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{rule: \"\", value: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.rule set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.value set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_gamerule_set_bool with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(rule_slot), "r"(value_slot)
    );
    return ret;
}

static inline int
gamerule_set_bool(String rule, int value)
{
    McfStrRef rule_ref;
    McfStrRef value_ref;
    int rule_slot;
    int value_slot;

    rule_ref = _Command_RequireStringRef(rule);
    value_ref = _Command_BoolRef(value);
    rule_slot = McfStrRef_SlotId(rule_ref);
    value_slot = McfStrRef_SlotId(value_ref);
    if (rule_slot < 0 || value_slot < 0) {
        return -1;
    }
    return gamerule_set_bool_unsafe(rule_ref, value_ref);
}

static inline int
gamerule_set_int_unsafe(McfStrRef rule_ref, int value)
{
    int ret;
    int rule_slot;

    rule_slot = McfStrRef_SlotId(rule_ref);
    if (rule_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.rule set from storage std:vm mcstr.slots[%0].value"
        :
        : "r"(rule_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run gamerule $(rule) %1"
        : "=r"(ret)
        : "r"(value)
    );
    return ret;
}

static inline int
gamerule_set_int(String rule, int value)
{
    McfStrRef rule_ref;
    int rule_slot;

    rule_ref = _Command_RequireStringRef(rule);
    rule_slot = McfStrRef_SlotId(rule_ref);
    if (rule_slot < 0) {
        return -1;
    }
    return gamerule_set_int_unsafe(rule_ref, value);
}

#ifdef __cplusplus
}
#endif
