#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_give:\n"
"    inline $execute store result score r0 vm_regs run give $(target) $(item)\n"
"    ret\n"
);

static inline int
give_unsafe(McfStrRef target_ref, McfStrRef item_ref)
{
    int ret;
    int target_slot;
    int item_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    item_slot = McfStrRef_SlotId(item_ref);
    if (target_slot < 0 || item_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", item: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.item set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_give with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(item_slot)
    );
    return ret;
}

static inline int
give(Target target, const Identifier * item)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef item_ref;
    int target_slot;
    int item_slot;

    target_ref = _Command_RequireTargetRef(target);
    item_ref = _Command_RequireIdentifierRef(item);
    target_slot = McfStrRef_SlotId(target_ref);
    item_slot = McfStrRef_SlotId(item_ref);
    if (target_slot < 0 || item_slot < 0) {
        McfStrRef_Release(item_ref);
        return -1;
    }

    ret = give_unsafe(target_ref, item_ref);
    McfStrRef_Release(item_ref);
    return ret;
}

static inline int
give_count_unsafe(McfStrRef target_ref, McfStrRef item_ref, int count)
{
    int ret;
    int target_slot;
    int item_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    item_slot = McfStrRef_SlotId(item_ref);
    if (target_slot < 0 || item_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
        "inline $data modify storage std:vm ls0.item set from storage std:vm mcstr.slots[%1].value"
        :
        : "r"(target_slot), "r"(item_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run give $(target) $(item) %1"
        : "=r"(ret)
        : "r"(count)
    );
    return ret;
}

static inline int
give_count(Target target, const Identifier * item, int count)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef item_ref;
    int target_slot;
    int item_slot;

    target_ref = _Command_RequireTargetRef(target);
    item_ref = _Command_RequireIdentifierRef(item);
    target_slot = McfStrRef_SlotId(target_ref);
    item_slot = McfStrRef_SlotId(item_ref);
    if (target_slot < 0 || item_slot < 0) {
        McfStrRef_Release(item_ref);
        return -1;
    }

    ret = give_count_unsafe(target_ref, item_ref, count);
    McfStrRef_Release(item_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
