/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

/*
 * File-scope command-helper label definitions for 'locate', split out
 * of bindings/locate.h so that a user translation unit which
 * #includes that header does NOT re-emit these `export` labels (they are already
 * provided, exactly once, by the LTO-built _ll_libmc.mch that every mcasm
 * program includes). This file is compiled once into the libmc stdlib bundle.
 */

__asm__(
"export _ll_shared:z/libmc_cmd_locate_structure:\n"
"    inline $execute store result score r0 vm_regs run locate structure $(structure)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_locate_biome:\n"
"    inline $execute store result score r0 vm_regs run locate biome $(biome)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_locate_poi:\n"
"    inline $execute store result score r0 vm_regs run locate poi $(poi)\n"
"    ret\n"
);
