/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

/*
 * File-scope command-helper label definitions for 'particle', split out
 * of bindings/particle.h so that a user translation unit which
 * #includes that header does NOT re-emit these `export` labels (they are already
 * provided, exactly once, by the LTO-built _ll_libmc.mch that every mcasm
 * program includes). This file is compiled once into the libmc stdlib bundle.
 */

__asm__(
"export _ll_shared:z/libmc_cmd_particle:\n"
"    inline $execute store result score r0 vm_regs run particle $(name)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_particle_at:\n"
"    inline $execute store result score r0 vm_regs run particle $(name) $(x) $(y) $(z)\n"
"    ret\n"
);
