#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"

typedef enum {
    SOUND_SOURCE_MASTER,
    SOUND_SOURCE_MUSIC,
    SOUND_SOURCE_RECORD,
    SOUND_SOURCE_WEATHER,
    SOUND_SOURCE_BLOCK,
    SOUND_SOURCE_HOSTILE,
    SOUND_SOURCE_NEUTRAL,
    SOUND_SOURCE_PLAYER,
    SOUND_SOURCE_AMBIENT,
    SOUND_SOURCE_VOICE
} SoundSource;

#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/playsound_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) master $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) music $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_unsafe_exec_2:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) record $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_unsafe_exec_3:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) weather $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_unsafe_exec_4:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) block $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_unsafe_exec_5:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) hostile $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_unsafe_exec_6:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) neutral $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_unsafe_exec_7:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) player $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_unsafe_exec_8:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) ambient $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_unsafe_exec_9:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) voice $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_at_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) master $(target) $(x) $(y) $(z)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_at_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) music $(target) $(x) $(y) $(z)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_at_unsafe_exec_2:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) record $(target) $(x) $(y) $(z)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_at_unsafe_exec_3:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) weather $(target) $(x) $(y) $(z)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_at_unsafe_exec_4:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) block $(target) $(x) $(y) $(z)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_at_unsafe_exec_5:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) hostile $(target) $(x) $(y) $(z)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_at_unsafe_exec_6:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) neutral $(target) $(x) $(y) $(z)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_at_unsafe_exec_7:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) player $(target) $(x) $(y) $(z)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_at_unsafe_exec_8:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) ambient $(target) $(x) $(y) $(z)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_at_unsafe_exec_9:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) voice $(target) $(x) $(y) $(z)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_full_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) master $(target) $(x) $(y) $(z) $(volume) $(pitch)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_full_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) music $(target) $(x) $(y) $(z) $(volume) $(pitch)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_full_unsafe_exec_2:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) record $(target) $(x) $(y) $(z) $(volume) $(pitch)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_full_unsafe_exec_3:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) weather $(target) $(x) $(y) $(z) $(volume) $(pitch)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_full_unsafe_exec_4:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) block $(target) $(x) $(y) $(z) $(volume) $(pitch)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_full_unsafe_exec_5:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) hostile $(target) $(x) $(y) $(z) $(volume) $(pitch)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_full_unsafe_exec_6:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) neutral $(target) $(x) $(y) $(z) $(volume) $(pitch)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_full_unsafe_exec_7:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) player $(target) $(x) $(y) $(z) $(volume) $(pitch)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_full_unsafe_exec_8:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) ambient $(target) $(x) $(y) $(z) $(volume) $(pitch)\n"
"    ret\n"
"\n"
"export _ll_shared:z/playsound_full_unsafe_exec_9:\n"
"    inline $execute store result score r0 vm_regs run playsound $(sound) voice $(target) $(x) $(y) $(z) $(volume) $(pitch)\n"
"    ret\n"
);

static inline int
playsound_unsafe(McfStrRef sound_ref, SoundSource source, McfStrRef target_ref)
{
    int ret;
    int sound_slot;
    int target_slot;

    sound_slot = McfStrRef_SlotId(sound_ref);
    target_slot = McfStrRef_SlotId(target_ref);
    if (sound_slot < 0 || target_slot < 0) {
        return -1;
    }

    switch (source) {
        case SOUND_SOURCE_MASTER:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(sound_slot), "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_unsafe_exec_0 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_MUSIC:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(sound_slot), "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_unsafe_exec_1 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_RECORD:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(sound_slot), "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_unsafe_exec_2 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_WEATHER:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(sound_slot), "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_unsafe_exec_3 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_BLOCK:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(sound_slot), "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_unsafe_exec_4 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_HOSTILE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(sound_slot), "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_unsafe_exec_5 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_NEUTRAL:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(sound_slot), "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_unsafe_exec_6 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_PLAYER:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(sound_slot), "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_unsafe_exec_7 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_AMBIENT:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(sound_slot), "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_unsafe_exec_8 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_VOICE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(sound_slot), "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_unsafe_exec_9 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
playsound(const Identifier * sound, SoundSource source, Target target)
{
    int ret;
    McfStrRef sound_ref;
    McfStrRef target_ref;
    int sound_slot;
    int target_slot;

    sound_ref = _Command_RequireIdentifierRef(sound);
    target_ref = _Command_RequireTargetRef(target);
    sound_slot = McfStrRef_SlotId(sound_ref);
    target_slot = McfStrRef_SlotId(target_ref);
    if (sound_slot < 0 || target_slot < 0) {
        McfStrRef_Release(sound_ref);
        return -1;
    }

    ret = playsound_unsafe(sound_ref, source, target_ref);
    McfStrRef_Release(sound_ref);
    return ret;
}

static inline int
playsound_at_unsafe(McfStrRef sound_ref, SoundSource source, McfStrRef target_ref, McfStrRef x_ref, McfStrRef y_ref, McfStrRef z_ref)
{
    int ret;
    int sound_slot;
    int target_slot;
    int x_slot;
    int y_slot;
    int z_slot;

    sound_slot = McfStrRef_SlotId(sound_ref);
    target_slot = McfStrRef_SlotId(target_ref);
    x_slot = McfStrRef_SlotId(x_ref);
    y_slot = McfStrRef_SlotId(y_ref);
    z_slot = McfStrRef_SlotId(z_ref);
    if (sound_slot < 0 || target_slot < 0 || x_slot < 0 || y_slot < 0 || z_slot < 0) {
        return -1;
    }

    switch (source) {
        case SOUND_SOURCE_MASTER:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_at_unsafe_exec_0 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_MUSIC:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_at_unsafe_exec_1 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_RECORD:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_at_unsafe_exec_2 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_WEATHER:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_at_unsafe_exec_3 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_BLOCK:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_at_unsafe_exec_4 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_HOSTILE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_at_unsafe_exec_5 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_NEUTRAL:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_at_unsafe_exec_6 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_PLAYER:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_at_unsafe_exec_7 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_AMBIENT:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_at_unsafe_exec_8 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_VOICE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_at_unsafe_exec_9 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
playsound_at(const Identifier * sound, SoundSource source, Target target, Vec3d pos)
{
    int ret;
    McfStrRef sound_ref;
    McfStrRef target_ref;
    McfStrRef x_ref;
    McfStrRef y_ref;
    McfStrRef z_ref;
    int sound_slot;
    int target_slot;
    int x_slot;
    int y_slot;
    int z_slot;

    sound_ref = _Command_RequireIdentifierRef(sound);
    target_ref = _Command_RequireTargetRef(target);
    x_ref = _Command_FormatDoubleRef(pos.x);
    y_ref = _Command_FormatDoubleRef(pos.y);
    z_ref = _Command_FormatDoubleRef(pos.z);
    sound_slot = McfStrRef_SlotId(sound_ref);
    target_slot = McfStrRef_SlotId(target_ref);
    x_slot = McfStrRef_SlotId(x_ref);
    y_slot = McfStrRef_SlotId(y_ref);
    z_slot = McfStrRef_SlotId(z_ref);
    if (sound_slot < 0 || target_slot < 0 || x_slot < 0 || y_slot < 0 || z_slot < 0) {
        McfStrRef_Release(sound_ref);
        McfStrRef_Release(x_ref);
        McfStrRef_Release(y_ref);
        McfStrRef_Release(z_ref);
        return -1;
    }

    ret = playsound_at_unsafe(sound_ref, source, target_ref, x_ref, y_ref, z_ref);
    McfStrRef_Release(sound_ref);
    McfStrRef_Release(x_ref);
    McfStrRef_Release(y_ref);
    McfStrRef_Release(z_ref);
    return ret;
}

static inline int
playsound_full_unsafe(McfStrRef sound_ref, SoundSource source, McfStrRef target_ref, McfStrRef x_ref, McfStrRef y_ref, McfStrRef z_ref, McfStrRef volume_ref, McfStrRef pitch_ref)
{
    int ret;
    int sound_slot;
    int target_slot;
    int x_slot;
    int y_slot;
    int z_slot;
    int volume_slot;
    int pitch_slot;

    sound_slot = McfStrRef_SlotId(sound_ref);
    target_slot = McfStrRef_SlotId(target_ref);
    x_slot = McfStrRef_SlotId(x_ref);
    y_slot = McfStrRef_SlotId(y_ref);
    z_slot = McfStrRef_SlotId(z_ref);
    volume_slot = McfStrRef_SlotId(volume_ref);
    pitch_slot = McfStrRef_SlotId(pitch_ref);
    if (sound_slot < 0 || target_slot < 0 || x_slot < 0 || y_slot < 0 || z_slot < 0 || volume_slot < 0 || pitch_slot < 0) {
        return -1;
    }

    switch (source) {
        case SOUND_SOURCE_MASTER:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value\n"
                "inline $data modify storage std:vm ls0.volume set from storage std:vm mcstr.slots[%5].value\n"
                "inline $data modify storage std:vm ls0.pitch set from storage std:vm mcstr.slots[%6].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot), "r"(volume_slot), "r"(pitch_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_full_unsafe_exec_0 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_MUSIC:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value\n"
                "inline $data modify storage std:vm ls0.volume set from storage std:vm mcstr.slots[%5].value\n"
                "inline $data modify storage std:vm ls0.pitch set from storage std:vm mcstr.slots[%6].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot), "r"(volume_slot), "r"(pitch_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_full_unsafe_exec_1 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_RECORD:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value\n"
                "inline $data modify storage std:vm ls0.volume set from storage std:vm mcstr.slots[%5].value\n"
                "inline $data modify storage std:vm ls0.pitch set from storage std:vm mcstr.slots[%6].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot), "r"(volume_slot), "r"(pitch_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_full_unsafe_exec_2 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_WEATHER:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value\n"
                "inline $data modify storage std:vm ls0.volume set from storage std:vm mcstr.slots[%5].value\n"
                "inline $data modify storage std:vm ls0.pitch set from storage std:vm mcstr.slots[%6].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot), "r"(volume_slot), "r"(pitch_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_full_unsafe_exec_3 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_BLOCK:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value\n"
                "inline $data modify storage std:vm ls0.volume set from storage std:vm mcstr.slots[%5].value\n"
                "inline $data modify storage std:vm ls0.pitch set from storage std:vm mcstr.slots[%6].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot), "r"(volume_slot), "r"(pitch_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_full_unsafe_exec_4 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_HOSTILE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value\n"
                "inline $data modify storage std:vm ls0.volume set from storage std:vm mcstr.slots[%5].value\n"
                "inline $data modify storage std:vm ls0.pitch set from storage std:vm mcstr.slots[%6].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot), "r"(volume_slot), "r"(pitch_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_full_unsafe_exec_5 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_NEUTRAL:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value\n"
                "inline $data modify storage std:vm ls0.volume set from storage std:vm mcstr.slots[%5].value\n"
                "inline $data modify storage std:vm ls0.pitch set from storage std:vm mcstr.slots[%6].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot), "r"(volume_slot), "r"(pitch_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_full_unsafe_exec_6 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_PLAYER:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value\n"
                "inline $data modify storage std:vm ls0.volume set from storage std:vm mcstr.slots[%5].value\n"
                "inline $data modify storage std:vm ls0.pitch set from storage std:vm mcstr.slots[%6].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot), "r"(volume_slot), "r"(pitch_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_full_unsafe_exec_7 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_AMBIENT:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value\n"
                "inline $data modify storage std:vm ls0.volume set from storage std:vm mcstr.slots[%5].value\n"
                "inline $data modify storage std:vm ls0.pitch set from storage std:vm mcstr.slots[%6].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot), "r"(volume_slot), "r"(pitch_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_full_unsafe_exec_8 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SOUND_SOURCE_VOICE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.x set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.y set from storage std:vm mcstr.slots[%3].value\n"
                "inline $data modify storage std:vm ls0.z set from storage std:vm mcstr.slots[%4].value\n"
                "inline $data modify storage std:vm ls0.volume set from storage std:vm mcstr.slots[%5].value\n"
                "inline $data modify storage std:vm ls0.pitch set from storage std:vm mcstr.slots[%6].value"
                :
                : "r"(sound_slot), "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot), "r"(volume_slot), "r"(pitch_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/playsound_full_unsafe_exec_9 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
playsound_full(const Identifier * sound, SoundSource source, Target target, Vec3d pos, float volume, float pitch)
{
    int ret;
    McfStrRef sound_ref;
    McfStrRef target_ref;
    McfStrRef x_ref;
    McfStrRef y_ref;
    McfStrRef z_ref;
    McfStrRef volume_ref;
    McfStrRef pitch_ref;
    int sound_slot;
    int target_slot;
    int x_slot;
    int y_slot;
    int z_slot;
    int volume_slot;
    int pitch_slot;

    sound_ref = _Command_RequireIdentifierRef(sound);
    target_ref = _Command_RequireTargetRef(target);
    x_ref = _Command_FormatDoubleRef(pos.x);
    y_ref = _Command_FormatDoubleRef(pos.y);
    z_ref = _Command_FormatDoubleRef(pos.z);
    volume_ref = _Command_FormatFloatRef(volume);
    pitch_ref = _Command_FormatFloatRef(pitch);
    sound_slot = McfStrRef_SlotId(sound_ref);
    target_slot = McfStrRef_SlotId(target_ref);
    x_slot = McfStrRef_SlotId(x_ref);
    y_slot = McfStrRef_SlotId(y_ref);
    z_slot = McfStrRef_SlotId(z_ref);
    volume_slot = McfStrRef_SlotId(volume_ref);
    pitch_slot = McfStrRef_SlotId(pitch_ref);
    if (sound_slot < 0 || target_slot < 0 || x_slot < 0 || y_slot < 0 || z_slot < 0 || volume_slot < 0 || pitch_slot < 0) {
        McfStrRef_Release(sound_ref);
        McfStrRef_Release(x_ref);
        McfStrRef_Release(y_ref);
        McfStrRef_Release(z_ref);
        McfStrRef_Release(volume_ref);
        McfStrRef_Release(pitch_ref);
        return -1;
    }

    ret = playsound_full_unsafe(sound_ref, source, target_ref, x_ref, y_ref, z_ref, volume_ref, pitch_ref);
    McfStrRef_Release(sound_ref);
    McfStrRef_Release(x_ref);
    McfStrRef_Release(y_ref);
    McfStrRef_Release(z_ref);
    McfStrRef_Release(volume_ref);
    McfStrRef_Release(pitch_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
