/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

/*
 * File-scope command-helper label definitions for 'random', split out
 * of bindings/random.h so that a user translation unit which
 * #includes that header does NOT re-emit these `export` labels (they are already
 * provided, exactly once, by the LTO-built _ll_libmc.mch that every mcasm
 * program includes). This file is compiled once into the libmc stdlib bundle.
 */

__asm__(
"export _ll_shared:z/libmc_cmd_random_value:\n"
"    inline $execute store result score r0 vm_regs run random value $(range)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_random_value_seq:\n"
"    inline $execute store result score r0 vm_regs run random value $(range) $(sequence)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_random_roll:\n"
"    inline $execute store result score r0 vm_regs run random roll $(range)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_random_roll_seq:\n"
"    inline $execute store result score r0 vm_regs run random roll $(range) $(sequence)\n"
"    ret\n"
);
