#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_recipe_give:\n"
"    inline $execute store result score r0 vm_regs run recipe give $(target) $(recipe)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_recipe_take:\n"
"    inline $execute store result score r0 vm_regs run recipe take $(target) $(recipe)\n"
"    ret\n"
);

static inline int
recipe_give_unsafe(McfStrRef target_ref, McfStrRef recipe_ref)
{
    int ret;
    int target_slot;
    int recipe_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    recipe_slot = McfStrRef_SlotId(recipe_ref);
    if (target_slot < 0 || recipe_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", recipe: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.recipe set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_recipe_give with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(recipe_slot)
    );
    return ret;
}

static inline int
recipe_give(Target target, const Identifier * recipe)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef recipe_ref;
    int target_slot;
    int recipe_slot;

    target_ref = _Command_RequireTargetRef(target);
    recipe_ref = _Command_RequireIdentifierRef(recipe);
    target_slot = McfStrRef_SlotId(target_ref);
    recipe_slot = McfStrRef_SlotId(recipe_ref);
    if (target_slot < 0 || recipe_slot < 0) {
        McfStrRef_Release(recipe_ref);
        return -1;
    }

    ret = recipe_give_unsafe(target_ref, recipe_ref);
    McfStrRef_Release(recipe_ref);
    return ret;
}

static inline int
recipe_take_unsafe(McfStrRef target_ref, McfStrRef recipe_ref)
{
    int ret;
    int target_slot;
    int recipe_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    recipe_slot = McfStrRef_SlotId(recipe_ref);
    if (target_slot < 0 || recipe_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", recipe: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.recipe set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_recipe_take with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(recipe_slot)
    );
    return ret;
}

static inline int
recipe_take(Target target, const Identifier * recipe)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef recipe_ref;
    int target_slot;
    int recipe_slot;

    target_ref = _Command_RequireTargetRef(target);
    recipe_ref = _Command_RequireIdentifierRef(recipe);
    target_slot = McfStrRef_SlotId(target_ref);
    recipe_slot = McfStrRef_SlotId(recipe_ref);
    if (target_slot < 0 || recipe_slot < 0) {
        McfStrRef_Release(recipe_ref);
        return -1;
    }

    ret = recipe_take_unsafe(target_ref, recipe_ref);
    McfStrRef_Release(recipe_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
