#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_say:\n"
"    inline $execute store result score r0 vm_regs run say $(text)\n"
"    ret\n"
);

static inline int
say_unsafe(McfStrRef text_ref)
{
    int ret;
    int slot_id;

    slot_id = McfStrRef_SlotId(text_ref);
    if (slot_id < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{text: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.text set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_say with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(slot_id)
    );
    return ret;
}

static inline int
say(String text)
{
    McfStrRef text_mcf;

    text_mcf = _Command_RequireStringRef(text);
    if (McfStrRef_SlotId(text_mcf) < 0) {
        return -1;
    }
    return say_unsafe(text_mcf);
}

#ifdef __cplusplus
}
#endif
