#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"

typedef enum {
    SCORE_OP_ASSIGN,
    SCORE_OP_ADD,
    SCORE_OP_SUB,
    SCORE_OP_MUL,
    SCORE_OP_DIV,
    SCORE_OP_MOD,
    SCORE_OP_MIN,
    SCORE_OP_MAX,
    SCORE_OP_SWAP
} ScoreOp;

typedef enum {
    OBJECTIVE_RENDER_HEARTS,
    OBJECTIVE_RENDER_INTEGER
} ObjectiveRenderType;

#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_scoreboard_objectives_list:\n"
"    inline execute store result score r0 vm_regs run scoreboard objectives list\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_scoreboard_objectives_add:\n"
"    inline $execute store result score r0 vm_regs run scoreboard objectives add $(objective) $(criteria)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_scoreboard_objectives_remove:\n"
"    inline $execute store result score r0 vm_regs run scoreboard objectives remove $(objective)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_scoreboard_objectives_setdisplay:\n"
"    inline $execute store result score r0 vm_regs run scoreboard objectives setdisplay $(slot) $(objective)\n"
"    ret\n"
"\n"
"export _ll_shared:z/scoreboard_objectives_modify_rendertype_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run scoreboard objectives modify $(objective) rendertype hearts\n"
"    ret\n"
"\n"
"export _ll_shared:z/scoreboard_objectives_modify_rendertype_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run scoreboard objectives modify $(objective) rendertype integer\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_scoreboard_players_get:\n"
"    inline $execute store result score r0 vm_regs run scoreboard players get $(target) $(objective)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_scoreboard_players_reset:\n"
"    inline $execute store result score r0 vm_regs run scoreboard players reset $(target) $(objective)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_scoreboard_players_enable:\n"
"    inline $execute store result score r0 vm_regs run scoreboard players enable $(target) $(objective)\n"
"    ret\n"
"\n"
"export _ll_shared:z/scoreboard_players_operation_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run scoreboard players operation $(target) $(objective) = $(source) $(source_objective)\n"
"    ret\n"
"\n"
"export _ll_shared:z/scoreboard_players_operation_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run scoreboard players operation $(target) $(objective) += $(source) $(source_objective)\n"
"    ret\n"
"\n"
"export _ll_shared:z/scoreboard_players_operation_unsafe_exec_2:\n"
"    inline $execute store result score r0 vm_regs run scoreboard players operation $(target) $(objective) -= $(source) $(source_objective)\n"
"    ret\n"
"\n"
"export _ll_shared:z/scoreboard_players_operation_unsafe_exec_3:\n"
"    inline $execute store result score r0 vm_regs run scoreboard players operation $(target) $(objective) *= $(source) $(source_objective)\n"
"    ret\n"
"\n"
"export _ll_shared:z/scoreboard_players_operation_unsafe_exec_4:\n"
"    inline $execute store result score r0 vm_regs run scoreboard players operation $(target) $(objective) /= $(source) $(source_objective)\n"
"    ret\n"
"\n"
"export _ll_shared:z/scoreboard_players_operation_unsafe_exec_5:\n"
"    inline $execute store result score r0 vm_regs run scoreboard players operation $(target) $(objective) %= $(source) $(source_objective)\n"
"    ret\n"
"\n"
"export _ll_shared:z/scoreboard_players_operation_unsafe_exec_6:\n"
"    inline $execute store result score r0 vm_regs run scoreboard players operation $(target) $(objective) < $(source) $(source_objective)\n"
"    ret\n"
"\n"
"export _ll_shared:z/scoreboard_players_operation_unsafe_exec_7:\n"
"    inline $execute store result score r0 vm_regs run scoreboard players operation $(target) $(objective) > $(source) $(source_objective)\n"
"    ret\n"
"\n"
"export _ll_shared:z/scoreboard_players_operation_unsafe_exec_8:\n"
"    inline $execute store result score r0 vm_regs run scoreboard players operation $(target) $(objective) >< $(source) $(source_objective)\n"
"    ret\n"
);

static inline int
scoreboard_objectives_list(void)
{
    int ret;

    __asm volatile (
        "inline function _ll_shared:z/libmc_cmd_scoreboard_objectives_list\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
    );
    return ret;
}

static inline int
scoreboard_objectives_add_unsafe(McfStrRef objective_ref, McfStrRef criteria_ref)
{
    int ret;
    int objective_slot;
    int criteria_slot;

    objective_slot = McfStrRef_SlotId(objective_ref);
    criteria_slot = McfStrRef_SlotId(criteria_ref);
    if (objective_slot < 0 || criteria_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{objective: \"\", criteria: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.objective set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.criteria set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_scoreboard_objectives_add with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(objective_slot), "r"(criteria_slot)
    );
    return ret;
}

static inline int
scoreboard_objectives_add(const char * objective, const char * criteria)
{
    int ret;
    McfStrRef objective_ref;
    McfStrRef criteria_ref;
    int objective_slot;
    int criteria_slot;

    objective_ref = _Command_RequireCStringRef(objective);
    criteria_ref = _Command_RequireCStringRef(criteria);
    objective_slot = McfStrRef_SlotId(objective_ref);
    criteria_slot = McfStrRef_SlotId(criteria_ref);
    if (objective_slot < 0 || criteria_slot < 0) {
        McfStrRef_Release(objective_ref);
        McfStrRef_Release(criteria_ref);
        return -1;
    }

    ret = scoreboard_objectives_add_unsafe(objective_ref, criteria_ref);
    McfStrRef_Release(objective_ref);
    McfStrRef_Release(criteria_ref);
    return ret;
}

static inline int
scoreboard_objectives_remove_unsafe(McfStrRef objective_ref)
{
    int ret;
    int objective_slot;

    objective_slot = McfStrRef_SlotId(objective_ref);
    if (objective_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{objective: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.objective set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_scoreboard_objectives_remove with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(objective_slot)
    );
    return ret;
}

static inline int
scoreboard_objectives_remove(const char * objective)
{
    int ret;
    McfStrRef objective_ref;
    int objective_slot;

    objective_ref = _Command_RequireCStringRef(objective);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (objective_slot < 0) {
        McfStrRef_Release(objective_ref);
        return -1;
    }

    ret = scoreboard_objectives_remove_unsafe(objective_ref);
    McfStrRef_Release(objective_ref);
    return ret;
}

static inline int
scoreboard_objectives_setdisplay_unsafe(McfStrRef slot_ref, McfStrRef objective_ref)
{
    int ret;
    int slot_slot;
    int objective_slot;

    slot_slot = McfStrRef_SlotId(slot_ref);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (slot_slot < 0 || objective_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{slot: \"\", objective: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.slot set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.objective set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_scoreboard_objectives_setdisplay with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(slot_slot), "r"(objective_slot)
    );
    return ret;
}

static inline int
scoreboard_objectives_setdisplay(const char * slot, const char * objective)
{
    int ret;
    McfStrRef slot_ref;
    McfStrRef objective_ref;
    int slot_slot;
    int objective_slot;

    slot_ref = _Command_RequireCStringRef(slot);
    objective_ref = _Command_RequireCStringRef(objective);
    slot_slot = McfStrRef_SlotId(slot_ref);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (slot_slot < 0 || objective_slot < 0) {
        McfStrRef_Release(slot_ref);
        McfStrRef_Release(objective_ref);
        return -1;
    }

    ret = scoreboard_objectives_setdisplay_unsafe(slot_ref, objective_ref);
    McfStrRef_Release(slot_ref);
    McfStrRef_Release(objective_ref);
    return ret;
}

static inline int
scoreboard_objectives_modify_rendertype_unsafe(McfStrRef objective_ref, ObjectiveRenderType rendertype)
{
    int ret;
    int objective_slot;

    objective_slot = McfStrRef_SlotId(objective_ref);
    if (objective_slot < 0) {
        return -1;
    }

    switch (rendertype) {
        case OBJECTIVE_RENDER_HEARTS:
            __asm volatile (
                "inline $data modify storage std:vm ls0.objective set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(objective_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/scoreboard_objectives_modify_rendertype_unsafe_exec_0 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case OBJECTIVE_RENDER_INTEGER:
            __asm volatile (
                "inline $data modify storage std:vm ls0.objective set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(objective_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/scoreboard_objectives_modify_rendertype_unsafe_exec_1 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
scoreboard_objectives_modify_rendertype(const char * objective, ObjectiveRenderType rendertype)
{
    int ret;
    McfStrRef objective_ref;
    int objective_slot;

    objective_ref = _Command_RequireCStringRef(objective);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (objective_slot < 0) {
        McfStrRef_Release(objective_ref);
        return -1;
    }

    ret = scoreboard_objectives_modify_rendertype_unsafe(objective_ref, rendertype);
    McfStrRef_Release(objective_ref);
    return ret;
}

static inline int
scoreboard_players_get_unsafe(McfStrRef target_ref, McfStrRef objective_ref)
{
    int ret;
    int target_slot;
    int objective_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (target_slot < 0 || objective_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", objective: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.objective set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_scoreboard_players_get with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(objective_slot)
    );
    return ret;
}

static inline int
scoreboard_players_get(Target target, const char * objective)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef objective_ref;
    int target_slot;
    int objective_slot;

    target_ref = _Command_RequireTargetRef(target);
    objective_ref = _Command_RequireCStringRef(objective);
    target_slot = McfStrRef_SlotId(target_ref);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (target_slot < 0 || objective_slot < 0) {
        McfStrRef_Release(objective_ref);
        return -1;
    }

    ret = scoreboard_players_get_unsafe(target_ref, objective_ref);
    McfStrRef_Release(objective_ref);
    return ret;
}

static inline int
scoreboard_players_set_unsafe(McfStrRef target_ref, McfStrRef objective_ref, int score)
{
    int ret;
    int target_slot;
    int objective_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (target_slot < 0 || objective_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
        "inline $data modify storage std:vm ls0.objective set from storage std:vm mcstr.slots[%1].value"
        :
        : "r"(target_slot), "r"(objective_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run scoreboard players set $(target) $(objective) %1"
        : "=r"(ret)
        : "r"(score)
    );
    return ret;
}

static inline int
scoreboard_players_set(Target target, const char * objective, int score)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef objective_ref;
    int target_slot;
    int objective_slot;

    target_ref = _Command_RequireTargetRef(target);
    objective_ref = _Command_RequireCStringRef(objective);
    target_slot = McfStrRef_SlotId(target_ref);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (target_slot < 0 || objective_slot < 0) {
        McfStrRef_Release(objective_ref);
        return -1;
    }

    ret = scoreboard_players_set_unsafe(target_ref, objective_ref, score);
    McfStrRef_Release(objective_ref);
    return ret;
}

static inline int
scoreboard_players_add_unsafe(McfStrRef target_ref, McfStrRef objective_ref, int count)
{
    int ret;
    int target_slot;
    int objective_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (target_slot < 0 || objective_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
        "inline $data modify storage std:vm ls0.objective set from storage std:vm mcstr.slots[%1].value"
        :
        : "r"(target_slot), "r"(objective_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run scoreboard players add $(target) $(objective) %1"
        : "=r"(ret)
        : "r"(count)
    );
    return ret;
}

static inline int
scoreboard_players_add(Target target, const char * objective, int count)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef objective_ref;
    int target_slot;
    int objective_slot;

    target_ref = _Command_RequireTargetRef(target);
    objective_ref = _Command_RequireCStringRef(objective);
    target_slot = McfStrRef_SlotId(target_ref);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (target_slot < 0 || objective_slot < 0) {
        McfStrRef_Release(objective_ref);
        return -1;
    }

    ret = scoreboard_players_add_unsafe(target_ref, objective_ref, count);
    McfStrRef_Release(objective_ref);
    return ret;
}

static inline int
scoreboard_players_remove_unsafe(McfStrRef target_ref, McfStrRef objective_ref, int count)
{
    int ret;
    int target_slot;
    int objective_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (target_slot < 0 || objective_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
        "inline $data modify storage std:vm ls0.objective set from storage std:vm mcstr.slots[%1].value"
        :
        : "r"(target_slot), "r"(objective_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run scoreboard players remove $(target) $(objective) %1"
        : "=r"(ret)
        : "r"(count)
    );
    return ret;
}

static inline int
scoreboard_players_remove(Target target, const char * objective, int count)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef objective_ref;
    int target_slot;
    int objective_slot;

    target_ref = _Command_RequireTargetRef(target);
    objective_ref = _Command_RequireCStringRef(objective);
    target_slot = McfStrRef_SlotId(target_ref);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (target_slot < 0 || objective_slot < 0) {
        McfStrRef_Release(objective_ref);
        return -1;
    }

    ret = scoreboard_players_remove_unsafe(target_ref, objective_ref, count);
    McfStrRef_Release(objective_ref);
    return ret;
}

static inline int
scoreboard_players_reset_unsafe(McfStrRef target_ref, McfStrRef objective_ref)
{
    int ret;
    int target_slot;
    int objective_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (target_slot < 0 || objective_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", objective: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.objective set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_scoreboard_players_reset with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(objective_slot)
    );
    return ret;
}

static inline int
scoreboard_players_reset(Target target, const char * objective)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef objective_ref;
    int target_slot;
    int objective_slot;

    target_ref = _Command_RequireTargetRef(target);
    objective_ref = _Command_RequireCStringRef(objective);
    target_slot = McfStrRef_SlotId(target_ref);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (target_slot < 0 || objective_slot < 0) {
        McfStrRef_Release(objective_ref);
        return -1;
    }

    ret = scoreboard_players_reset_unsafe(target_ref, objective_ref);
    McfStrRef_Release(objective_ref);
    return ret;
}

static inline int
scoreboard_players_enable_unsafe(McfStrRef target_ref, McfStrRef objective_ref)
{
    int ret;
    int target_slot;
    int objective_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (target_slot < 0 || objective_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", objective: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.objective set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_scoreboard_players_enable with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(objective_slot)
    );
    return ret;
}

static inline int
scoreboard_players_enable(Target target, const char * objective)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef objective_ref;
    int target_slot;
    int objective_slot;

    target_ref = _Command_RequireTargetRef(target);
    objective_ref = _Command_RequireCStringRef(objective);
    target_slot = McfStrRef_SlotId(target_ref);
    objective_slot = McfStrRef_SlotId(objective_ref);
    if (target_slot < 0 || objective_slot < 0) {
        McfStrRef_Release(objective_ref);
        return -1;
    }

    ret = scoreboard_players_enable_unsafe(target_ref, objective_ref);
    McfStrRef_Release(objective_ref);
    return ret;
}

static inline int
scoreboard_players_operation_unsafe(McfStrRef target_ref, McfStrRef objective_ref, ScoreOp operation, McfStrRef source_ref, McfStrRef source_objective_ref)
{
    int ret;
    int target_slot;
    int objective_slot;
    int source_slot;
    int source_objective_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    objective_slot = McfStrRef_SlotId(objective_ref);
    source_slot = McfStrRef_SlotId(source_ref);
    source_objective_slot = McfStrRef_SlotId(source_objective_ref);
    if (target_slot < 0 || objective_slot < 0 || source_slot < 0 || source_objective_slot < 0) {
        return -1;
    }

    switch (operation) {
        case SCORE_OP_ASSIGN:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.objective set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.source set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.source_objective set from storage std:vm mcstr.slots[%3].value"
                :
                : "r"(target_slot), "r"(objective_slot), "r"(source_slot), "r"(source_objective_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/scoreboard_players_operation_unsafe_exec_0 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SCORE_OP_ADD:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.objective set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.source set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.source_objective set from storage std:vm mcstr.slots[%3].value"
                :
                : "r"(target_slot), "r"(objective_slot), "r"(source_slot), "r"(source_objective_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/scoreboard_players_operation_unsafe_exec_1 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SCORE_OP_SUB:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.objective set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.source set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.source_objective set from storage std:vm mcstr.slots[%3].value"
                :
                : "r"(target_slot), "r"(objective_slot), "r"(source_slot), "r"(source_objective_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/scoreboard_players_operation_unsafe_exec_2 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SCORE_OP_MUL:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.objective set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.source set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.source_objective set from storage std:vm mcstr.slots[%3].value"
                :
                : "r"(target_slot), "r"(objective_slot), "r"(source_slot), "r"(source_objective_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/scoreboard_players_operation_unsafe_exec_3 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SCORE_OP_DIV:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.objective set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.source set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.source_objective set from storage std:vm mcstr.slots[%3].value"
                :
                : "r"(target_slot), "r"(objective_slot), "r"(source_slot), "r"(source_objective_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/scoreboard_players_operation_unsafe_exec_4 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SCORE_OP_MOD:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.objective set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.source set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.source_objective set from storage std:vm mcstr.slots[%3].value"
                :
                : "r"(target_slot), "r"(objective_slot), "r"(source_slot), "r"(source_objective_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/scoreboard_players_operation_unsafe_exec_5 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SCORE_OP_MIN:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.objective set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.source set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.source_objective set from storage std:vm mcstr.slots[%3].value"
                :
                : "r"(target_slot), "r"(objective_slot), "r"(source_slot), "r"(source_objective_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/scoreboard_players_operation_unsafe_exec_6 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SCORE_OP_MAX:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.objective set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.source set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.source_objective set from storage std:vm mcstr.slots[%3].value"
                :
                : "r"(target_slot), "r"(objective_slot), "r"(source_slot), "r"(source_objective_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/scoreboard_players_operation_unsafe_exec_7 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case SCORE_OP_SWAP:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.objective set from storage std:vm mcstr.slots[%1].value\n"
                "inline $data modify storage std:vm ls0.source set from storage std:vm mcstr.slots[%2].value\n"
                "inline $data modify storage std:vm ls0.source_objective set from storage std:vm mcstr.slots[%3].value"
                :
                : "r"(target_slot), "r"(objective_slot), "r"(source_slot), "r"(source_objective_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/scoreboard_players_operation_unsafe_exec_8 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
scoreboard_players_operation(Target target, const char * objective, ScoreOp operation, Target source, const char * source_objective)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef objective_ref;
    McfStrRef source_ref;
    McfStrRef source_objective_ref;
    int target_slot;
    int objective_slot;
    int source_slot;
    int source_objective_slot;

    target_ref = _Command_RequireTargetRef(target);
    objective_ref = _Command_RequireCStringRef(objective);
    source_ref = _Command_RequireTargetRef(source);
    source_objective_ref = _Command_RequireCStringRef(source_objective);
    target_slot = McfStrRef_SlotId(target_ref);
    objective_slot = McfStrRef_SlotId(objective_ref);
    source_slot = McfStrRef_SlotId(source_ref);
    source_objective_slot = McfStrRef_SlotId(source_objective_ref);
    if (target_slot < 0 || objective_slot < 0 || source_slot < 0 || source_objective_slot < 0) {
        McfStrRef_Release(objective_ref);
        McfStrRef_Release(source_objective_ref);
        return -1;
    }

    ret = scoreboard_players_operation_unsafe(target_ref, objective_ref, operation, source_ref, source_objective_ref);
    McfStrRef_Release(objective_ref);
    McfStrRef_Release(source_objective_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
