#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_seed:\n"
"    inline execute store result score r0 vm_regs run seed\n"
"    ret\n"
);

static inline int
seed(void)
{
    int ret;

    __asm volatile (
        "inline function _ll_shared:z/libmc_cmd_seed\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
    );
    return ret;
}

#ifdef __cplusplus
}
#endif
