#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"

typedef enum {
    DESTROY,
    KEEP,
    REPLACE
} SetBlockMode;

#ifdef __cplusplus
extern "C" {
#endif

static inline int
setblock_unsafe(int x, int y, int z, McfStrRef block_ref, SetBlockMode mode)
{
    int ret;
    int slot_id;

    slot_id = McfStrRef_SlotId(block_ref);
    if (slot_id < 0) {
        return -1;
    }

    switch (mode) {
        case DESTROY:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(slot_id)
            );
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run setblock %1 %2 %3 $(block) destroy"
                : "=r"(ret)
                : "r"(x), "r"(y), "r"(z)
            );
            return ret;
        case KEEP:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(slot_id)
            );
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run setblock %1 %2 %3 $(block) keep"
                : "=r"(ret)
                : "r"(x), "r"(y), "r"(z)
            );
            return ret;
        case REPLACE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(slot_id)
            );
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run setblock %1 %2 %3 $(block)"
                : "=r"(ret)
                : "r"(x), "r"(y), "r"(z)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
setblock(Vec3i pos, Block block, SetBlockMode mode)
{
    McfStrRef block_name;

    block_name = Block_EnsureMcfName(block);
    if (McfStrRef_SlotId(block_name) < 0) {
        return -1;
    }
    return setblock_unsafe(pos.x, pos.y, pos.z, block_name, mode);
}

#ifdef __cplusplus
}
#endif
