#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"

typedef enum {
    SETBLOCK_DESTROY,
    SETBLOCK_KEEP,
    SETBLOCK_REPLACE
} SetBlockMode;

#ifdef __cplusplus
extern "C" {
#endif

static inline int
setblock_unsafe(int x, int y, int z, McfStrRef block_ref, SetBlockMode mode)
{
    int ret;
    int block_slot;

    block_slot = McfStrRef_SlotId(block_ref);
    if (block_slot < 0) {
        return -1;
    }

    switch (mode) {
        case SETBLOCK_DESTROY:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(block_slot)
            );
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run setblock %1 %2 %3 $(block) destroy"
                : "=r"(ret)
                : "r"(x), "r"(y), "r"(z)
            );
            return ret;
        case SETBLOCK_KEEP:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(block_slot)
            );
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run setblock %1 %2 %3 $(block) keep"
                : "=r"(ret)
                : "r"(x), "r"(y), "r"(z)
            );
            return ret;
        case SETBLOCK_REPLACE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(block_slot)
            );
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run setblock %1 %2 %3 $(block)"
                : "=r"(ret)
                : "r"(x), "r"(y), "r"(z)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
setblock(Vec3i pos, Block block, SetBlockMode mode)
{
    McfStrRef block_ref;
    int block_slot;

    block_ref = Block_EnsureMcfName(block);
    block_slot = McfStrRef_SlotId(block_ref);
    if (block_slot < 0) {
        return -1;
    }
    return setblock_unsafe(pos.x, pos.y, pos.z, block_ref, mode);
}

#ifdef __cplusplus
}
#endif
