#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_setworldspawn:\n"
"    inline $execute store result score r0 vm_regs run setworldspawn\n"
"    ret\n"
);

static inline int
setworldspawn(void)
{
    int ret;

    __asm volatile (
        "inline function _ll_shared:z/libmc_cmd_setworldspawn\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
    );
    return ret;
}

static inline int
setworldspawn_at(Vec3i pos)
{
    int ret;

    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run setworldspawn %1 %2 %3"
        : "=r"(ret)
        : "r"(pos.x), "r"(pos.y), "r"(pos.z)
    );
    return ret;
}

#ifdef __cplusplus
}
#endif
