#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_spectate:\n"
"    inline $execute store result score r0 vm_regs run spectate\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_spectate_target:\n"
"    inline $execute store result score r0 vm_regs run spectate $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_spectate_as:\n"
"    inline $execute store result score r0 vm_regs run spectate $(target) $(player)\n"
"    ret\n"
);

static inline int
spectate(void)
{
    int ret;

    __asm volatile (
        "inline function _ll_shared:z/libmc_cmd_spectate\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
    );
    return ret;
}

static inline int
spectate_target_unsafe(McfStrRef target_ref)
{
    int ret;
    int target_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_spectate_target with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot)
    );
    return ret;
}

static inline int
spectate_target(Target target)
{
    McfStrRef target_ref;
    int target_slot;

    target_ref = _Command_RequireTargetRef(target);
    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }
    return spectate_target_unsafe(target_ref);
}

static inline int
spectate_as_unsafe(McfStrRef target_ref, McfStrRef player_ref)
{
    int ret;
    int target_slot;
    int player_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    player_slot = McfStrRef_SlotId(player_ref);
    if (target_slot < 0 || player_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", player: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.player set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_spectate_as with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(player_slot)
    );
    return ret;
}

static inline int
spectate_as(Target target, Target player)
{
    McfStrRef target_ref;
    McfStrRef player_ref;
    int target_slot;
    int player_slot;

    target_ref = _Command_RequireTargetRef(target);
    player_ref = _Command_RequireTargetRef(player);
    target_slot = McfStrRef_SlotId(target_ref);
    player_slot = McfStrRef_SlotId(player_ref);
    if (target_slot < 0 || player_slot < 0) {
        return -1;
    }
    return spectate_as_unsafe(target_ref, player_ref);
}

#ifdef __cplusplus
}
#endif
