/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

/*
 * File-scope command-helper label definitions for 'spreadplayers', split out
 * of bindings/spreadplayers.h so that a user translation unit which
 * #includes that header does NOT re-emit these `export` labels (they are already
 * provided, exactly once, by the LTO-built _ll_libmc.mch that every mcasm
 * program includes). This file is compiled once into the libmc stdlib bundle.
 */

__asm__(
"export _ll_shared:z/spreadplayers_unsafe_exec_true:\n"
"    inline $execute store result score r0 vm_regs run spreadplayers $(center_x) $(center_z) $(spread_distance) $(max_range) true $(targets)\n"
"    ret\n"
"\n"
"export _ll_shared:z/spreadplayers_unsafe_exec_false:\n"
"    inline $execute store result score r0 vm_regs run spreadplayers $(center_x) $(center_z) $(spread_distance) $(max_range) false $(targets)\n"
"    ret\n"
);
