#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"

typedef enum {
    STOPSOUND_SOURCE_MASTER,
    STOPSOUND_SOURCE_MUSIC,
    STOPSOUND_SOURCE_RECORD,
    STOPSOUND_SOURCE_WEATHER,
    STOPSOUND_SOURCE_BLOCK,
    STOPSOUND_SOURCE_HOSTILE,
    STOPSOUND_SOURCE_NEUTRAL,
    STOPSOUND_SOURCE_PLAYER,
    STOPSOUND_SOURCE_AMBIENT,
    STOPSOUND_SOURCE_VOICE
} StopSoundSource;

#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_stopsound:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target)\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_source_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) master\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_source_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) music\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_source_unsafe_exec_2:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) record\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_source_unsafe_exec_3:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) weather\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_source_unsafe_exec_4:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) block\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_source_unsafe_exec_5:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) hostile\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_source_unsafe_exec_6:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) neutral\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_source_unsafe_exec_7:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) player\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_source_unsafe_exec_8:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) ambient\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_source_unsafe_exec_9:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) voice\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_sound_unsafe_exec_0:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) master $(sound)\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_sound_unsafe_exec_1:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) music $(sound)\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_sound_unsafe_exec_2:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) record $(sound)\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_sound_unsafe_exec_3:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) weather $(sound)\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_sound_unsafe_exec_4:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) block $(sound)\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_sound_unsafe_exec_5:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) hostile $(sound)\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_sound_unsafe_exec_6:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) neutral $(sound)\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_sound_unsafe_exec_7:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) player $(sound)\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_sound_unsafe_exec_8:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) ambient $(sound)\n"
"    ret\n"
"\n"
"export _ll_shared:z/stopsound_sound_unsafe_exec_9:\n"
"    inline $execute store result score r0 vm_regs run stopsound $(target) voice $(sound)\n"
"    ret\n"
);

static inline int
stopsound_unsafe(McfStrRef target_ref)
{
    int ret;
    int target_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_stopsound with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot)
    );
    return ret;
}

static inline int
stopsound(Target target)
{
    McfStrRef target_ref;
    int target_slot;

    target_ref = _Command_RequireTargetRef(target);
    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }
    return stopsound_unsafe(target_ref);
}

static inline int
stopsound_source_unsafe(McfStrRef target_ref, StopSoundSource source)
{
    int ret;
    int target_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }

    switch (source) {
        case STOPSOUND_SOURCE_MASTER:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_source_unsafe_exec_0 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case STOPSOUND_SOURCE_MUSIC:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_source_unsafe_exec_1 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case STOPSOUND_SOURCE_RECORD:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_source_unsafe_exec_2 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case STOPSOUND_SOURCE_WEATHER:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_source_unsafe_exec_3 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case STOPSOUND_SOURCE_BLOCK:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_source_unsafe_exec_4 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case STOPSOUND_SOURCE_HOSTILE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_source_unsafe_exec_5 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case STOPSOUND_SOURCE_NEUTRAL:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_source_unsafe_exec_6 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case STOPSOUND_SOURCE_PLAYER:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_source_unsafe_exec_7 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case STOPSOUND_SOURCE_AMBIENT:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_source_unsafe_exec_8 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case STOPSOUND_SOURCE_VOICE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(target_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_source_unsafe_exec_9 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
stopsound_source(Target target, StopSoundSource source)
{
    McfStrRef target_ref;
    int target_slot;

    target_ref = _Command_RequireTargetRef(target);
    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }
    return stopsound_source_unsafe(target_ref, source);
}

static inline int
stopsound_sound_unsafe(McfStrRef target_ref, StopSoundSource source, McfStrRef sound_ref)
{
    int ret;
    int target_slot;
    int sound_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    sound_slot = McfStrRef_SlotId(sound_ref);
    if (target_slot < 0 || sound_slot < 0) {
        return -1;
    }

    switch (source) {
        case STOPSOUND_SOURCE_MASTER:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(target_slot), "r"(sound_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_sound_unsafe_exec_0 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case STOPSOUND_SOURCE_MUSIC:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(target_slot), "r"(sound_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_sound_unsafe_exec_1 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case STOPSOUND_SOURCE_RECORD:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(target_slot), "r"(sound_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_sound_unsafe_exec_2 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case STOPSOUND_SOURCE_WEATHER:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(target_slot), "r"(sound_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_sound_unsafe_exec_3 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case STOPSOUND_SOURCE_BLOCK:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(target_slot), "r"(sound_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_sound_unsafe_exec_4 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case STOPSOUND_SOURCE_HOSTILE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(target_slot), "r"(sound_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_sound_unsafe_exec_5 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case STOPSOUND_SOURCE_NEUTRAL:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(target_slot), "r"(sound_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_sound_unsafe_exec_6 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case STOPSOUND_SOURCE_PLAYER:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(target_slot), "r"(sound_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_sound_unsafe_exec_7 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case STOPSOUND_SOURCE_AMBIENT:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(target_slot), "r"(sound_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_sound_unsafe_exec_8 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        case STOPSOUND_SOURCE_VOICE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value\n"
                "inline $data modify storage std:vm ls0.sound set from storage std:vm mcstr.slots[%1].value"
                :
                : "r"(target_slot), "r"(sound_slot)
            );
            __asm volatile (
                "inline function _ll_shared:z/stopsound_sound_unsafe_exec_9 with storage std:vm ls0\n"
                "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
stopsound_sound(Target target, StopSoundSource source, const Identifier * sound)
{
    int ret;
    McfStrRef target_ref;
    McfStrRef sound_ref;
    int target_slot;
    int sound_slot;

    target_ref = _Command_RequireTargetRef(target);
    sound_ref = _Command_RequireIdentifierRef(sound);
    target_slot = McfStrRef_SlotId(target_ref);
    sound_slot = McfStrRef_SlotId(sound_ref);
    if (target_slot < 0 || sound_slot < 0) {
        McfStrRef_Release(sound_ref);
        return -1;
    }

    ret = stopsound_sound_unsafe(target_ref, source, sound_ref);
    McfStrRef_Release(sound_ref);
    return ret;
}

#ifdef __cplusplus
}
#endif
