/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

/*
 * File-scope command-helper label definitions for 'tag', split out
 * of bindings/tag.h so that a user translation unit which
 * #includes that header does NOT re-emit these `export` labels (they are already
 * provided, exactly once, by the LTO-built _ll_libmc.mch that every mcasm
 * program includes). This file is compiled once into the libmc stdlib bundle.
 */

__asm__(
"export _ll_shared:z/libmc_cmd_tag_add:\n"
"    inline $execute store result score r0 vm_regs run tag $(target) add $(name)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_tag_remove:\n"
"    inline $execute store result score r0 vm_regs run tag $(target) remove $(name)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_tag_list:\n"
"    inline $execute store result score r0 vm_regs run tag $(target) list\n"
"    ret\n"
);
