#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "tp.h"

#ifdef __cplusplus
extern "C" {
#endif

static inline int
teleport(Target target, Vec3d pos)
{
    return tp(target, pos);
}

static inline int
teleport_unsafe(McfStrRef target_ref, McfStrRef x_ref, McfStrRef y_ref, McfStrRef z_ref)
{
    return tp_unsafe(target_ref, x_ref, y_ref, z_ref);
}

static inline int
teleport_rot(Target target, Vec3d pos, Vec2f rot)
{
    return tp_rot(target, pos, rot);
}

static inline int
teleport_rot_unsafe(McfStrRef target_ref, McfStrRef x_ref, McfStrRef y_ref, McfStrRef z_ref, McfStrRef yaw_ref, McfStrRef pitch_ref)
{
    return tp_rot_unsafe(target_ref, x_ref, y_ref, z_ref, yaw_ref, pitch_ref);
}

static inline int
teleport_entity(Target target, Target destination)
{
    return tp_entity(target, destination);
}

static inline int
teleport_entity_unsafe(McfStrRef target_ref, McfStrRef destination_ref)
{
    return tp_entity_unsafe(target_ref, destination_ref);
}

#ifdef __cplusplus
}
#endif
