/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

/*
 * File-scope command-helper label definitions for 'title', split out
 * of bindings/title.h so that a user translation unit which
 * #includes that header does NOT re-emit these `export` labels (they are already
 * provided, exactly once, by the LTO-built _ll_libmc.mch that every mcasm
 * program includes). This file is compiled once into the libmc stdlib bundle.
 */

__asm__(
"export _ll_shared:z/libmc_cmd_title_clear:\n"
"    inline $execute store result score r0 vm_regs run title $(target) clear\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_title_reset:\n"
"    inline $execute store result score r0 vm_regs run title $(target) reset\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_title_title:\n"
"    inline $execute store result score r0 vm_regs run title $(target) title $(json)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_title_subtitle:\n"
"    inline $execute store result score r0 vm_regs run title $(target) subtitle $(json)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_title_actionbar:\n"
"    inline $execute store result score r0 vm_regs run title $(target) actionbar $(json)\n"
"    ret\n"
);
