#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_title_clear:\n"
"    inline $execute store result score r0 vm_regs run title $(target) clear\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_title_reset:\n"
"    inline $execute store result score r0 vm_regs run title $(target) reset\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_title_title:\n"
"    inline $execute store result score r0 vm_regs run title $(target) title $(json)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_title_subtitle:\n"
"    inline $execute store result score r0 vm_regs run title $(target) subtitle $(json)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_title_actionbar:\n"
"    inline $execute store result score r0 vm_regs run title $(target) actionbar $(json)\n"
"    ret\n"
);

static inline int
title_clear_unsafe(McfStrRef target_ref)
{
    int ret;
    int target_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_title_clear with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot)
    );
    return ret;
}

static inline int
title_clear(Target target)
{
    McfStrRef target_ref;
    int target_slot;

    target_ref = _Command_RequireTargetRef(target);
    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }
    return title_clear_unsafe(target_ref);
}

static inline int
title_reset_unsafe(McfStrRef target_ref)
{
    int ret;
    int target_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_title_reset with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot)
    );
    return ret;
}

static inline int
title_reset(Target target)
{
    McfStrRef target_ref;
    int target_slot;

    target_ref = _Command_RequireTargetRef(target);
    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }
    return title_reset_unsafe(target_ref);
}

static inline int
title_title_unsafe(McfStrRef target_ref, McfStrRef json_ref)
{
    int ret;
    int target_slot;
    int json_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    json_slot = McfStrRef_SlotId(json_ref);
    if (target_slot < 0 || json_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", json: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.json set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_title_title with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(json_slot)
    );
    return ret;
}

static inline int
title_title(Target target, String json)
{
    McfStrRef target_ref;
    McfStrRef json_ref;
    int target_slot;
    int json_slot;

    target_ref = _Command_RequireTargetRef(target);
    json_ref = _Command_RequireStringRef(json);
    target_slot = McfStrRef_SlotId(target_ref);
    json_slot = McfStrRef_SlotId(json_ref);
    if (target_slot < 0 || json_slot < 0) {
        return -1;
    }
    return title_title_unsafe(target_ref, json_ref);
}

static inline int
title_subtitle_unsafe(McfStrRef target_ref, McfStrRef json_ref)
{
    int ret;
    int target_slot;
    int json_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    json_slot = McfStrRef_SlotId(json_ref);
    if (target_slot < 0 || json_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", json: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.json set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_title_subtitle with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(json_slot)
    );
    return ret;
}

static inline int
title_subtitle(Target target, String json)
{
    McfStrRef target_ref;
    McfStrRef json_ref;
    int target_slot;
    int json_slot;

    target_ref = _Command_RequireTargetRef(target);
    json_ref = _Command_RequireStringRef(json);
    target_slot = McfStrRef_SlotId(target_ref);
    json_slot = McfStrRef_SlotId(json_ref);
    if (target_slot < 0 || json_slot < 0) {
        return -1;
    }
    return title_subtitle_unsafe(target_ref, json_ref);
}

static inline int
title_actionbar_unsafe(McfStrRef target_ref, McfStrRef json_ref)
{
    int ret;
    int target_slot;
    int json_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    json_slot = McfStrRef_SlotId(json_ref);
    if (target_slot < 0 || json_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", json: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.json set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_title_actionbar with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(json_slot)
    );
    return ret;
}

static inline int
title_actionbar(Target target, String json)
{
    McfStrRef target_ref;
    McfStrRef json_ref;
    int target_slot;
    int json_slot;

    target_ref = _Command_RequireTargetRef(target);
    json_ref = _Command_RequireStringRef(json);
    target_slot = McfStrRef_SlotId(target_ref);
    json_slot = McfStrRef_SlotId(json_ref);
    if (target_slot < 0 || json_slot < 0) {
        return -1;
    }
    return title_actionbar_unsafe(target_ref, json_ref);
}

static inline int
title_times_unsafe(McfStrRef target_ref, int fade_in, int stay, int fade_out)
{
    int ret;
    int target_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline $data modify storage std:vm ls0.target set from storage std:vm mcstr.slots[%0].value"
        :
        : "r"(target_slot)
    );
    __asm volatile (
        "$$direct_args\n"
        "inline $execute store result score %0 vm_regs run title $(target) times %1 %2 %3"
        : "=r"(ret)
        : "r"(fade_in), "r"(stay), "r"(fade_out)
    );
    return ret;
}

static inline int
title_times(Target target, int fade_in, int stay, int fade_out)
{
    McfStrRef target_ref;
    int target_slot;

    target_ref = _Command_RequireTargetRef(target);
    target_slot = McfStrRef_SlotId(target_ref);
    if (target_slot < 0) {
        return -1;
    }
    return title_times_unsafe(target_ref, fade_in, stay, fade_out);
}

#ifdef __cplusplus
}
#endif
