#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "teammsg.h"

#ifdef __cplusplus
extern "C" {
#endif

static inline int
tm(String message)
{
    return teammsg(message);
}

static inline int
tm_unsafe(McfStrRef message_ref)
{
    return teammsg_unsafe(message_ref);
}

#ifdef __cplusplus
}
#endif
