#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_tp:\n"
"    inline $execute store result score r0 vm_regs run tp $(target) $(x) $(y) $(z)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_tp_rot:\n"
"    inline $execute store result score r0 vm_regs run tp $(target) $(x) $(y) $(z) $(yaw) $(pitch)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_tp_entity:\n"
"    inline $execute store result score r0 vm_regs run tp $(target) $(destination)\n"
"    ret\n"
);

static inline int
tp_unsafe(McfStrRef target_ref, McfStrRef x_ref, McfStrRef y_ref, McfStrRef z_ref)
{
    int ret;
    int target_slot;
    int x_slot;
    int y_slot;
    int z_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    x_slot = McfStrRef_SlotId(x_ref);
    y_slot = McfStrRef_SlotId(y_ref);
    z_slot = McfStrRef_SlotId(z_ref);
    if (target_slot < 0 || x_slot < 0 || y_slot < 0 || z_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", x: \"\", y: \"\", z: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.x set from storage std:vm mcstr.slots[%2].value\n"
        "inline $data modify storage std:vm s6.cmd.y set from storage std:vm mcstr.slots[%3].value\n"
        "inline $data modify storage std:vm s6.cmd.z set from storage std:vm mcstr.slots[%4].value\n"
        "inline function _ll_shared:z/libmc_cmd_tp with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
    );
    return ret;
}

static inline int
tp_rot_unsafe(McfStrRef target_ref, McfStrRef x_ref, McfStrRef y_ref, McfStrRef z_ref,
              McfStrRef yaw_ref, McfStrRef pitch_ref)
{
    int ret;
    int target_slot;
    int x_slot;
    int y_slot;
    int z_slot;
    int yaw_slot;
    int pitch_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    x_slot = McfStrRef_SlotId(x_ref);
    y_slot = McfStrRef_SlotId(y_ref);
    z_slot = McfStrRef_SlotId(z_ref);
    yaw_slot = McfStrRef_SlotId(yaw_ref);
    pitch_slot = McfStrRef_SlotId(pitch_ref);
    if (target_slot < 0 || x_slot < 0 || y_slot < 0 ||
        z_slot < 0 || yaw_slot < 0 || pitch_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", x: \"\", y: \"\", z: \"\", yaw: \"\", pitch: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.x set from storage std:vm mcstr.slots[%2].value\n"
        "inline $data modify storage std:vm s6.cmd.y set from storage std:vm mcstr.slots[%3].value\n"
        "inline $data modify storage std:vm s6.cmd.z set from storage std:vm mcstr.slots[%4].value\n"
        "inline $data modify storage std:vm s6.cmd.yaw set from storage std:vm mcstr.slots[%5].value\n"
        "inline $data modify storage std:vm s6.cmd.pitch set from storage std:vm mcstr.slots[%6].value\n"
        "inline function _ll_shared:z/libmc_cmd_tp_rot with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot), "r"(yaw_slot), "r"(pitch_slot)
    );
    return ret;
}

static inline int
tp_entity_unsafe(McfStrRef target_ref, McfStrRef destination_ref)
{
    int ret;
    int target_slot;
    int destination_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    destination_slot = McfStrRef_SlotId(destination_ref);
    if (target_slot < 0 || destination_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", destination: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.destination set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_tp_entity with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(destination_slot)
    );
    return ret;
}

static inline int
tp(Target target, Vec3d pos)
{
    int ret;
    McfStrRef target_name;
    McfStrRef x;
    McfStrRef y;
    McfStrRef z;
    int target_slot;
    int x_slot;
    int y_slot;
    int z_slot;

    target_name = _Command_RequireTargetRef(target);
    target_slot = McfStrRef_SlotId(target_name);
    if (target_slot < 0) {
        return -1;
    }

    x = _Command_FormatDoubleRef(pos.x);
    x_slot = McfStrRef_SlotId(x);
    y = _Command_FormatDoubleRef(pos.y);
    y_slot = McfStrRef_SlotId(y);
    z = _Command_FormatDoubleRef(pos.z);
    z_slot = McfStrRef_SlotId(z);
    if (x_slot < 0 || y_slot < 0 || z_slot < 0) {
        McfStrRef_Release(x);
        McfStrRef_Release(y);
        McfStrRef_Release(z);
        return -1;
    }

    ret = tp_unsafe(target_name, x, y, z);
    McfStrRef_Release(x);
    McfStrRef_Release(y);
    McfStrRef_Release(z);
    return ret;
}

static inline int
tp_rot(Target target, Vec3d pos, Vec2f rot)
{
    int ret;
    McfStrRef target_name;
    McfStrRef x;
    McfStrRef y;
    McfStrRef z;
    McfStrRef yaw;
    McfStrRef pitch;
    int target_slot;
    int x_slot;
    int y_slot;
    int z_slot;
    int yaw_slot;
    int pitch_slot;

    target_name = _Command_RequireTargetRef(target);
    target_slot = McfStrRef_SlotId(target_name);
    if (target_slot < 0) {
        return -1;
    }

    x = _Command_FormatDoubleRef(pos.x);
    x_slot = McfStrRef_SlotId(x);
    y = _Command_FormatDoubleRef(pos.y);
    y_slot = McfStrRef_SlotId(y);
    z = _Command_FormatDoubleRef(pos.z);
    z_slot = McfStrRef_SlotId(z);
    yaw = _Command_FormatFloatRef(rot.x);
    yaw_slot = McfStrRef_SlotId(yaw);
    pitch = _Command_FormatFloatRef(rot.y);
    pitch_slot = McfStrRef_SlotId(pitch);
    if (x_slot < 0 || y_slot < 0 || z_slot < 0 || yaw_slot < 0 || pitch_slot < 0) {
        McfStrRef_Release(x);
        McfStrRef_Release(y);
        McfStrRef_Release(z);
        McfStrRef_Release(yaw);
        McfStrRef_Release(pitch);
        return -1;
    }

    ret = tp_rot_unsafe(target_name, x, y, z, yaw, pitch);
    McfStrRef_Release(x);
    McfStrRef_Release(y);
    McfStrRef_Release(z);
    McfStrRef_Release(yaw);
    McfStrRef_Release(pitch);
    return ret;
}

static inline int
tp_entity(Target target, Target destination)
{
    McfStrRef target_name;
    McfStrRef destination_name;
    int target_slot;
    int destination_slot;

    target_name = _Command_RequireTargetRef(target);
    target_slot = McfStrRef_SlotId(target_name);
    destination_name = _Command_RequireTargetRef(destination);
    destination_slot = McfStrRef_SlotId(destination_name);
    if (target_slot < 0 || destination_slot < 0) {
        return -1;
    }
    return tp_entity_unsafe(target_name, destination_name);
}

#ifdef __cplusplus
}
#endif
