#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "msg.h"

#ifdef __cplusplus
extern "C" {
#endif

static inline int
w(Target target, String message)
{
    return msg(target, message);
}

static inline int
w_unsafe(McfStrRef target_ref, McfStrRef message_ref)
{
    return msg_unsafe(target_ref, message_ref);
}

#ifdef __cplusplus
}
#endif
