#pragma once

/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

#include "bindings/CommandSupport.h"

typedef enum {
    WEATHER_CLEAR,
    WEATHER_RAIN,
    WEATHER_THUNDER
} WeatherType;

#ifdef __cplusplus
extern "C" {
#endif

static inline int
weather(WeatherType type)
{
    int ret;

    switch (type) {
        case WEATHER_CLEAR:
            __asm volatile (
                "inline $execute store result score %0 vm_regs run weather clear"
                : "=r"(ret)
            );
            return ret;
        case WEATHER_RAIN:
            __asm volatile (
                "inline $execute store result score %0 vm_regs run weather rain"
                : "=r"(ret)
            );
            return ret;
        case WEATHER_THUNDER:
            __asm volatile (
                "inline $execute store result score %0 vm_regs run weather thunder"
                : "=r"(ret)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
weather_duration(WeatherType type, int duration)
{
    int ret;

    switch (type) {
        case WEATHER_CLEAR:
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run weather clear %1"
                : "=r"(ret)
                : "r"(duration)
            );
            return ret;
        case WEATHER_RAIN:
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run weather rain %1"
                : "=r"(ret)
                : "r"(duration)
            );
            return ret;
        case WEATHER_THUNDER:
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run weather thunder %1"
                : "=r"(ret)
                : "r"(duration)
            );
            return ret;
        default:
            return -1;
    }
}

#ifdef __cplusplus
}
#endif
