/* Generated by tools/commands/generator/generate.py. Do not edit this file. */

/*
 * File-scope command-helper label definitions for 'worldborder', split out
 * of bindings/worldborder.h so that a user translation unit which
 * #includes that header does NOT re-emit these `export` labels (they are already
 * provided, exactly once, by the LTO-built _ll_libmc.mch that every mcasm
 * program includes). This file is compiled once into the libmc stdlib bundle.
 */

__asm__(
"export _ll_shared:z/libmc_cmd_worldborder_set:\n"
"    inline $execute store result score r0 vm_regs run worldborder set $(distance)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_worldborder_add:\n"
"    inline $execute store result score r0 vm_regs run worldborder add $(distance)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_worldborder_center:\n"
"    inline $execute store result score r0 vm_regs run worldborder center $(x) $(z)\n"
"    ret\n"
);
