from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
SCHEMA_PATH = ROOT / "tools" / "commands" / "schema" / "vanilla_commands.json"
ENTITY_LIST_PATH = ROOT / "src" / "resources" / "libmc" / "entity" / "Entities.h"
BINDINGS_DIR = ROOT / "src" / "resources" / "libmc" / "bindings"
ENTITY_TYPES_PATH = ROOT / "src" / "resources" / "libmc" / "entity" / "EntityTypes.h"
GENERATED_NOTICE = "/* Generated by tools/commands/generator/generate.py. Do not edit this file. */"


def load_schema() -> dict:
    return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))


def parse_entity_ids() -> list[str]:
    entity_ids: list[str] = []
    pattern = re.compile(r'^\s*X\((ENTITY_[A-Z0-9_]+),\s*"')
    for line in ENTITY_LIST_PATH.read_text(encoding="utf-8").splitlines():
        match = pattern.match(line)
        if match:
            entity_ids.append(match.group(1))
    return entity_ids


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8", newline="\n")


def entity_type_alias_name(entity_id: str) -> str:
    return entity_id.replace("ENTITY_", "ENTITY_TYPE_", 1)


def render_entity_types(entity_ids: list[str]) -> str:
    aliases = "\n".join(
        f"static const EntityType {entity_type_alias_name(entity_id)} = {entity_id};"
        for entity_id in entity_ids
    )
    return f"""#pragma once

{GENERATED_NOTICE}

#include "Entities.h"

#ifdef __cplusplus
extern "C" {{
#endif

{aliases}

#ifdef __cplusplus
}}
#endif
"""


def render_enum(enum_spec: dict) -> str:
    values = ",\n    ".join(enum_spec["values"])
    return f"""typedef enum {{
    {values}
}} {enum_spec["name"]};
"""


def render_setblock() -> str:
    return """static inline int
setblock_unsafe(int x, int y, int z, McfStrRef block_ref, SetBlockMode mode)
{
    int ret;
    int slot_id;

    slot_id = McfStrRef_SlotId(block_ref);
    if (slot_id < 0) {
        return -1;
    }

    switch (mode) {
        case DESTROY:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(slot_id)
            );
            __asm volatile (
                "$$direct_args\\n"
                "inline $execute store result score %0 vm_regs run setblock %1 %2 %3 $(block) destroy"
                : "=r"(ret)
                : "r"(x), "r"(y), "r"(z)
            );
            return ret;
        case KEEP:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(slot_id)
            );
            __asm volatile (
                "$$direct_args\\n"
                "inline $execute store result score %0 vm_regs run setblock %1 %2 %3 $(block) keep"
                : "=r"(ret)
                : "r"(x), "r"(y), "r"(z)
            );
            return ret;
        case REPLACE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(slot_id)
            );
            __asm volatile (
                "$$direct_args\\n"
                "inline $execute store result score %0 vm_regs run setblock %1 %2 %3 $(block)"
                : "=r"(ret)
                : "r"(x), "r"(y), "r"(z)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
setblock(Vec3i pos, Block block, SetBlockMode mode)
{
    McfStrRef block_name;

    block_name = Block_EnsureMcfName(block);
    if (McfStrRef_SlotId(block_name) < 0) {
        return -1;
    }
    return setblock_unsafe(pos.x, pos.y, pos.z, block_name, mode);
}
"""


def render_fill() -> str:
    return """static inline int
fill_unsafe(int from_x, int from_y, int from_z,
            int to_x, int to_y, int to_z,
            McfStrRef block_ref, FillMode mode)
{
    int ret;
    int slot_id;

    slot_id = McfStrRef_SlotId(block_ref);
    if (slot_id < 0) {
        return -1;
    }

    switch (mode) {
        case FILL_DESTROY:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(slot_id)
            );
            __asm volatile (
                "$$direct_args\\n"
                "inline $execute store result score %0 vm_regs run fill %1 %2 %3 %4 %5 %6 $(block) destroy"
                : "=r"(ret)
                : "r"(from_x), "r"(from_y), "r"(from_z),
                  "r"(to_x), "r"(to_y), "r"(to_z)
            );
            return ret;
        case FILL_HOLLOW:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(slot_id)
            );
            __asm volatile (
                "$$direct_args\\n"
                "inline $execute store result score %0 vm_regs run fill %1 %2 %3 %4 %5 %6 $(block) hollow"
                : "=r"(ret)
                : "r"(from_x), "r"(from_y), "r"(from_z),
                  "r"(to_x), "r"(to_y), "r"(to_z)
            );
            return ret;
        case FILL_KEEP:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(slot_id)
            );
            __asm volatile (
                "$$direct_args\\n"
                "inline $execute store result score %0 vm_regs run fill %1 %2 %3 %4 %5 %6 $(block) keep"
                : "=r"(ret)
                : "r"(from_x), "r"(from_y), "r"(from_z),
                  "r"(to_x), "r"(to_y), "r"(to_z)
            );
            return ret;
        case FILL_OUTLINE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(slot_id)
            );
            __asm volatile (
                "$$direct_args\\n"
                "inline $execute store result score %0 vm_regs run fill %1 %2 %3 %4 %5 %6 $(block) outline"
                : "=r"(ret)
                : "r"(from_x), "r"(from_y), "r"(from_z),
                  "r"(to_x), "r"(to_y), "r"(to_z)
            );
            return ret;
        case FILL_REPLACE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(slot_id)
            );
            __asm volatile (
                "$$direct_args\\n"
                "inline $execute store result score %0 vm_regs run fill %1 %2 %3 %4 %5 %6 $(block)"
                : "=r"(ret)
                : "r"(from_x), "r"(from_y), "r"(from_z),
                  "r"(to_x), "r"(to_y), "r"(to_z)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
fill(Vec3i from, Vec3i to, Block block, FillMode mode)
{
    McfStrRef block_name;

    block_name = Block_EnsureMcfName(block);
    if (McfStrRef_SlotId(block_name) < 0) {
        return -1;
    }
    return fill_unsafe(from.x, from.y, from.z, to.x, to.y, to.z, block_name, mode);
}
"""


def render_summon() -> str:
    return """__asm__(
"export _ll_shared:z/libmc_cmd_summon:\\n"
"    inline $execute store result score r0 vm_regs run summon $(entity_type) $(x) $(y) $(z)\\n"
"    ret\\n"
);

static inline int
summon_unsafe(McfStrRef entity_type_ref, McfStrRef x_ref, McfStrRef y_ref, McfStrRef z_ref)
{
    int ret;
    int entity_type_slot;
    int x_slot;
    int y_slot;
    int z_slot;

    entity_type_slot = McfStrRef_SlotId(entity_type_ref);
    x_slot = McfStrRef_SlotId(x_ref);
    y_slot = McfStrRef_SlotId(y_ref);
    z_slot = McfStrRef_SlotId(z_ref);
    if (entity_type_slot < 0 || x_slot < 0 || y_slot < 0 || z_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{entity_type: \\\"\\\", x: \\\"\\\", y: \\\"\\\", z: \\\"\\\"%}\\n"
        "inline $data modify storage std:vm s6.cmd.entity_type set from storage std:vm mcstr.slots[%1].value\\n"
        "inline $data modify storage std:vm s6.cmd.x set from storage std:vm mcstr.slots[%2].value\\n"
        "inline $data modify storage std:vm s6.cmd.y set from storage std:vm mcstr.slots[%3].value\\n"
        "inline $data modify storage std:vm s6.cmd.z set from storage std:vm mcstr.slots[%4].value\\n"
        "inline function _ll_shared:z/libmc_cmd_summon with storage std:vm s6.cmd\\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(entity_type_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
    );
    return ret;
}

static inline int
summon(EntityType type, Vec3d pos)
{
    int ret;
    McfStrRef entity_type_name;
    McfStrRef x;
    McfStrRef y;
    McfStrRef z;
    int entity_type_slot;
    int x_slot;
    int y_slot;
    int z_slot;

    entity_type_name = EntityType_EnsureMcfName(type);
    entity_type_slot = McfStrRef_SlotId(entity_type_name);
    if (entity_type_slot < 0) {
        return -1;
    }

    x = _Command_FormatDoubleRef(pos.x);
    x_slot = McfStrRef_SlotId(x);
    y = _Command_FormatDoubleRef(pos.y);
    y_slot = McfStrRef_SlotId(y);
    z = _Command_FormatDoubleRef(pos.z);
    z_slot = McfStrRef_SlotId(z);
    if (x_slot < 0 || y_slot < 0 || z_slot < 0) {
        McfStrRef_Release(x);
        McfStrRef_Release(y);
        McfStrRef_Release(z);
        return -1;
    }

    ret = summon_unsafe(entity_type_name, x, y, z);
    McfStrRef_Release(x);
    McfStrRef_Release(y);
    McfStrRef_Release(z);
    return ret;
}
"""


def render_kill() -> str:
    return """__asm__(
"export _ll_shared:z/libmc_cmd_kill:\\n"
"    inline $execute store result score r0 vm_regs run kill $(target)\\n"
"    ret\\n"
);

static inline int
kill_unsafe(McfStrRef target_ref)
{
    int ret;
    int slot_id;

    slot_id = McfStrRef_SlotId(target_ref);
    if (slot_id < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \\\"\\\"%}\\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\\n"
        "inline function _ll_shared:z/libmc_cmd_kill with storage std:vm s6.cmd\\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(slot_id)
    );
    return ret;
}

static inline int
kill(Target target)
{
    McfStrRef target_name;

    target_name = _Command_RequireTargetRef(target);
    if (McfStrRef_SlotId(target_name) < 0) {
        return -1;
    }
    return kill_unsafe(target_name);
}
"""


def render_tp() -> str:
    return """__asm__(
"export _ll_shared:z/libmc_cmd_tp:\\n"
"    inline $execute store result score r0 vm_regs run tp $(target) $(x) $(y) $(z)\\n"
"    ret\\n"
"\\n"
"export _ll_shared:z/libmc_cmd_tp_rot:\\n"
"    inline $execute store result score r0 vm_regs run tp $(target) $(x) $(y) $(z) $(yaw) $(pitch)\\n"
"    ret\\n"
"\\n"
"export _ll_shared:z/libmc_cmd_tp_entity:\\n"
"    inline $execute store result score r0 vm_regs run tp $(target) $(destination)\\n"
"    ret\\n"
);

static inline int
tp_unsafe(McfStrRef target_ref, McfStrRef x_ref, McfStrRef y_ref, McfStrRef z_ref)
{
    int ret;
    int target_slot;
    int x_slot;
    int y_slot;
    int z_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    x_slot = McfStrRef_SlotId(x_ref);
    y_slot = McfStrRef_SlotId(y_ref);
    z_slot = McfStrRef_SlotId(z_ref);
    if (target_slot < 0 || x_slot < 0 || y_slot < 0 || z_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \\\"\\\", x: \\\"\\\", y: \\\"\\\", z: \\\"\\\"%}\\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\\n"
        "inline $data modify storage std:vm s6.cmd.x set from storage std:vm mcstr.slots[%2].value\\n"
        "inline $data modify storage std:vm s6.cmd.y set from storage std:vm mcstr.slots[%3].value\\n"
        "inline $data modify storage std:vm s6.cmd.z set from storage std:vm mcstr.slots[%4].value\\n"
        "inline function _ll_shared:z/libmc_cmd_tp with storage std:vm s6.cmd\\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
    );
    return ret;
}

static inline int
tp_rot_unsafe(McfStrRef target_ref, McfStrRef x_ref, McfStrRef y_ref, McfStrRef z_ref,
              McfStrRef yaw_ref, McfStrRef pitch_ref)
{
    int ret;
    int target_slot;
    int x_slot;
    int y_slot;
    int z_slot;
    int yaw_slot;
    int pitch_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    x_slot = McfStrRef_SlotId(x_ref);
    y_slot = McfStrRef_SlotId(y_ref);
    z_slot = McfStrRef_SlotId(z_ref);
    yaw_slot = McfStrRef_SlotId(yaw_ref);
    pitch_slot = McfStrRef_SlotId(pitch_ref);
    if (target_slot < 0 || x_slot < 0 || y_slot < 0 ||
        z_slot < 0 || yaw_slot < 0 || pitch_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \\\"\\\", x: \\\"\\\", y: \\\"\\\", z: \\\"\\\", yaw: \\\"\\\", pitch: \\\"\\\"%}\\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\\n"
        "inline $data modify storage std:vm s6.cmd.x set from storage std:vm mcstr.slots[%2].value\\n"
        "inline $data modify storage std:vm s6.cmd.y set from storage std:vm mcstr.slots[%3].value\\n"
        "inline $data modify storage std:vm s6.cmd.z set from storage std:vm mcstr.slots[%4].value\\n"
        "inline $data modify storage std:vm s6.cmd.yaw set from storage std:vm mcstr.slots[%5].value\\n"
        "inline $data modify storage std:vm s6.cmd.pitch set from storage std:vm mcstr.slots[%6].value\\n"
        "inline function _ll_shared:z/libmc_cmd_tp_rot with storage std:vm s6.cmd\\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot), "r"(yaw_slot), "r"(pitch_slot)
    );
    return ret;
}

static inline int
tp_entity_unsafe(McfStrRef target_ref, McfStrRef destination_ref)
{
    int ret;
    int target_slot;
    int destination_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    destination_slot = McfStrRef_SlotId(destination_ref);
    if (target_slot < 0 || destination_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \\\"\\\", destination: \\\"\\\"%}\\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\\n"
        "inline $data modify storage std:vm s6.cmd.destination set from storage std:vm mcstr.slots[%2].value\\n"
        "inline function _ll_shared:z/libmc_cmd_tp_entity with storage std:vm s6.cmd\\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(destination_slot)
    );
    return ret;
}

static inline int
tp(Target target, Vec3d pos)
{
    int ret;
    McfStrRef target_name;
    McfStrRef x;
    McfStrRef y;
    McfStrRef z;
    int target_slot;
    int x_slot;
    int y_slot;
    int z_slot;

    target_name = _Command_RequireTargetRef(target);
    target_slot = McfStrRef_SlotId(target_name);
    if (target_slot < 0) {
        return -1;
    }

    x = _Command_FormatDoubleRef(pos.x);
    x_slot = McfStrRef_SlotId(x);
    y = _Command_FormatDoubleRef(pos.y);
    y_slot = McfStrRef_SlotId(y);
    z = _Command_FormatDoubleRef(pos.z);
    z_slot = McfStrRef_SlotId(z);
    if (x_slot < 0 || y_slot < 0 || z_slot < 0) {
        McfStrRef_Release(x);
        McfStrRef_Release(y);
        McfStrRef_Release(z);
        return -1;
    }

    ret = tp_unsafe(target_name, x, y, z);
    McfStrRef_Release(x);
    McfStrRef_Release(y);
    McfStrRef_Release(z);
    return ret;
}

static inline int
tp_rot(Target target, Vec3d pos, Vec2f rot)
{
    int ret;
    McfStrRef target_name;
    McfStrRef x;
    McfStrRef y;
    McfStrRef z;
    McfStrRef yaw;
    McfStrRef pitch;
    int target_slot;
    int x_slot;
    int y_slot;
    int z_slot;
    int yaw_slot;
    int pitch_slot;

    target_name = _Command_RequireTargetRef(target);
    target_slot = McfStrRef_SlotId(target_name);
    if (target_slot < 0) {
        return -1;
    }

    x = _Command_FormatDoubleRef(pos.x);
    x_slot = McfStrRef_SlotId(x);
    y = _Command_FormatDoubleRef(pos.y);
    y_slot = McfStrRef_SlotId(y);
    z = _Command_FormatDoubleRef(pos.z);
    z_slot = McfStrRef_SlotId(z);
    yaw = _Command_FormatFloatRef(rot.x);
    yaw_slot = McfStrRef_SlotId(yaw);
    pitch = _Command_FormatFloatRef(rot.y);
    pitch_slot = McfStrRef_SlotId(pitch);
    if (x_slot < 0 || y_slot < 0 || z_slot < 0 || yaw_slot < 0 || pitch_slot < 0) {
        McfStrRef_Release(x);
        McfStrRef_Release(y);
        McfStrRef_Release(z);
        McfStrRef_Release(yaw);
        McfStrRef_Release(pitch);
        return -1;
    }

    ret = tp_rot_unsafe(target_name, x, y, z, yaw, pitch);
    McfStrRef_Release(x);
    McfStrRef_Release(y);
    McfStrRef_Release(z);
    McfStrRef_Release(yaw);
    McfStrRef_Release(pitch);
    return ret;
}

static inline int
tp_entity(Target target, Target destination)
{
    McfStrRef target_name;
    McfStrRef destination_name;
    int target_slot;
    int destination_slot;

    target_name = _Command_RequireTargetRef(target);
    target_slot = McfStrRef_SlotId(target_name);
    destination_name = _Command_RequireTargetRef(destination);
    destination_slot = McfStrRef_SlotId(destination_name);
    if (target_slot < 0 || destination_slot < 0) {
        return -1;
    }
    return tp_entity_unsafe(target_name, destination_name);
}
"""


def render_say() -> str:
    return """__asm__(
"export _ll_shared:z/libmc_cmd_say:\\n"
"    inline $execute store result score r0 vm_regs run say $(text)\\n"
"    ret\\n"
);

static inline int
say_unsafe(McfStrRef text_ref)
{
    int ret;
    int slot_id;

    slot_id = McfStrRef_SlotId(text_ref);
    if (slot_id < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{text: \\\"\\\"%}\\n"
        "inline $data modify storage std:vm s6.cmd.text set from storage std:vm mcstr.slots[%1].value\\n"
        "inline function _ll_shared:z/libmc_cmd_say with storage std:vm s6.cmd\\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(slot_id)
    );
    return ret;
}

static inline int
say(String text)
{
    McfStrRef text_mcf;

    text_mcf = _Command_RequireStringRef(text);
    if (McfStrRef_SlotId(text_mcf) < 0) {
        return -1;
    }
    return say_unsafe(text_mcf);
}
"""


def render_tellraw() -> str:
    return """__asm__(
"export _ll_shared:z/libmc_cmd_tellraw:\\n"
"    inline $execute store result score r0 vm_regs run tellraw $(target) $(json)\\n"
"    ret\\n"
);

static inline int
tellraw_unsafe(McfStrRef target_ref, McfStrRef json_ref)
{
    int ret;
    int target_slot;
    int json_slot;

    target_slot = McfStrRef_SlotId(target_ref);
    json_slot = McfStrRef_SlotId(json_ref);
    if (target_slot < 0 || json_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \\\"\\\", json: \\\"\\\"%}\\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\\n"
        "inline $data modify storage std:vm s6.cmd.json set from storage std:vm mcstr.slots[%2].value\\n"
        "inline function _ll_shared:z/libmc_cmd_tellraw with storage std:vm s6.cmd\\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(json_slot)
    );
    return ret;
}

static inline int
tellraw(Target target, String json)
{
    McfStrRef target_name;
    McfStrRef json_text;
    int target_slot;
    int json_slot;

    target_name = _Command_RequireTargetRef(target);
    target_slot = McfStrRef_SlotId(target_name);
    json_text = _Command_RequireStringRef(json);
    json_slot = McfStrRef_SlotId(json_text);
    if (target_slot < 0 || json_slot < 0) {
        return -1;
    }
    return tellraw_unsafe(target_name, json_text);
}
"""


RENDERERS = {
    "setblock": render_setblock,
    "fill": render_fill,
    "summon": render_summon,
    "kill": render_kill,
    "tp": render_tp,
    "say": render_say,
    "tellraw": render_tellraw,
}


def render_header(command: dict) -> str:
    enums = "\n".join(render_enum(enum_spec) for enum_spec in command.get("enums", []))
    body = RENDERERS[command["kind"]]()
    return f"""#pragma once

{GENERATED_NOTICE}

#include "bindings/CommandSupport.h"

{enums}
#ifdef __cplusplus
extern "C" {{
#endif

{body}
#ifdef __cplusplus
}}
#endif
"""


def main() -> None:
    schema = load_schema()
    entity_ids = parse_entity_ids()
    write_if_changed(ENTITY_TYPES_PATH, render_entity_types(entity_ids))
    for command in schema["commands"]:
        write_if_changed(BINDINGS_DIR / command["header"], render_header(command))


if __name__ == "__main__":
    main()
