from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
SCHEMA_PATH = ROOT / "tools" / "commands" / "schema" / "vanilla_commands.json"
BINDINGS_DIR = ROOT / "src" / "resources" / "libmc" / "include" / "bindings"
VANILLA_BINDINGS_PATH = BINDINGS_DIR / "vanilla.h"
GENERATED_NOTICE = "/* Generated by tools/commands/generator/generate.py. Do not edit this file. */"


# Type descriptors for scalar (non-grouped) parameter types.
#
# category: "value" params are passed as plain registers/immediates (no
#           McfStrRef allocation); "ref" params must be converted to a
#           McfStrRef before they can be embedded in a command.
# to_ref:   conversion function name (ref types only).
# needs_release: whether the McfStrRef returned by to_ref is a fresh
#           allocation the caller owns (must Release), as opposed to a
#           borrowed/cached ref owned by the source object.
TYPES = {
    "int": {"category": "value", "c_type": "int"},
    "double": {
        "category": "ref", "c_type": "double",
        "to_ref": "_Command_FormatDoubleRef", "needs_release": True,
    },
    "float": {
        "category": "ref", "c_type": "float",
        "to_ref": "_Command_FormatFloatRef", "needs_release": True,
    },
    "target": {
        "category": "ref", "c_type": "Target",
        "to_ref": "_Command_RequireTargetRef", "needs_release": False,
    },
    "string": {
        "category": "ref", "c_type": "String",
        "to_ref": "_Command_RequireStringRef", "needs_release": False,
    },
    "cstring": {
        "category": "ref", "c_type": "const char *",
        "to_ref": "_Command_RequireCStringRef", "needs_release": True,
    },
    "block": {
        "category": "ref", "c_type": "Block",
        "to_ref": "Block_EnsureMcfName", "needs_release": False,
    },
    "entity_type": {
        "category": "ref", "c_type": "Entity",
        "to_ref": "Entity_EnsureMcfName", "needs_release": False,
    },
    "identifier": {
        "category": "ref", "c_type": "const Identifier *",
        "to_ref": "_Command_RequireIdentifierRef", "needs_release": True,
    },
    "text_component": {
        "category": "ref", "c_type": "TextComponent",
        "to_ref": "_Command_RequireTextComponentRef", "needs_release": True,
    },
    # bool is not a ref: it expands to a compile-time branch (if/else) that
    # bakes the literal `true`/`false` straight into the command text, the
    # same way an enum bakes its per-case literal. Only c_type (the public
    # signature type) is consulted; see expand_param's dedicated bool arm.
    "bool": {"c_type": "int"},
}

# Grouped (multi-field) parameter types. Each expands into several scalar
# slots at code-generation time; "fields" gives the struct member access
# order, "asm_fields" (schema-provided per param) gives the flat name used
# for the local variable / NBT field / command placeholder for each member.
GROUPS = {
    "vec3i": {
        "category": "value", "c_type": "Vec3i",
        "fields": ["x", "y", "z"], "scalar_type": "int",
    },
    "vec3d": {
        "category": "ref", "c_type": "Vec3d",
        "fields": ["x", "y", "z"], "scalar_type": "double",
        "to_ref": "_Command_FormatDoubleRef", "needs_release": True,
    },
    "vec2f": {
        "category": "ref", "c_type": "Vec2f",
        "fields": ["x", "y"], "scalar_type": "float",
        "to_ref": "_Command_FormatFloatRef", "needs_release": True,
    },
    "vec2d": {
        "category": "ref", "c_type": "Vec2d",
        "fields": ["x", "z"], "scalar_type": "double",
        "to_ref": "_Command_FormatDoubleRef", "needs_release": True,
    },
}


def load_schema() -> dict:
    return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8", newline="\n")


def render_enum(enum_spec: dict) -> str:
    enum_values = enum_spec["values"]
    if not enum_values:
        raise ValueError(
            f"enum {enum_spec.get('name', '<unnamed>')!r} has no values; "
            "cannot generate an empty enum body"
        )
    values = ",\n    ".join(value["const"] for value in enum_values)
    return f"""typedef enum {{
    {values}
}} {enum_spec["name"]};
"""


def command_c_name(command_name: str) -> str:
    return re.sub(r"[^0-9A-Za-z_]", "_", command_name)


# ---------------------------------------------------------------------------
# Structured-command rendering
# ---------------------------------------------------------------------------


def expand_param(param: dict) -> list[dict]:
    """Expand one schema param into an ordered list of code-generation slots."""
    ptype = param["type"]

    if ptype == "literal":
        # A fixed keyword that must appear at this position in the command
        # (e.g. the trailing `points`/`levels`/`everything` after a selector).
        # Contributes a bare token to the command text but NO C parameter.
        return [{"kind": "literal", "text": param["text"]}]

    if ptype == "enum":
        return [{"kind": "enum", "param_name": param["name"], "enum_ref": param["enum_ref"]}]

    if ptype == "bool":
        # A two-valued compile-time branch: `int value` in the public
        # signature, dispatched via if/else, each arm baking the fixed
        # literal true/false into the command. No McfStrRef, no slot.
        return [{"kind": "bool", "param_name": param["name"]}]

    if ptype in GROUPS:
        group = GROUPS[ptype]
        asm_fields = param["asm_fields"]
        if len(asm_fields) != len(group["fields"]):
            raise ValueError(
                f"param {param['name']!r} of type {ptype!r} needs "
                f"{len(group['fields'])} asm_fields, got {len(asm_fields)}"
            )
        slots = []
        for struct_field, flat_name in zip(group["fields"], asm_fields):
            slots.append({
                "kind": group["category"],
                "flat_name": flat_name,
                "c_type": group["scalar_type"],
                "source_expr": f'{param["name"]}.{struct_field}',
                "to_ref": group.get("to_ref"),
                "needs_release": group.get("needs_release", False),
            })
        return slots

    descriptor = TYPES[ptype]
    return [{
        "kind": descriptor["category"],
        "flat_name": param["name"],
        "c_type": descriptor["c_type"],
        "source_expr": param["name"],
        "to_ref": descriptor.get("to_ref"),
        "needs_release": descriptor.get("needs_release", False),
    }]


def expand_variant(variant: dict) -> list[dict]:
    slots: list[dict] = []
    for param in variant.get("params", []):
        slots.extend(expand_param(param))
    return slots


def check_no_asm_field_collisions(cmd_name: str, variant: dict, slots: list[dict]) -> None:
    seen: dict[str, str] = {}
    for slot in slots:
        if slot["kind"] in ("enum", "literal", "bool"):
            continue
        flat_name = slot["flat_name"]
        if flat_name in seen:
            raise ValueError(
                f"command {cmd_name!r} variant {variant.get('c_suffix', '')!r} has "
                f"duplicate asm field name {flat_name!r}"
            )
        seen[flat_name] = flat_name


def public_param_list(variant: dict) -> str:
    parts = []
    for param in variant.get("params", []):
        ptype = param["type"]
        if ptype == "literal":
            continue
        if ptype == "enum":
            c_type = param["enum_ref"]
        elif ptype in GROUPS:
            c_type = GROUPS[ptype]["c_type"]
        else:
            c_type = TYPES[ptype]["c_type"]
        parts.append(f'{c_type} {param["name"]}')
    return ", ".join(parts) if parts else "void"


def public_arg_names(variant: dict) -> list[str]:
    return [param["name"] for param in variant.get("params", []) if param["type"] != "literal"]


# Placeholder for the one compile-time "choice" token a variant may carry: the
# per-case literal of an enum, or the true/false literal of a bool. A variant
# has at most one branch param (see render_template_b), so at most one of these
# appears in a command's token stream; render_command_text substitutes the
# chosen literal at render time.
class _ChoiceToken:
    __slots__ = ()


def build_command_tokens(cmd_name: str, variant: dict, slots: list[dict]) -> list:
    tokens: list = [cmd_name, *variant.get("literal_path", [])]
    value_index = 0
    for slot in slots:
        if slot["kind"] in ("enum", "bool"):
            tokens.append(_ChoiceToken())
        elif slot["kind"] == "literal":
            tokens.append(slot["text"])
        elif slot["kind"] == "ref":
            tokens.append(f"$({slot['flat_name']})")
        else:
            value_index += 1
            tokens.append(f"%{value_index}")
    return tokens


# A mcfunction line may be prefixed with `$` (a "macro line") if and only if it
# actually contains at least one `$(...)` macro placeholder; Minecraft refuses to
# load a function whose `$`-line has no placeholder. In these bindings a line ends
# up carrying a `$(...)` from one of two sources: a `$(name)` token baked into the
# command text (ref params), or a `%N` asm operand that the mcasm backend rewrites
# into `$(...)` during generation. The standalone `export ...:` helpers use a
# literal `r0` register (no `%N` operands), so their only possible macro source is
# a `$(...)` in the command text.
_MACRO_PLACEHOLDER_RE = re.compile(r"\$\(|%\d")


def _macro_prefix(text: str) -> str:
    """Return '$' if `text` contains a macro placeholder, else '' (see note above)."""
    return "$" if _MACRO_PLACEHOLDER_RE.search(text) else ""


def render_command_text(tokens: list, branch_literal: str | None) -> str:
    final_tokens = []
    for token in tokens:
        if isinstance(token, _ChoiceToken):
            if branch_literal is None:
                raise ValueError("command text has a choice placeholder but no branch_literal given")
            if branch_literal:
                final_tokens.append(branch_literal)
            # empty literal -> omit token entirely
        else:
            final_tokens.append(token)
    return " ".join(final_tokens)


# --- Template A: pure-ref (or zero-field) commands. -------------------------
#
# Mirrors the existing tp/tp_rot/tp_entity/kill/say/tellraw/summon shape: a
# file-scope __asm__ block exports a small hand-shaped mcfunction that reads
# its arguments from a shared "s6.cmd" storage record via macro substitution;
# the C wrapper writes each field into that record (via mcstr slot ids) and
# calls the exported function with `inline function ... with storage ...`.


def render_template_a(cmd_name: str, suffix: str, variant: dict, slots: list[dict]):
    fname = f"{command_c_name(cmd_name)}{suffix}"
    label = f"_ll_shared:z/libmc_cmd_{fname}"
    ref_slots = [s for s in slots if s["kind"] == "ref"]

    cmd_text = render_command_text(build_command_tokens(cmd_name, variant, slots), None)
    macro = _macro_prefix(cmd_text)
    export_snippet = (
        f'"export {label}:\\n"\n'
        f'"    inline {macro}execute store result score r0 vm_regs run {cmd_text}\\n"\n'
        f'"    ret\\n"'
    )

    parts = []

    if not ref_slots:
        public_params = public_param_list(variant)
        parts.append(f"""static inline int
{fname}({public_params})
{{
    int ret;

    __asm volatile (
        "inline function {label}\\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
    );
    return ret;
}}
""")
        return export_snippet, "\n".join(parts)

    unsafe_params = ", ".join(f"McfStrRef {s['flat_name']}_ref" for s in ref_slots)
    slot_decls = "\n".join(f"    int {s['flat_name']}_slot;" for s in ref_slots)
    slot_assigns = "\n".join(
        f"    {s['flat_name']}_slot = McfStrRef_SlotId({s['flat_name']}_ref);" for s in ref_slots
    )
    slot_check = " || ".join(f"{s['flat_name']}_slot < 0" for s in ref_slots)
    struct_init = ", ".join(f'{s["flat_name"]}: \\"\\"' for s in ref_slots)
    field_writes = "\n        ".join(
        f'"inline $data modify storage std:vm s6.cmd.{s["flat_name"]} '
        f'set from storage std:vm mcstr.slots[%{i}].value\\n"'
        for i, s in enumerate(ref_slots, start=1)
    )
    operand_list = ", ".join(f'"r"({s["flat_name"]}_slot)' for s in ref_slots)

    parts.append(f"""static inline int
{fname}_unsafe({unsafe_params})
{{
    int ret;
{slot_decls}

{slot_assigns}
    if ({slot_check}) {{
        return -1;
    }}

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{{{struct_init}%}}\\n"
        {field_writes}
        "inline function {label} with storage std:vm s6.cmd\\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : {operand_list}
    );
    return ret;
}}
""")

    public_params = public_param_list(variant)
    conv_decls = "\n".join(f"    McfStrRef {s['flat_name']}_ref;" for s in ref_slots)
    conv_assigns = "\n".join(
        f"    {s['flat_name']}_ref = {s['to_ref']}({s['source_expr']});" for s in ref_slots
    )
    call_args = ", ".join(f"{s['flat_name']}_ref" for s in ref_slots)
    release_needed = [s for s in ref_slots if s["needs_release"]]
    release_lines_nested = "\n".join(f"        McfStrRef_Release({s['flat_name']}_ref);" for s in release_needed)
    release_lines_flat = "\n".join(f"    McfStrRef_Release({s['flat_name']}_ref);" for s in release_needed)

    if release_needed:
        body = f"""    int ret;
{conv_decls}
{slot_decls}

{conv_assigns}
{slot_assigns}
    if ({slot_check}) {{
{release_lines_nested}
        return -1;
    }}

    ret = {fname}_unsafe({call_args});
{release_lines_flat}
    return ret;"""
    else:
        body = f"""{conv_decls}
{slot_decls}

{conv_assigns}
{slot_assigns}
    if ({slot_check}) {{
        return -1;
    }}
    return {fname}_unsafe({call_args});"""

    parts.append(f"""static inline int
{fname}({public_params})
{{
{body}
}}
""")

    return export_snippet, "\n".join(parts)


# --- Template B: variants with value-type params (plain int / vec3i
# members) and/or a compile-time enum branch. Mirrors the existing
# setblock/fill shape: no separately exported mcfunction; everything is
# inlined directly in the compiled C function using a per-function "ls0"
# scratch storage record for ref fields (if any) and `$$direct_args` to
# embed value-type registers directly as literal numbers in the command
# text. Enum params compile down to a C switch, one case per enum value,
# each emitting its own literal command suffix.


def _render_asm_branch(cmd_name: str, variant: dict, tokens: list, ref_slots: list[dict],
                        value_slots: list[dict], branch_literal: str | None, indent: str,
                        in_unsafe: bool, fname: str, branch_key: str) -> tuple[str, list[str]]:
    # Inside an _unsafe() function, value slots are real declared parameters
    # named after their flat_name (e.g. setblock_unsafe(int x, int y, int z, ...)).
    # Without an _unsafe layer (has_ref == False), this asm is embedded
    # directly in the public function, whose real parameters are the
    # *un-expanded* schema params (e.g. setworldspawn_at(Vec3i pos)) — so a
    # grouped value field must be read via its source_expr (pos.x), not the
    # flat_name (x), which was never declared as a local in that scope.
    #
    # Returns (branch_c_code, export_snippets). export_snippets are file-scope
    # `export ...:` mcfunction helpers that must be emitted outside the C
    # function (see the "explicit hoist" note below).
    def value_expr(slot: dict) -> str:
        return slot["flat_name"] if in_unsafe else slot["source_expr"]

    cmd_text = render_command_text(tokens, branch_literal)
    inner = indent + "    "
    lines = []
    exports: list[str] = []

    if ref_slots:
        write_lines = []
        for i, slot in enumerate(ref_slots):
            trailing = "\\n" if i < len(ref_slots) - 1 else ""
            write_lines.append(
                f'"inline $data modify storage std:vm ls0.{slot["flat_name"]} '
                f'set from storage std:vm mcstr.slots[%{i}].value{trailing}"'
            )
        operand_list = ", ".join(f'"r"({s["flat_name"]}_slot)' for s in ref_slots)
        lines.append(f"{indent}__asm volatile (")
        for write_line in write_lines:
            lines.append(f"{inner}{write_line}")
        lines.append(f"{inner}:")
        lines.append(f"{inner}: {operand_list}")
        lines.append(f"{indent});")

    # A ref field contributes a `$(name)` macro to the command text, which
    # stays a runtime macro line. Such a line MUST run inside a mcfunction
    # invoked `with storage`, or Minecraft aborts the whole function on the
    # missing macro argument — skipping the caller's stack epilogue and
    # leaking rsp (see GAMEMODE_TARGET_CODEGEN_BUG.md).
    #
    # When there are value operands, `$$direct_args` already forces the mcasm
    # backend to hoist the whole `$execute ...` line into a `with storage`
    # helper (setblock/fill), carrying the `$(name)` macro along. But with no
    # value operands there is nothing for the backend to hoist on, so we hoist
    # the macro command ourselves into an explicit file-scope helper (the same
    # shape Template A uses) and invoke it `with storage std:vm ls0`.
    needs_explicit_hoist = bool(ref_slots) and not value_slots
    if needs_explicit_hoist:
        label = f"_ll_shared:z/{fname}_unsafe_exec{branch_key}"
        macro = _macro_prefix(cmd_text)
        exports.append(
            f'"export {label}:\\n"\n'
            f'"    inline {macro}execute store result score r0 vm_regs run {cmd_text}\\n"\n'
            f'"    ret\\n"'
        )
        lines.append(f"{indent}__asm volatile (")
        lines.append(f'{inner}"inline function {label} with storage std:vm ls0\\n"')
        lines.append(f'{inner}"inline scoreboard players operation %0 vm_regs = r0 vm_regs"')
        lines.append(f'{inner}: "=r"(ret)')
        lines.append(f"{indent});")
        lines.append(f"{indent}return ret;")
        return "\n".join(lines), exports

    exec_lines = []
    if value_slots:
        exec_lines.append('"$$direct_args\\n"')
    # Only prefix `$` when the command text actually carries a macro placeholder
    # (`$(...)` from a ref field, or a `%N` value operand that `$$direct_args`
    # rewrites into `$(...)`). The `%0` output operand becomes a plain register,
    # not a macro, so a pure-enum command like `difficulty peaceful` must stay a
    # non-macro line -- Minecraft refuses to load a `$`-line with no variables
    # ("Macro without variables"), which would abort the function and leak rsp.
    exec_macro = _macro_prefix(cmd_text)
    exec_lines.append(f'"inline {exec_macro}execute store result score %0 vm_regs run {cmd_text}"')
    value_operand_list = ", ".join(f'"r"({value_expr(s)})' for s in value_slots)

    lines.append(f"{indent}__asm volatile (")
    for exec_line in exec_lines:
        lines.append(f"{inner}{exec_line}")
    lines.append(f'{inner}: "=r"(ret)')
    if value_slots:
        lines.append(f"{inner}: {value_operand_list}")
    lines.append(f"{indent});")
    lines.append(f"{indent}return ret;")

    return "\n".join(lines), exports


def render_template_b(cmd_name: str, suffix: str, variant: dict, slots: list[dict], enums_by_name: dict):
    fname = f"{command_c_name(cmd_name)}{suffix}"
    ref_slots = [s for s in slots if s["kind"] == "ref"]
    value_slots = [s for s in slots if s["kind"] == "value"]
    enum_slots = [s for s in slots if s["kind"] == "enum"]
    bool_slots = [s for s in slots if s["kind"] == "bool"]
    # enum and bool are both compile-time branch dimensions. The generator
    # currently emits a single flat switch/if per variant, so it supports at
    # most one branch dimension; a variant needing several (an enum crossed
    # with a bool) would require generalizing this to a cartesian product of
    # nested branches. No vanilla command mixes them, so we reject it loudly.
    if len(enum_slots) + len(bool_slots) > 1:
        raise ValueError(
            f"command {cmd_name!r} variant {suffix!r} has more than one branch "
            f"(enum/bool) param; generalize render_template_b to a branch product"
        )
    enum_slot = enum_slots[0] if enum_slots else None
    bool_slot = bool_slots[0] if bool_slots else None

    tokens = build_command_tokens(cmd_name, variant, slots)
    in_unsafe = len(ref_slots) > 0

    exports: list[str] = []
    if enum_slot is not None:
        enum_spec = enums_by_name[enum_slot["enum_ref"]]
        switch_cases = []
        for i, value in enumerate(enum_spec["values"]):
            branch, branch_exports = _render_asm_branch(
                cmd_name, variant, tokens, ref_slots, value_slots, value["literal"],
                indent="            ", in_unsafe=in_unsafe, fname=fname, branch_key=f"_{i}"
            )
            exports.extend(branch_exports)
            switch_cases.append(f"""        case {value["const"]}:
{branch}""")
        switch_body = "\n".join(switch_cases)
        asm_and_return = f"""    switch ({enum_slot["param_name"]}) {{
{switch_body}
        default:
            return -1;
    }}"""
    elif bool_slot is not None:
        # Two compile-time arms, each baking the fixed literal true/false into
        # the command. Mirrors the enum switch, dispatched on the plain int.
        param_name = bool_slot["param_name"]
        true_branch, true_exports = _render_asm_branch(
            cmd_name, variant, tokens, ref_slots, value_slots, "true",
            indent="        ", in_unsafe=in_unsafe, fname=fname, branch_key="_true"
        )
        false_branch, false_exports = _render_asm_branch(
            cmd_name, variant, tokens, ref_slots, value_slots, "false",
            indent="        ", in_unsafe=in_unsafe, fname=fname, branch_key="_false"
        )
        exports.extend(true_exports)
        exports.extend(false_exports)
        asm_and_return = f"""    if ({param_name}) {{
{true_branch}
    }} else {{
{false_branch}
    }}"""
    else:
        asm_and_return, exports = _render_asm_branch(
            cmd_name, variant, tokens, ref_slots, value_slots, None,
            indent="    ", in_unsafe=in_unsafe, fname=fname, branch_key=""
        )

    def slot_unsafe_param(slot: dict) -> str:
        if slot["kind"] == "ref":
            return f"McfStrRef {slot['flat_name']}_ref"
        if slot["kind"] == "value":
            return f"{slot['c_type']} {slot['flat_name']}"
        if slot["kind"] == "bool":
            return f"int {slot['param_name']}"
        return f"{slot['enum_ref']} {slot['param_name']}"

    def slot_call_arg(slot: dict) -> str:
        if slot["kind"] == "ref":
            return f"{slot['flat_name']}_ref"
        if slot["kind"] == "value":
            return slot["source_expr"]
        if slot["kind"] == "bool":
            return slot["param_name"]
        return slot["param_name"]

    parts = []
    has_ref = len(ref_slots) > 0
    # Literal slots carry no C parameter/argument; keep them out of the
    # public _unsafe() signature and call-site argument list.
    param_slots = [s for s in slots if s["kind"] != "literal"]

    if has_ref:
        # Preserve the schema-declared parameter order in the public
        # _unsafe() signature and call-site argument list, even though the
        # asm plumbing below groups slots by category (ref vs. value).
        unsafe_params = ", ".join(slot_unsafe_param(s) for s in param_slots)

        slot_decls = "\n".join(f"    int {s['flat_name']}_slot;" for s in ref_slots)
        slot_assigns = "\n".join(
            f"    {s['flat_name']}_slot = McfStrRef_SlotId({s['flat_name']}_ref);" for s in ref_slots
        )
        slot_check = " || ".join(f"{s['flat_name']}_slot < 0" for s in ref_slots)

        parts.append(f"""static inline int
{fname}_unsafe({unsafe_params})
{{
    int ret;
{slot_decls}

{slot_assigns}
    if ({slot_check}) {{
        return -1;
    }}

{asm_and_return}
}}
""")

        public_params = public_param_list(variant)
        conv_decls = "\n".join(f"    McfStrRef {s['flat_name']}_ref;" for s in ref_slots)
        conv_assigns = "\n".join(
            f"    {s['flat_name']}_ref = {s['to_ref']}({s['source_expr']});" for s in ref_slots
        )
        release_needed = [s for s in ref_slots if s["needs_release"]]
        release_lines_nested = "\n".join(f"        McfStrRef_Release({s['flat_name']}_ref);" for s in release_needed)
        release_lines_flat = "\n".join(f"    McfStrRef_Release({s['flat_name']}_ref);" for s in release_needed)

        call_args = ", ".join(slot_call_arg(s) for s in param_slots)

        if release_needed:
            body = f"""    int ret;
{conv_decls}
{slot_decls}

{conv_assigns}
{slot_assigns}
    if ({slot_check}) {{
{release_lines_nested}
        return -1;
    }}

    ret = {fname}_unsafe({call_args});
{release_lines_flat}
    return ret;"""
        else:
            body = f"""{conv_decls}
{slot_decls}

{conv_assigns}
{slot_assigns}
    if ({slot_check}) {{
        return -1;
    }}
    return {fname}_unsafe({call_args});"""

        parts.append(f"""static inline int
{fname}({public_params})
{{
{body}
}}
""")
    else:
        # No ref fields at all: the structured function *is* the only
        # function generated (there is nothing "unsafe" to guard against).
        public_params = public_param_list(variant)
        parts.append(f"""static inline int
{fname}({public_params})
{{
    int ret;

{asm_and_return}
}}
""")

    export_snippet = '\n"\\n"\n'.join(exports) if exports else None
    return export_snippet, "\n".join(parts)


def render_variant(cmd_name: str, variant: dict, enums_by_name: dict):
    suffix = variant.get("c_suffix", "")
    slots = expand_variant(variant)
    check_no_asm_field_collisions(cmd_name, variant, slots)

    needs_template_b = any(s["kind"] in ("value", "enum", "bool") for s in slots)
    if needs_template_b:
        return render_template_b(cmd_name, suffix, variant, slots, enums_by_name)
    return render_template_a(cmd_name, suffix, variant, slots)


def render_structured_body(command: dict) -> str:
    enums_by_name = {enum_spec["name"]: enum_spec for enum_spec in command.get("enums", [])}
    export_snippets = []
    bodies = []
    for variant in command["variants"]:
        export_snippet, body = render_variant(command["name"], variant, enums_by_name)
        if export_snippet is not None:
            export_snippets.append(export_snippet)
        bodies.append(body)

    parts = []
    if export_snippets:
        parts.append("__asm__(\n" + '\n"\\n"\n'.join(export_snippets) + "\n);\n")
    parts.extend(bodies)
    return "\n".join(parts)


def render_alias_header(command: dict, target: dict) -> str:
    target_fn = command_c_name(target["name"])
    alias_fn = command_c_name(command["name"])
    forwards = []
    for variant in target["variants"]:
        suffix = variant.get("c_suffix", "")
        slots = expand_variant(variant)
        params = public_param_list(variant)
        args = ", ".join(public_arg_names(variant))
        forwards.append(f"""static inline int
{alias_fn}{suffix}({params})
{{
    return {target_fn}{suffix}({args});
}}""")
        if any(s["kind"] == "ref" for s in slots):
            # The target's _unsafe() takes ALL non-literal slots in schema
            # order (ref -> McfStrRef, value -> scalar, enum -> enum type),
            # not just the ref slots -- mirror render_template_b's signature
            # so the forwarder passes every argument through.
            def _alias_unsafe_param(slot: dict) -> str:
                if slot["kind"] == "ref":
                    return f"McfStrRef {slot['flat_name']}_ref"
                if slot["kind"] == "value":
                    return f"{slot['c_type']} {slot['flat_name']}"
                if slot["kind"] == "bool":
                    return f"int {slot['param_name']}"
                return f"{slot['enum_ref']} {slot['param_name']}"

            def _alias_unsafe_arg(slot: dict) -> str:
                if slot["kind"] == "ref":
                    return f"{slot['flat_name']}_ref"
                if slot["kind"] == "value":
                    return slot["flat_name"]
                if slot["kind"] == "bool":
                    return slot["param_name"]
                return slot["param_name"]

            unsafe_slots = [s for s in slots if s["kind"] != "literal"]
            unsafe_params = ", ".join(_alias_unsafe_param(s) for s in unsafe_slots)
            unsafe_args = ", ".join(_alias_unsafe_arg(s) for s in unsafe_slots)
            forwards.append(f"""static inline int
{alias_fn}{suffix}_unsafe({unsafe_params})
{{
    return {target_fn}{suffix}_unsafe({unsafe_args});
}}""")
    body = "\n\n".join(forwards)
    return f"""#pragma once

{GENERATED_NOTICE}

#include "{target["header"]}"

#ifdef __cplusplus
extern "C" {{
#endif

{body}

#ifdef __cplusplus
}}
#endif
"""


def render_empty_shell(command: dict) -> str:
    return f"""#pragma once

{GENERATED_NOTICE}

/* {command["name"]!r} has no structured binding yet; use exec() to run it. */
"""


def render_header(command: dict, commands_by_name: dict) -> str:
    alias_of = command.get("alias_of")
    if alias_of is not None:
        return render_alias_header(command, commands_by_name[alias_of])

    if "variants" not in command:
        return render_empty_shell(command)

    if command.get("hand_written"):
        raise ValueError(
            f"command {command['name']!r} is marked hand_written but also has "
            "variants; a hand-written command must not carry a schema body"
        )

    enums = "\n".join(render_enum(enum_spec) for enum_spec in command.get("enums", []))
    body = render_structured_body(command)
    return f"""#pragma once

{GENERATED_NOTICE}

#include "bindings/CommandSupport.h"

{enums}
#ifdef __cplusplus
extern "C" {{
#endif

{body}
#ifdef __cplusplus
}}
#endif
"""


def render_vanilla_bindings(commands: list[dict]) -> str:
    includes = "\n".join(f'#include "{command["header"]}"' for command in commands)
    return f"""#pragma once

{GENERATED_NOTICE}

{includes}
"""


def check_no_c_name_collisions(commands: list[dict]) -> None:
    seen: dict[str, str] = {}
    for command in commands:
        c_name = command_c_name(command["name"])
        if c_name in seen and seen[c_name] != command["name"]:
            raise ValueError(
                f"command name collision after C-identifier normalization: "
                f"{seen[c_name]!r} and {command['name']!r} both normalize to {c_name!r}"
            )
        seen[c_name] = command["name"]


def main() -> None:
    schema = load_schema()
    check_no_c_name_collisions(schema["commands"])
    commands_by_name = {command["name"]: command for command in schema["commands"]}
    for command in schema["commands"]:
        # hand_written commands own their bindings/<header> file directly; the
        # generator must not touch it (else the empty-shell / stale body would
        # clobber the maintained source). vanilla.h still #includes it below.
        if command.get("hand_written"):
            continue
        write_if_changed(BINDINGS_DIR / command["header"], render_header(command, commands_by_name))
    write_if_changed(VANILLA_BINDINGS_PATH, render_vanilla_bindings(schema["commands"]))


if __name__ == "__main__":
    main()
